### ISSUE TITLE
Add tracing facility for debugging purposes

### ISSUE THREAD

**Issue by angerman** [snowleopard/hadrian#172]
As mentioned in #18. When debugging the shake build system, one often would like some tracing statements, that let one home in on certain issues.

Until we have something like `putDiagnostic`, I propose we wrap `putLoud`, and annotate most of the actions with the function call to trace what's happening.

This is just a stub to sketch out a better design prior to final implementation.

**Comment by snowleopard** [comment]
This sounds like a very useful feature.

One somewhat related idea we discussed at the start of the project was to track provenance of all settings using [ImplicitLocations](https://ghc.haskell.org/trac/ghc/wiki/ExplicitCallStack/ImplicitLocations). This could help determine where a certain flag comes from.

> Until we have something like putDiagnostic, I propose we wrap putLoud, and annotate most of the actions with the function call to trace what's happening.

An observation: many actions already print build info statements. To avoid duplicating code, we should somehow reuse this, perhaps, by tracing all these messages when they are off by `--build-info=none`.

**Comment by angerman** [comment]
Maybe we add callstacks to errors as well? Not sure if that would need to be in shake though.

**Comment by ndmitchell** [comment]
I suggest you add putChatty and use that for your tracing. 

Shake errors will have implicit locations once 8.0 is out and j wire it through. It's on the todo list.

**Comment by snowleopard** [comment]
This seem to have been forgotten, so I'm tempted to close this. I myself use `putBuild/putSuccess` for printing diagnostic info when needed and this has worked fine so far.

Feel free to reopen if debugging Hadrian is still an issue and better tools are required.
