### ISSUE TITLE
Add support for llvm toolchain / code gen

### ISSUE THREAD

**Issue by angerman** [snowleopard/hadrian#178]
This will allow us to use llvm for cross compilers that use the llvm backend. (or use llvm instead of the native code gen)

**Comment by izgzhen** [comment]
recently I am adding `-fllvm` to ghc invocation in the cross compiler case -- are they relevant?

**Comment by angerman** [comment]
Not sure if this helps. Cross compiling is basically two things:
a) choice of toolchain. (usually `<target triple>-tool`)
b) passing flags to ghc. To select the code gen backend (e.g. `-fasm`, `-fllvm` and soon `-fllvmng`)

The `-fllvm` flag just instructs ghc to use a different code path for code gen. One which involves writing out a llvm IR file, and invoking opt, llc and the mangler on it before running it through the assembler.

**Comment by chitrak7** [comment]
Hi @angerman, @snowleopard .
I stumbled upon this issue while checking ghc-quake milestone and I think that this is a necessary issue to be resolved. But I have limited information about cross-compilation and llvm. Can you please tell me where to start looking and how to address this issue.

**Comment by snowleopard** [comment]
@chitrak7 I don't know whether this issue is still relevant. Let's see what @angerman thinks.

**Comment by angerman** [comment]
This should pretty much work as is. The ceosscompilers on hackage.mobilehaskell.org are almost all llvmng based ones, and have been built with Hadrian (#445).
