### ISSUE TITLE
Test integerLibrary = integerSimple setting

### ISSUE THREAD

**Issue by angerman** [snowleopard/hadrian#179]
So far I only see we have either `integer-gmp`, or `integer-simple`. We should still be able to allow the user to choose between both.

**Comment by snowleopard** [comment]
This is already supported, see `Settings/User.hs`:
```haskell
-- | Choose the integer library: integerGmp or integerSimple
integerLibrary :: Package
integerLibrary = integerGmp
```
I never tested `integer-simple` thought -- feel free to give it a try and report on your results here.

**Comment by angerman** [comment]
Ohh. Ok. Should definetly check that out :grinning: and, improve the non-haddock documentation!

**Comment by snowleopard** [comment]
:+1:

**Comment by snowleopard** [comment]
After a minor revision above, `integerSimple` seems to work as expected in all my tests.
