### ISSUE TITLE
Visualize Dependencies

### ISSUE THREAD

**Issue by angerman** [snowleopard/hadrian#184]
I'm trying to update the `ghc-cabal` branch to the latest master, so it doesn't get forgotten about completely. See #166, and I'm continuously running into cyclic imports.
I'll try to clean them up. But I'd like to take the opportunity to gather input on inter-project dependency visualization (tools?) or a general approach, that would reduce the risk of cyclic imports with `shaking-up-ghc`, as this has been quite an issue with the `ghc-cabal` branch :disappointed:

**Comment by ggreif** [comment]
There are a few graphviz packages on hackage, notably
https://hackage.haskell.org/package/dotgen for simplifying this. Maybe
Neil can tell how to add it if there is a simple way.

**Comment by ndmitchell** [comment]
Using Shake you can visualise dependencies with the profiling, but here it's talking about the Haskell files in the build system itself, not the result of the build system.

I have to say I rarely (never?) have problems with circular imports. I suspect some more robust partitioning, grouping data and functions that operate on each other separately, and more global knowledge should work.

**Comment by angerman** [comment]
I found that there is `-ddump-minimal-imports`[1]. So maybe I'll be able to whip something together with with `dot`, to run minimal imports (and detect unused imports), and then check for clusters to find a better partitioning.

Sounds like it could work?

--- 

[1]: https://gist.github.com/dmalikov/6098556

**Comment by ndmitchell** [comment]
We are already at minimal imports, since we warn if there are any unnecessary imports.

**Comment by angerman** [comment]
@ndmitchell ohh, that's right. So unused imports won't be an issue. As far as I understand minimal-imports, it also produces the list of imported symbols per module. Thanks for pointing that out though!

**Comment by snowleopard** [comment]
One way to get rid of cyclic dependencies may be to get rid of `src/Oracles.hs` which re-exports a lot of oracle modules and instead import them directly when need be.

Not sure visualisation helps actually. I had to break cyclic dependencies several times already and usually I had to fully understand the reason for the cycle, before I could break it in a sensible way. The most recent case: https://github.com/snowleopard/shaking-up-ghc/issues/176#issuecomment-172715372. Can you get the core of the cycle? I might then be able to figure out which parts can be safely moved around to break it.

**Comment by angerman** [comment]
@snowleopard ohh, that would precisely be the idea. To better understand the cycle, have all functions point to the used symbols they use from the current project under compilation. That way cycles should be obvious, or so I hope. `-ddump-minimal-imports` would help in showing that one potentially only import a single symbol from the `Oracles`. A whole module dependency analysis could assist in understanding the dependencies.

Maybe I didn't describe what I intended well enough; and maybe such a tool exists? I could not find it though.

**Comment by snowleopard** [comment]
> `-ddump-minimal-imports` would help in showing that one potentially only import a single symbol from the Oracles.

Ah, I see now. This makes a lot of sense. Let me know if you manage to find a useful tool to assist in isolating cycles, and perhaps even suggesting possible solutions.

It's an interesting algorithmic problem actually: doing the analysis and presenting the developer with some options in the form: "Move symbol X from Y.hs to Z.hs". Hm-mm.

**Comment by snowleopard** [comment]
I'm closing this issue, as it seems to be not really related to Hadrian.

Visualising Haskell module dependencies would certainly be useful; ping me if a solution is found!
