### ISSUE TITLE
Object file not rebuild when hi file is dirty

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/hadrian#216]
While trying to reproduce #214 I came across the following bug: if I delete a `hi` file and rerun the build system, it fails to rebuild it.

Here is the explanation: we currently have two separate rules, one for producing `*.o` files which does the actual work by calling GHC on an appropriate source file, and another rule producing `*.hi` files, which simply `need`s the corresponding `*.o` file. When `*.hi` file is missing but the corresponding `*.o` file is up-to-date the `need` is a no-op.

The file in question is https://github.com/snowleopard/shaking-up-ghc/blob/master/src/Rules/Compile.hs.

An obvious solution is to combine the two rules into one by using Shake's AND-rules `&%>`, however there are some difficulties here, because the `*.o` rule is currently also responsible for calling GCC, which does not produce any `hi` files. Nothing we can't handle though.

@ndmitchell Do you have a different workaround in mind? Doesn't this problem demonstrate that rules with multiple outputs cannot be always decomposed in two rules?

**Comment by ndmitchell** [comment]
@snowleopard - indeed, multiple output rules are sometimes required. There is an encoding into files with monadic non-changing build systems (e.g. Shake) but it's pretty complex.

I think something like `provides` (https://github.com/ndmitchell/shake/issues/421) might allow you in one *.o rule to capture this dependency, but it doesn't exist yet, and is probably best viewed as a workaround rather than the right solution here.

**Comment by snowleopard** [comment]
@ndmitchell I see, thanks.

I wonder if `|%>` could perhaps be a better tool in this situation: we sometimes produce both `hi` and `o` and sometimes only `o` (for C sources). Does `|%>` allow **inclusive-OR** behaviour?

It seems a perfect use case for `&?>`, but unfortunately the test must be pure, while I need to perform an Action to find out the exact set of outputs.

**Comment by snowleopard** [comment]
On a second thought, perhaps, the following predicate for `&?>` will work?
```haskell
test :: FilePath -> Maybe [FilePath]
test file
    | takeExtension file == ".hi" = Just [file, file -<.> "o"]
    | takeExtension file == ".o"  = Just [file]
    | otherwise                   = Nothing
```

In words, if the rule is asked to build an `hi` file we will definitely produce an `o` one as well. Otherwise we can only tell about `o` for sure, although we might as well produce `hi` which will be unre

**Comment by ndmitchell** [comment]
No, `|%>` will not work - it's just sugar for a map over `%>`. Looking at the filename in the test to determine which set to produce is not allowed - any member of the set must produce all members. You really want `&%>` which produces a `File, Maybe File` - which is exactly what is required for https://github.com/ndmitchell/shake/issues/388, and I'll hopefully sort out sooner or later. For the moment, I'd just leave this as its a corner case...

**Comment by Ericson2314** [comment]
In the mean time, would it make sense to just `touch` the `hi` file so its generated in the C case?

**Comment by snowleopard** [comment]
@Ericson2314 This should work, but is not a very satisfactory solution. Hopefully we'll come up with a better one (but right now ICFP deadline takes the priority!).

**Comment by snowleopard** [comment]
The above commit should have fixed this issue, however I hit a strange lint error: https://github.com/ndmitchell/shake/issues/296#issuecomment-255193248.

Specifically, if I delete ` _build/stage1/compiler/BooleanFormula.hi` file and rebuild, I get:
```
Lint checking error - value has changed since being depended upon:
  Key:  _build/stage1/compiler/BooleanFormula.o
  Old:  File {mod=0x56F20E45,size=0x149A9,digest=0xB1F1F9FC}
  New:  File {mod=0xD660EF00,size=0x149A9,digest=0xB1F1F9FC}
```

@ndmitchell Any suggestions?

**Comment by snowleopard** [comment]
I'm closing this issue, as I believe the remaining linting error is not Hadrian's fault. If this causes problems for you, simply remove the `--lint` flag from the Hadrian build script.
