### ISSUE TITLE
$srcdir != $builddir support?

### ISSUE THREAD

**Issue by hvr** [snowleopard/hadrian#226]
Consider this a request for discussion :-)

One of Autotools neat features is support for srcdir/builddir being separate, allowing one common source-tree, and multiple builds done from that, see also

  https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html#VPATH-Builds

This is something that wouldn't have been easy with the current Makefile system because the srcdir==builddir assumption is hardcoded in too many places.

However, is the Shake-based implementation abstracted in such a way to be better suited to add  support  for this at some point in the future?

**Comment by snowleopard** [comment]
Indeed, in the new build system we have `buildRootPath = ".build"` defined in `Settings/User.hs`. We can easily override it from the command line, e.g. by switching to `buildRootPath = CmdLineFlag.BuildPath`.

However, we didn't manage to migrate all build results to `buildRootPath` yet for a number of reasons, which are being tracked in this issue: #113. To be done with this, we seem to require changes in GHC itself, and also in the `ghc-cabal` utility (another relevant ticket: #18). Both are challenging for me, and I'd welcome any help from more experienced GHC hackers!

**Comment by snowleopard** [comment]
@hvr #113 has been resolved, and we now store *almost* all build artefacts in the folder specified by the `buildRootPath` setting in `UserSettings.hs`.

The only build artefacts that remain in the source tree and seem rather hard to move are those produced by `configure` scripts from various `.in` source files. See https://github.com/snowleopard/hadrian/issues/18#issuecomment-261342028 by @ezyang about why this is difficult.

Perhaps, what we currently have already sufficient for the purposes of this ticket?

**Comment by snowleopard** [comment]
Note: PR #445 is relevant for this issue.

**Comment by snowleopard** [comment]
I think this can now be closed. The build root is fully configurable as of #531.
