### ISSUE TITLE
Switch to in-tree Cabal library

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/hadrian#228]
We currently use the Cabal library installed on the system for parsing `.cabal` files. As has been pointed out in #215, this is not a good idea, because we sometimes need features of unreleased versions of the Cabal library. Therefore we should switch to using the in-tree implementation, e.g. by compiling the build system with a flag like `-i../libraries/Cabal/Cabal`.

This seems to be not on the critical path at the moment,  but it would be great if someone could implement this in _the right way_, which may turn out to be trickier than just `-i../libraries/Cabal/Cabal`.

**Comment by ndmitchell** [comment]
What makes you think it might be trickier than -I? In what way?

**Comment by snowleopard** [comment]
I'm worried that the build system will be depending on a mix of bootstrapping packages (e.g., Shake) and GHC HEAD packages (Cabal and its dependencies). Will they play together nicely?

Also we may want to make this configurable and allow using the bootstrapping Cabal if it works -- this may be faster as it is already compiled.

**Comment by snowleopard** [comment]
Done, see the above commit. However, see #233 on how to optimise the current solution.
