### ISSUE TITLE
Run boot and configure by default

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/hadrian#234]
(This has been discussed in #204, and I think this deserves a separate issue.)

We need to optimise Hadrian's command line arguments for the most common use-case, which means the `--setup` flag will be dropped and both `boot` and `configure` will be run by default if need be, as this is what most users want. There is no reason to force everyone to remember calling Hadrian with `--setup`. 

We will also provide a way to suppress automated invocation of `boot` and `configure` if required, by passing `--skip-configure` flag. This is consistent with Shake's `--skip` flags: https://github.com/ndmitchell/shake/issues/436.

**Comment by snowleopard** [comment]
@ndmitchell Let's update [your Windows doc](https://github.com/snowleopard/hadrian/blob/master/doc/windows.md) to match this change.

There are two options:
* Drop these two commands (I think this is preferable):

    ```
    stack exec -- perl boot
    stack exec -- bash configure --enable-tarballs-autodownload
    ```
* Add `--skip-configure` to the last command.

Note, all CI instances are happy when Hadrian calls `boot` and `configure` directly.

**Comment by ndmitchell** [comment]
@snowleopard - so you now never need to run either `boot` or `configure`, and in normal development there will never be any reason to run `--skip-configure` - it's only there for people who want to make everything explicit? That's awesome!

**Comment by ndmitchell** [comment]
I'll try it, probably over the weekend.

**Comment by snowleopard** [comment]
> So you now never need to run either `boot` or `configure`, and in normal development there will never be any reason to run `--skip-configure` - it's only there for people who want to make everything explicit? That's awesome!

@ndmitchell Yes, that's correct!

> I'll try it, probably over the weekend.

:+1:

**Comment by ndmitchell** [comment]
I tried, I failed, #238.

**Comment by snowleopard** [comment]
@ndmitchell Hmm, I don't think #238 is related to this issue. Can you try building with `--skip-configure`? I'm pretty sure it will fail too. (#238 looks familiar, I remember we have already solved it once...)

**Comment by ndmitchell** [comment]
Confirmed, trying again without cleaning worked - seems like a non-deterministic race condition. Nothing to do with configure, which seems like it works nicely.

**Comment by snowleopard** [comment]
@ndmitchell Nice! So, shall I drop the `boot` and `configure` lines from your script? Or would you prefer to edit it yourself?

**Comment by ndmitchell** [comment]
Where is my script? I edited it on the blog page at http://neilmitchell.blogspot.co.uk/2016/03/compiling-ghc-on-windows.html. Did we copy it somewhere else?

**Comment by snowleopard** [comment]
Here it is: https://github.com/snowleopard/hadrian/blob/master/doc/windows.md :-)

**Comment by ndmitchell** [comment]
Ah, https://github.com/snowleopard/hadrian/blob/master/doc/windows.md - I'll link there from the blog post! And yes, please do feel free to edit it.

**Comment by ndmitchell** [comment]
Perhaps we should also add `--flavour=quick` to the list of flags, so the default first-experience is a bit faster (people will rarely want to actually use the result immediately, since then you'd just use a dist).

**Comment by snowleopard** [comment]
Done.

> Perhaps we should also add `--flavour=quick` to the list of flags

Good idea. Let me do that too. In `quick` mode my runtime is around 20min. What's your timing?

**Comment by hvr** [comment]
> Ah, https://github.com/snowleopard/hadrian/blob/master/doc/windows.md - I'll link there from the blog post! 

Can we please have `cabal`-based instructions as well? It's fine to have instructions for Stack as well of course, but plain `cabal` is the base-line for GHC development.

**Comment by hvr** [comment]
> as this is what most users want

btw, what makes you think this? ;-)

**Comment by ndmitchell** [comment]
The idea is not to give the definitive or official approach, just the simplest and most robust approach. It's not for hardcore developers, just people who want to try quickly. 

The use if stack is primarily to get MinGW installed and setup, Cabal provides no alternative to that.

**Comment by ndmitchell** [comment]
As for being what "most users" want, I'd disagree - it's exactly what I want, and I documented it so I can find it later :).

**Comment by hvr** [comment]
> just the simplest and most robust approach

fwiw, I just tried `./hadrian/build.cabal-new.sh` on an remote msys2 VM, and it just worked "simple and robust". I'm now confused why we even need a separate `build.bat` script.

> The use if stack is primarily to get MinGW installed and setup, Cabal provides no alternative to that.

That's because Stack does something (installing binaries) which is ought to be a concern of the system package manager which can do this in a really robust and sound way. I've elaborated elsewhere already why I consider this feature of Stack a convenient but wrong overreach of authority. Admittedly, I'm biased here as I'm heavily involved in `cabal` development :-)

**Comment by ndmitchell** [comment]
> on an remote msys2 VM

Which version of msys2? Where did you get it? How did you configure it? My experience is the correct answer to all these questions varies somewhat over time and is hard to reproduce. In contrast, with `stack` it's a pretty simple and direct recipe. In this case we really are using `stack` as "the thing that downloads binaries for MinGW" - the Haskell dependency engine thing is pretty irrelevant.

I agree you should use the system package manager, but these are the Windows instructions, where such a package manager doesn't exist. I'm not advocating these instructions for other platforms where installing a working gcc etc is far easier.

As for the `.bat` file, the whole idea is that we can drive the build system from the Windows command line without msys2, just relying on msys2 tools. That simplifies some things, and gets us a bit closer to compiling GHC with a GHC distribution and eliminating msys2 altogether. Still a way off, but it means you can start in command prompt, which simplifies things.

**Comment by snowleopard** [comment]
> fwiw, I just tried ./hadrian/build.cabal-new.sh on an remote msys2 VM, and it just worked "simple and robust".

@hvr It would be great if you write down precise steps one needs to take on a fresh machine to get a successful `cabal-new` GHC build. I'd be happy if we have another `/doc` entry, say `/doc/cabal-new.md`. I can test your script on my Windows machine.

> I'm now confused why we even need a separate `build.bat` script.

Both `build.sh` and `build.bat` are the baseline, as they are direct replacements of `make`. Not Cabal, not Stack, nor any other magic tool. Our current CI instances are routinely testing commits using `build` scripts. If you'd like to make sure your `/doc/cabal-new.md` script is never broken by a commit, feel free to contribute a CI script too! :-)

> btw, what makes you think this? Are we talking about GHC developers or users? Do you have empirical data to back up that claim? ;-)

Well, admittedly so far I've been closely working only with a very small sample of GHC developers. When Hadrian is deployed and we have a more significant user base we can make a proper study :-)

**Comment by hvr** [comment]
> It would be great if you write down precise steps one needs to take on a fresh machine

will do; we'll need that anyway for the GHC wiki as the officially recommended way for "hardcore developers"

> Both build.sh and build.bat are the baseline, as they are direct replacements of make

Oh, ok... so the `build.*.sh` variants were never meant to be used directly by people... this is starting to make sense now:

The previous system used

 - `./boot` to create/build (parts) of the makefile system (i.e. the traditional bootstrap-phase)
 - `./configure` is the traditional Autoconf-phase
 - `make ...` invokes the actual build-phase

and now since `build.{sh,bat}` is a direct replacement of the `make` part we get

- `./boot` (re)builds hadrian (i.e. `.shake/build.exe`) and runs autoreconf
- `./configure` same Autoconf-phase as previously
- `hadrian/build.sh ...` invokes the actual build-phase

In fact I'd like to add a top-level wrapper-`Makefile` at some point which internally just delegates to `hadrian/build.sh` so that we can have `make ...` work for the most popular  `make ...`-invocations.

the important thing to note here is that `build.sh` needs to leave `configure` and its outputs untouched, i.e. pass `--skip-configure` to `.shake/build.exe`. This has the benefit that the new build-system would feel more familiar, as it'd look like a drop-in replacement rather than a something totally new/different.

**Comment by snowleopard** [comment]
@hvr One correction: `build --skip-configure` is now a direct replacement for `make`, not simply `build`, which does more things by default.

This means the only command one normally needs to run is `build`. It will do:
* Run `./boot` to build `./configure` (if this hasn't been done before).
* Run `./configure` to build `hadrian/cfg/system.config` (if this hasn't been done before).
* Run the rest of the build commands using settings from `hadrian/cfg/system.config`.

I'm confused: why would we need another `Makefile` wrapper? Why not just use `build`?

**Comment by snowleopard** [comment]
> `./boot` (re)builds hadrian (i.e. `.shake/build.exe`) and runs autoreconf

Another correction: no, `boot` is unchanged and it was never used to build `hadrian.exe`! The executable is build by the `build` script.

**Comment by hvr** [comment]
> If you don't like the annoying cleverness of the above, simply pass --skip-configure.

why can't we leave the old legacy scripts in place for compatibility with people not wanting to use the new "cleverness"? I.e. I dont want to *have* to pass `--skip-configure`, I just want to keep using the old scripts and have a reasonable compatible behaviour. I've got Emacs setup, Debian ppa-packaging, and other helper scripts which rely on the boot/configure/make pattern. I'm really not keen to have to adapt all that, if we can simply try to be backwards compatible for common patterns. It's already bad enough that the new build-system has a signficantly different output, but I think at least that can be tweaked to be a bit more like the old output?

> I'm confused: why would we need another Makefile wrapper? Why not just use build?

 - muscle memory, I even sometimes type `make` when I really mean `cabal build`
 - other standard tooling calling `make` when there's a `Makefile`; GHC's  inventing its own build-system invocations is not gonna change existing tooling out there... ;-)

**Comment by ndmitchell** [comment]
Make is actually a pretty nice way of having small shell scripts with simple command line parsing. It's quite well suited. You just need to ignore all the dependency garbage :)

**Comment by snowleopard** [comment]
Well, fine! We can create a `make` script/wrapper which does `build --skip-configure`. No difference whatsoever for existing workflows/legacy scripts/muscle memory. And @hvr is happy, hopefully :-)

And people who come naive and legacy-free to this world, like me, will simply write `build` and can remain oblivious to the mysteries of `boot`, `configure` and other bumps on the way to a working GHC build.

**Comment by snowleopard** [comment]
> but I think at least that can be tweaked to be a bit more like the old output?

@hvr There are already several different styles of output supported through `--progress-info` flag, see the `README`: https://github.com/snowleopard/hadrian#command-line-flags. Feel free to add another one suiting your preferences.

**Comment by snowleopard** [comment]
OK, I think this can now be closed.

@hvr I'm not in a good position to lead on `/doc/cabal.md`, wrapper `make`, or `--progress-info=make` flag, but I'll be happy to help, just ping me!
