### ISSUE TITLE
userLibraryWays should override flavourLibraryWays

### ISSUE THREAD

**Issue by thomie** [snowleopard/hadrian#243]
`getLibraryWays` currently looks like this:
```
-- | Combine default ways with user modifications
getLibraryWays :: Expr [Way]
getLibraryWays = fromDiffExpr $ mconcat [ defaultLibraryWays
                                        , userLibraryWays
                                        , flavourLibraryWays ]
```

I think the order of `userLibraryWays` and `flavourLibraryWays` should be reversed. The user is always right.

**Comment by snowleopard** [comment]
Here is why I chose this ordering: it's easier to change the command line (say, by adding `--flavour=quick`) than to change `Settings/User.hs`. So, I thought that command line settings should apply last. Changing them is very cheap, as no recompilation of Hadrian is needed, so presumably users will be using them for most frequent tweaks.

> The user is always right.

But both the current flavour and `Settings/User.hs` are set by the user, right?

Maybe I'm misunderstanding the purpose of build flavours. Can you provide a more arguments why you think the ordering should be reversed?

**Comment by thomie** [comment]
In my opinion, users shouldn't be encouraged to control build settings using command line flags. If they come back to a project after a short break, they will just want to type `make` or `hadrian/build.sh` etc, and it should be a zero-build. They wouldn't remember which command line flags they used previously.

I don't think `--haddock`, `--flavour`, `--split-objects` need to exist at all. They can all just be `User.hs` settings.

Build flavours are just a combination of build settings that have turned out to be useful during ghc development. There are different ones for different use cases, for example working on the `stage1` compiler vs the `stage2` compiler, or creating a profiled ghc. A ghc developer doesn't usually create new build flavours, but they might override or add one or two settings compared to the build flavour they have chosen.

Example:
* By default, the build system creates a release build, fully optimized and including documentation
* A ghc developer might choose the `devel2` build flavour, which builds the stage2 compiler unoptimized, skips the documentation, doesn't build prof libs, doesn't split-objs, and adds the `-DDEBUG` and `-dcore-lint` flags
* But they *do* want to build the documentation, so they change `User.hs` to override just that setting

**Comment by snowleopard** [comment]
> In my opinion, users shouldn't be encouraged to control build settings using command line flags. 

@thomie This is quite a big step in the design space, away from the familiar territory of the Make build system. This also sounds as a dangerous diversion from the current project of migrating from Make to Shake, so I'm not sure now is a good time to attempt such changes. Note that in Make we could also dump all command line flags and use only `build.mk`, yet this is not how things are done. Let me invite others to this discussion: @ndmitchell, @hvr, @bgamari, @thoughtpolice, @simonmar -- what do you think?

> I don't think `--haddock`, `--flavour`, `--split-objects` need to exist at all. They can all just be `User.hs` settings.

There is at least one important reason for `--flavour` to exist: CI. Without it, we will run out of time on our CI instances. Somehow patching `Settings/User.hs` on CI seems unnecessary complicated. There are other similar scenarios, when Hadrian is called as a part of a bigger script and therefore should support tuning via command line flags.

**Comment by hvr** [comment]
quick 2cents until I get more time to elaborate: I always considered `mk/build.mk` to be a configuration file in spirit. I don't like the idea that `Settings/User.hs` takes it places, requiring a recompile of `hadrian` everytime I want to change/tweak a setting. I'm used to the `./configure` mental model which makes configuration flags/choices sticky. So that when I run `make` it keeps using whatever state `configure` persisted. I do, however, also like to inject CFLAGS or similiar via `make CFLAGS=...  some/foo.o` when I'm debugging/experimenting, that's something the dynamic nature of GNU make makes easy, having to recompile `hadrian` everytime, with the risk of invalidating  previous builds may break this workflow.

**Comment by thomie** [comment]
> This is quite a big step in the design space, away from the familiar territory of the Make build system. 

No?

> This also sounds as a dangerous diversion from the current project of migrating from Make to Shake

I'm not sure why you think this.

Users can edit `mk/build.mk` to select a build flavour and set some other settings they would like to persist. There is no way to select a build flavour using command line flags.

Keeping the `--flavour` flag for CI is fine.


Anyway, this was a minor feature request to let users override settings from `Settings/Flavours/*.hs` by editing `User.hs`. Just like they can now override settings from `mk/flavours/*` by editing `mk/build.mk` (make sure they're below the `include mk/flavours/$(BuildFlavour).mk` line!).

**Comment by thomie** [comment]
> I thought that command line settings should apply last.

Command line flags should apply last, indeed. So if nothing else changes, this issue can be closed.

Sorry, while writing my previous comments, I mistakenly assumed it was already possible to select the build flavour from `User.hs`. I now see that isn't the case (though I think it should be, and maybe a new ticket should be opened for that).

**Comment by snowleopard** [comment]
> Sorry, while writing my previous comments, I mistakenly assumed it was already possible to select the build flavour from `User.hs`. I now see that isn't the case (though I think it should be, and maybe a new ticket should be opened for that).

I think what we can do is to let the user choose the _default flavour_ in `User.hs`. And in general, this may be a good approach: the user can change default settings for all command line settings in `User.hs`, and then override them from command line if need be. Does this sound good?

Note, there is an open issue dedicated to build flavours: #188. Currently we only have two: `Default` (default) and `Quick`. I can see how some users may want to set the default flavour to `Quick`, e.g. I would do that. We can continue flavour-specific discussions there, in which case we can probably close this issue.

----

I'm fine to also have a more general discussion to elaborate on your comment that _users shouldn't be encouraged to control build settings using command line flags_. Feel free to open a new issue for that.

The current Make instructions do list command line settings like `EXTRA_HC_OPTS=-dcore-lint`, `FAST=YES`, and others: https://ghc.haskell.org/trac/ghc/wiki/Building/Using#Buildconfiguration. Plus @hvr's example. 

> There is no way to select a build flavour using command line flags.

Ah, I didn't know that. I always thought you can just do `make BuildFlavour=quick`.

**Comment by thomie** [comment]
> Does this sound good?
Yes.

I'm closing this issue, as it was mostly just misunderstanding.
