### ISSUE TITLE
progress-info option that prints each command being run

### ISSUE THREAD

**Issue by thomie** [snowleopard/hadrian#245]
I would like a flag to get progress info like this:

...
"inplace/bin/ghc-stage1" -hisuf hi -osuf  o -hcsuf hc -static  -O0 -H64m -Wall      -hide-all-packages -i -ighc/. -ighc/stage2/build -ighc/stage2/build/autogen -Ighc/stage2/build -Ighc/stage2/build/autogen    -optP-DGHCI -optP-include -optPghc/stage2/build/autogen/cabal_macros.h -package-id array-0.5.1.1 -package-id base-4.9.0.0 -package-id bytestring-0.10.8.0 -package-id containers-0.5.7.1 -package-id deepseq-1.4.2.0 -package-id directory-1.2.6.2 -package-id filepath-1.4.1.0 -package-id ghc-8.1 -package-id ghc-boot-8.1 -package-id ghci-8.1 -package-id haskeline-0.7.2.3 -package-id process-1.4.2.0 -package-id time-1.6.0.1 -package-id transformers-0.5.2.0 -package-id unix-2.7.2.0 -Wall -fno-warn-name-shadowing -XHaskell2010  -O0 -no-hs-main -threaded -no-user-package-db -rtsopts      -Wnoncanonical-monad-instances  -odir ghc/stage2/build -hidir ghc/stage2/build -stubdir ghc/stage2/build    -c ghc/./Main.hs -o ghc/stage2/build/Main.o 
...

I tried `hadrian/build.sh --progress-info=unicorn --verbose`, but it still hides too much detail.

When an error occurs, the command line *is* shown. I would just like to see it all the time.

**Comment by snowleopard** [comment]
@thomie Do you know about `verboseCommands` setting in `Settings/User.hs`? It allows to choose which commands to print verbosely in a very flexible way. For example, if you are interested in the command line just for the above case, you can use:
```haskell
verboseCommands :: Predicagte
verboseCommands = file "ghc/stage2/build/Main.o"
```
(By the way, I'm thinking of renaming `file` to `output` for clarity and also adding `input` predicates.)

A few other examples:
```haskell
-- Print command lines for all Ghc Link invocations:
verboseCommands = builder (Ghc Link)

-- Print command lines when compiling files in package compiler using Gcc:
verboseCommands = builder (Gcc Compile) &&^ package compiler 

-- Use patterns when matching files:
verboseCommands = file "//rts/sm/*" &&^ way threaded

-- Show all commands:
verboseCommands = return True
```

I think this should be sufficient. Admittedly I need to document this, so let's keep this issue open until I add some documentation.

**Comment by thomie** [comment]
Excellent, just what I was looking for.

**Comment by snowleopard** [comment]
I've added a doc, covering user settings and `verboseCommands` in particular:

https://github.com/snowleopard/hadrian/blob/master/doc/user-settings.md.
