### ISSUE TITLE
Build the User's Guide + man pages

### ISSUE THREAD

**Issue by thomie** [snowleopard/hadrian#246]
See `docs/users_guide/ghc.mk` and `rules/sphinx.mk`.

**Comment by snowleopard** [comment]
Shall this go into the list in #239?

@thomie You are on fire today -- many thanks for your help :+1:

**Comment by jmct** [comment]
There is a ghc-trac ticket that should probably be kept in mind on this which is about being able to build the user guide independently [here](https://ghc.haskell.org/trac/ghc/ticket/12619).

I am not sure if you’d like this independence to be part of the minimum viable product described in #239 or not.

**Comment by snowleopard** [comment]
@jmct Thanks! I think it would be implement independent build rules for documentation, as described in the ticket you linked.

I don't think this should be on the critical path, but it's still an important feature to work on.

**Comment by snowleopard** [comment]
By the way, I just noticed that Hadrian currently builds `mkUserGuidePart` in Stage0. Presumably this is wrong, but `mkUserGuidePart.cabal` doesn't set any restrictions on the version of the `ghc` library, hence the build succeeds. If `mkUserGuidePart` must have access to the latest in-tree `DynFlags` then I guess this should somehow be reflected in the `cabal` file?

@bgamari Shall I move `mkUserGuidePart` to Stage2 as in the Make build system?

**Comment by snowleopard** [comment]
Ah, `mkUserGuidePart` was actually moved to Stage0 by @bgamari's commit: https://github.com/snowleopard/hadrian/commit/a86f2b1e97fb7fa0ef08327f083049a41b278513.

So, I'll leave `mkUserGuidePart` where it is for now :)

**Comment by bgamari** [comment]
Andrey Mokhov <notifications@github.com> writes:

> By the way, I just noticed that Hadrian currently builds `mkUserGuidePart` in Stage0. Presumably this is wrong, but `mkUserGuidePart.cabal` doesn't set any restrictions on the version of the `ghc` library, hence the build succeeds. If `mkUserGuidePart` must have access to the latest in-tree `DynFlags` then I guess this should somehow be reflected in the `cabal` file?
>
> @bgamari Shall I move `mkUserGuidePart` to Stage2 as in the Make build system?
>
Or stage1, either way should work. Thanks for noticing!

I'll add a tighter bound on `ghc`.

**Comment by snowleopard** [comment]
> Or stage1, either way should work.

@bgamari I guess Stage1 would be preferable as it will then be a lot less overhead to build user guide only?

**Comment by snowleopard** [comment]
@bgamari Actually, perhaps the right way is as follows:

* Keep it formally in Stage0, that is, compile it with the bootstrapping GHC.
* Respect the cabal dependency on in-tree `ghc` library. This will require waiting for `ghc` library to be compiled by the bootstrapping GHC, but not introduce dependency on the Stage1 GHC.

This seems to be the right way forward.

**Comment by bgamari** [comment]
Andrey Mokhov <notifications@github.com> writes:

> @bgamari Actually, perhaps the right way is as follows:
>
> * Keep it formally in Stage0, that is, compile it with the bootstrapping GHC.
> * Respect the cabal dependency on in-tree `ghc` library. This will require waiting for `ghc` library to be compiled by the bootstrapping GHC, but not introduce dependency on the Stage1 GHC.
>
This sounds reasonable to me.

**Comment by snowleopard** [comment]
@bgamari Just to confirm: Hadrian can successfully build `mkUserGuidePart` in Stage0 even though it depends on `ghc-8.1`. I presume some other utilities, such as `ghctags`, can also be moved to Stage0, hence improving concurrency in the build?

**Comment by bgamari** [comment]
Andrey Mokhov <notifications@github.com> writes:

> @bgamari Just to confirm: Hadrian can successfully build
> `mkUserGuidePart` in Stage0 even though it depends on `ghc-8.1`.

When you say "in stage0" do you mean "with the stage0 compiler linking
against the stage1 `ghc` library? If so this sounds fine. However, if you are
linking against the stage0 `ghc` then this may break at some point (or
at very least generate incorrect documentation).

> I presume some other utilities, such as `ghctags`, can also be moved
> to Stage0, hence improving concurrency in the build?
>
Indeed this sounds quite plausible in the case of `ghctags`. I did a
quick look through the other utilities and the only other candidate for
moving to stage0 is `compare_sizes`.

**Comment by snowleopard** [comment]
> When you say "in stage0" do you mean "with the stage0 compiler linking
against the stage1 `ghc` library? If so this sounds fine.

@bgamari Yes, that's what I meant. Just to double check, I tried to build it with the `ghc == 8.2` cabal constraint instead and it failed.

I'll look into moving `ghctags` and `compare_sizes` to Stage0 too; `check-api-annotations` seems to be another candidate. Note that moving these packages to Stage0 safely will require similar modifications to their cabal files as you did with `mkUserGuidePart`.

**Comment by bgamari** [comment]
Andrey Mokhov <notifications@github.com> writes:

>> When you say "in stage0" do you mean "with the stage0 compiler linking
> against the stage1 `ghc` library? If so this sounds fine.
>
> @bgamari Yes, that's what I meant. Just to double check, I tried to
> build it with the `ghc == 8.2` cabal constraint instead and it failed.
>
Lovely.

> I'll look into moving `ghctags` and `compare_sizes` to Stage0 too;
> `check-api-annotations` seems to be another candidate.

Ahh yes, I suppose you are right.

> Note that moving these packages to Stage0 safely will require similar
> modifications to their cabal files as you did with `mkUserGuidePart`.
>
Indeed.

**Comment by snowleopard** [comment]
I'm closing this issue now. Please see #414 for what remains to be done.
