### ISSUE TITLE
Implement per-package warning suppression flags

### ISSUE THREAD

**Issue by thomie** [snowleopard/hadrian#251]
To pass validate, Hadrian should learn the per-package warning suppression flags from `mk/warnings.mk`. `Note [Order of warning flags]` in that same file might also be useful.

More info: https://ghc.haskell.org/trac/ghc/wiki/Commentary/CodingStyle#Warnings

**Comment by snowleopard** [comment]
Right, so I think per-package warning suppression flags should probably live in `Settings/Packages/*`. This seems easy enough to implement, just need to make sure the desired order of flags is respected.

Thanks for the helpful links! Note, I renamed the issue.

**Comment by snowleopard** [comment]
I'm closing this in favour of a more general issue #296.
