### ISSUE TITLE
Fix debug way

### ISSUE THREAD

**Issue by thomie** [snowleopard/hadrian#252]
```
$ ~/ghc-hadrian/inplace/bin/ghc-stage2 -debug Test.hs
[1 of 1] Compiling Main             ( Test.hs, Test.o )
Linking Test ...
/usr/bin/ld: cannot find -lHSrts_debug
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
```

It is strange, because the `debug` RTS way _is_ listed:

```
$ ~/ghc-hadrian/inplace/bin/ghc-stage2 --info | grep RTS
 ,("RTS ways","l debug thr thr_debug thr_l")
```

But the library is indeed missing:

```
$ find _build -name 'libHSrts*'
_build/stage1/rts/libHSrts.a
_build/stage1/rts/libHSrts_thr.a
```

I used `--flavour=quick` to create this build.

**Comment by snowleopard** [comment]
Thanks for documenting this.

As we say in the list of limitations, we can only properly build `vanilla` and `profiling` ways at the moment.

Let me rename this issue, we'll use it to track progress with the `debug` way.

**Comment by snowleopard** [comment]
I've accidentally fixed this while working on build flavours issues #188, #268.
