### ISSUE TITLE
Call to `getDirectoryFiles` tracks hidden files

### ISSUE THREAD

**Issue by michalt** [snowleopard/hadrian#254]
I just got a warning from shake's lint that a call to `getDirectoryFiles` changed the result (a new file was added). The problem is - the file is actually a hidden vim `.swp` file. IIRC shake's `getDirectoryFiles` automatically starts tracking the files that it returns (please correct me if I'm wrong - I'm not very familiar with shake). This would mean that if we use `"*"` as pattern, we start tracking all files in that directory (including all temporary files for editors, etc.) and thus if some of them change, this might end up unnecessary work when running hadrian.

I grepped through hadrian and it seems there is only one place we call `getDirectoryFiles` with wildcard `"*"`: `moduleFilesOracle`.

Should we just avoid `"*"` completely and try to come up with the list of patterns/extensions that we expect (`"*.hs"`, `"*.x"`, etc.)? Or is there some better way to fix this?

**Comment by ndmitchell** [comment]
Specifying the patterns we consider relevant is a much better way to go.

**Comment by snowleopard** [comment]
@michalt Thanks for reporting, this may be relevant for many GHC developers.

The module `Oracles.ModuleFiles` also has the following function:
```haskell
-- The following generators and corresponding source extensions are supported:
determineBuilder :: FilePath -> Maybe Builder
determineBuilder file = case takeExtension file of
    ".x"   -> Just Alex
    ".y"   -> Just Happy
    ".ly"  -> Just Happy
    ".hsc" -> Just Hsc2Hs
    _      -> Nothing
```

So, basically we know exactly what we are looking for and can specify this in a pattern. 

@ndmitchell I presume this won't hurt performance? I expect the cost to be dominated by traversing the the directory, not file pattern matching, so we should be fine.

I'll take care of this issue.

**Comment by ndmitchell** [comment]
@snowleopard I expect that too - especially with the latest 0.15.6 which has the tree walking performance enhancements. If you do see a regression, let me know, but I wouldn't even bother measuring - I'll be investigating as part of performance work in a little bit anyway.

**Comment by snowleopard** [comment]
I've committed a fix, see above.

@michalt Please test it and reopen the issue in case I missed anything.
