### ISSUE TITLE
I cannot read the output from Hadrian

### ISSUE THREAD

**Issue by simonmar** [snowleopard/hadrian#263]
Here's what it looks like:

![screenshot from 2016-06-10 16 18 55](https://cloud.githubusercontent.com/assets/609606/15969273/4091c49e-2f27-11e6-823d-2b9cf826b103.png)

There seems to be a contrast issue :)

**Comment by snowleopard** [comment]
@simonmar We have a setting for that! :) Have a look [here](https://github.com/snowleopard/hadrian/blob/master/doc/user-settings.md#miscellaneous).

You can redefine `putBuild` and `putSuccess` to match your terminal settings.

**Comment by simonmar** [comment]
Well yes, but I rather think the default should do something that's sensible in the majority of cases.  I dont' think I'm all that unusual in having black-on-white windows.

**Comment by snowleopard** [comment]
Well, so far this request actually is unusual: the current defaults seem to work well for most users. Only @michalt has recently asked about a different palette, which prompted us to add the setting. All my various terminals, for example, are white-on-black by default.

So, let's keep this open and if we have more people requesting to change the defaults I'm fine to do that!

Everyone:

:+1: the top comment if you'd prefer @simonmar's defaults, and :+1: my response if you are fine with the current defaults.

**Comment by snowleopard** [comment]
@simonmar @michalt By the way, please share your favourite setting for white-on-black terminals. We could at least recommend it in the docs, so people have a quick solution at hand.

**Comment by simonmar** [comment]
Why not just pick colours that work for both, that's what most other terminal software does.  Or make colours optional?

**Comment by snowleopard** [comment]
> Why not just pick colours that work for both, that's what most other terminal software does.

So, we need build progress info to stand out from normal text spit out by various builders, which led to the current choice. If you could suggest an alternative that works well for both black-on-white and white-on-black that would be great. Happy to test on my white-on-black terminals.

> Or make colours optional?

Colours are already optional, but to opt out currently you need to use `--progress-colour=never`:
```markdown
* `--progress-colour=MODE`: choose whether to use colours when printing build progress
info. There are three settings: `never` (do not use colours), `auto` (attempt to detect
whether the console supports colours; this is the default setting), and `always` (use
colours).
```
We could switch the default from `auto` to `never`, but while Hadrian is being actively developed I find colours very useful. Once Hadrian is stable, users most probably won't care much about colours and build progress info in general and we could hide most of it.

**Comment by simonmar** [comment]
> Colours are already optional

Sorry, I meant "off by default".  Anyway, I'll make a pull request.

**Comment by michalt** [comment]
Right, we had a discussion about this in #253. I'm using something like:
```
-- | Customise build progress messages (e.g. executing a build command).
putBuild :: String -> Action ()
putBuild = putColoured Dull Blue

-- | Customise build success messages (e.g. a package is built successfully).
putSuccess :: String -> Action ()
putSuccess = putColoured Dull Green
```
IMHO this is a reasonable default that should work for both dark and light backgrounds.

**Comment by simonmar** [comment]
Interestingly, that colour scheme is exactly what I was going to suggest!  The default should be something that's readable everywhere, IMO.

**Comment by snowleopard** [comment]
Thanks @michalt and @simonmar!

I tested on a white-on-black terminal: `Dull Green` looks fine, but `Dull Blue` is really very hard to read.

The following three alternatives to `Dull Blue` are fine for me, in the order of my preference:
1. `Dull Magenta`
2. `Dull Cyan`
3. `Dull Yellow`

Can you live with them? What is your ranking? (I was only looking at `Dull` variants as I assume `Vivid` ones won't work for black-on-white terminals.)

**Comment by simonmar** [comment]
1 & 2 are fine, 3 is a bit hard to read.

**Comment by snowleopard** [comment]
Thanks @simonmar!

The above commit changed the defaults to `Dull Magenta` and `Dull Green`, hopefully making Hadrian's defaults more friendly for everyone.

I think we can close this issue now, but do reopen if need be.

**Comment by simonmar** [comment]
Great, thanks for doing this :)

**Comment by michalt** [comment]
Cool, thanks!
