### ISSUE TITLE
Possible missing dependencies

### ISSUE THREAD

**Issue by simonmar** [snowleopard/hadrian#264]
There appears to be a missing dependency somewhere.  If I start from a clean build and modify say `rts/Sparks.c` and rebuild, I see this:

```
 > hadrian/build.cabal.sh --progress-colour=never --progress-info=brief -j2
Up to date
| Run Cc FindDependencies Stage1 (stage = Stage1, package = rts): rts/Sparks.c => _build/stage1/rts/Sparks.c.deps
/home/smarlow/bin/gcc -E -MM -Iincludes -Iincludes/dist-derivedconstants/header -std=gnu99 -fno-stack-protector -I_build/stage1/rts -I_build/stage1/rts/autogen -MF _build/stage1/rts/Sparks.c.deps -MT _build/stage1/rts/Sparks.o -x c rts/Sparks.c -Irts -I_build/stage1/rts '-DRtsWay="rts_v"' -O2
| Run Cc Compile Stage1 (stage = Stage1, package = rts): rts/Sparks.c => _build/stage1/rts/Sparks.o
/home/smarlow/bin/gcc -Iincludes -Iincludes/dist-derivedconstants/header -std=gnu99 -fno-stack-protector -I_build/stage1/rts -I_build/stage1/rts/autogen -c rts/Sparks.c -o _build/stage1/rts/Sparks.o -Irts -I_build/stage1/rts '-DRtsWay="rts_v"' -O2
| Run Cc Compile Stage1 (stage = Stage1, package = rts, way = thr): rts/Sparks.c => _build/stage1/rts/Sparks.thr_o
/home/smarlow/bin/gcc -Iincludes -Iincludes/dist-derivedconstants/header -std=gnu99 -fno-stack-protector -I_build/stage1/rts -I_build/stage1/rts/autogen -c rts/Sparks.c -o _build/stage1/rts/Sparks.thr_o -Irts -I_build/stage1/rts '-DRtsWay="rts_thr"' -O2 -DTHREADED_RTS
| Run Cc Compile Stage1 (stage = Stage1, package = rts, way = p): rts/Sparks.c => _build/stage1/rts/Sparks.p_o
/home/smarlow/bin/gcc -Iincludes -Iincludes/dist-derivedconstants/header -std=gnu99 -fno-stack-protector -I_build/stage1/rts -I_build/stage1/rts/autogen -c rts/Sparks.c -o _build/stage1/rts/Sparks.p_o -Irts -I_build/stage1/rts '-DRtsWay="rts_p"' -O2
shakeArgsWith                      0.000s    0%                           
Function shake                     0.143s    3%  =                        
Database read                      1.047s   25%  ==========               
Database compression               0.393s    9%  ====                     
With database                      0.036s    0%                           
Running rules                      2.408s   58%  ======================== 
Pool finished (81 threads, 2 max)  0.001s    0%                           
Lint checking                      0.065s    1%                           
Total                              4.092s  100%                           
Build completed in 0:05m
```

I would expect to see
* Various `libHSrts.a` libraries being rebuilt
* stage 2 GHC being relinked
* everything that depends on stage 2 GHC being rebuilt

**Comment by snowleopard** [comment]
My guess is that the change did not lead to modified object code, hence no further rebuilds.

Having said that, I run another experiment where the change did lead to changes in object files (changed `return 1` to `return 2` in line 78 of `rts/Spark.c`), and the rebuild chain was incomplete: only the `libHSrts_thr.a` library got rebuilt. So some dependencies are indeed missing!

**Comment by simonmar** [comment]
I also suspected that, so I changed the code in a meaningful way and still got the same result.

**Comment by simonmar** [comment]
Hmm, so the change I introduced (and you did to I suspect) only leads to a difference in the thr_o object file and hence libHSrts_thr.a.  Perhaps stage2 is not depending on the threaded RTS?  If I make a change that changes the non-threaded RTS then a ton of stuff gets rebuilt.

**Comment by ndmitchell** [comment]
Build systems are very difficult to test, particularly if you have clever recompilation avoidance on identical files. Given the Shake database it should be possible to assert that `a` depends on `b`, which might serve as useful checks? That functionality isn't exposed in Shake, but it could be.

**Comment by simonmar** [comment]
Where is the recompilation avoidance on identical files coming from?  Does Shake do that?

**Comment by ndmitchell** [comment]
It's an option that Shake provides and that @snowleopard has enabled, specifically https://github.com/snowleopard/hadrian/blob/185af600e91c5294fe8f49158ca8d73aec6ec646/src/Main.hs#L32 reads:

            { shakeChange   = ChangeModtimeAndDigest

So only consider it a change if both the modification time and the contents have changed.

**Comment by snowleopard** [comment]
> Given the Shake database it should be possible to assert that `a` depends on `b`, which might serve as useful checks? That functionality isn't exposed in Shake, but it could be.

I think that would be useful, yes. Sounds like it could even be `quickcheck`-able, e.g.: for all `.o` files in a library package directory, we have a dependent `.a` library file, etc.

**Comment by snowleopard** [comment]
> Hmm, so the change I introduced (and you did to I suspect) only leads to a difference in the thr_o object file and hence `libHSrts_thr.a`. Perhaps stage2 is not depending on the threaded RTS? If I make a change that changes the non-threaded RTS then a ton of stuff gets rebuilt.

@simonmar You are right, `rts/Spark.c` seems to only affect threaded RTS. However, I also tried a different file `rts/Stable.c`, which resulted in a really strange rebuild set, so I'm still suspicious.

**Comment by ndmitchell** [comment]
You can --report=output.json to dump a complete list of dependencies in JSON, then write whatever properties you want over that. No need to QuickCheck when enumeration works just fine.

**Comment by snowleopard** [comment]
This issue should have been fixed too, as described in https://github.com/snowleopard/hadrian/issues/267#issuecomment-255265427.

@simonmar Please reopen if more work is required.
