### ISSUE TITLE
Build failure when a .h file is moved

### ISSUE THREAD

**Issue by simonmar** [snowleopard/hadrian#267]
I encountered this error:

```
Error when running Shake build system:
* inplace/bin/mkUserGuidePart
* OracleQ (PackageDataKey ("_build/stage2/utils/mkUserGuidePart/package-data.mk","_build_stage2_utils_mkUserGuidePart_MODULES"))
* _build/stage2/utils/mkUserGuidePart/package-data.mk
* utils/mkUserGuidePart/stage2/package-data.mk
* inplace/bin/ghc-stage2
* inplace/lib/bin/ghc-stage2
* _build/stage1/libraries/ghci/libHSghci-8.1.a
* _build/stage1/libraries/ghci/SizedSeq.o
* _build/stage1/libraries/binary/Data/Binary.hi
* _build/stage1/libraries/binary/Data/Binary.o
* _build/stage1/libraries/binary/Data/Binary/Put.hi
* _build/stage1/libraries/binary/Data/Binary/Put.o
* _build/stage1/libraries/binary/Data/Binary/Builder.hi
* _build/stage1/libraries/binary/Data/Binary/Builder.o
* _build/stage1/libraries/bytestring/Data/ByteString/Builder.hi
* _build/stage1/libraries/bytestring/Data/ByteString/Builder.o
* _build/stage1/libraries/bytestring/Data/ByteString/Builder/ASCII.hi
* _build/stage1/libraries/bytestring/Data/ByteString/Builder/ASCII.o
* _build/stage1/libraries/integer-gmp/GHC/Integer/GMP/Internals.hi
* _build/stage1/libraries/integer-gmp/GHC/Integer/GMP/Internals.o
* _build/stage1/libraries/integer-gmp/GHC/Integer/Type.hi
* _build/stage1/libraries/integer-gmp/GHC/Integer/Type.o
* _build/stage1/libraries/ghc-prim/libHSghc-prim-0.5.0.0.a
* _build/stage1/libraries/ghc-prim/cbits/word2float.o
* /home/smarlow/ghc/includes/rts/storage/SMPClosureOps.h
Error, file does not exist and no rule available:
  /home/smarlow/ghc/includes/rts/storage/SMPClosureOps.h
```

Now, SMPClosureOps.h has moved from `/home/smarlow/ghc/includes/rts/storage/SMPClosureOps.h`, it now lives in `rts/`, but Hadrian doesn't rebuild things, it just fails with the above error message.

I suspect the problem is that it's using the `.c.deps` file:

```
> cat _build/stage1/libraries/ghc-prim/cbits/word2float.c.deps | grep SMPC
 /home/smarlow/ghc/includes/rts/storage/SMPClosureOps.h \
```

But the information in this file is out of date, so it needs to be regenerated.

**Comment by snowleopard** [comment]
@simonmar Thanks for documenting! I actually knew this was broken :-)

I think to fix this we should add `needed` to the rules producing `.c.deps` files: we know the list of header files to depend on only after we generated them (we refer to such dependencies as _post-use dependencies_ in the paper).

I'll take care of this.

**Comment by simonmar** [comment]
It would be nice to generate dependencies at the same time as compiling the file, using `gcc -MD`, and then call `needed` on the deps afterwards.  That way we don't need separate preprocessing and compilation rules.

**Comment by snowleopard** [comment]
@simonmar Sounds simple and straightforward to implement... I wonder why I am not doing this already :)

**Comment by snowleopard** [comment]
While studying `gcc` command line flags I came across `-MG` which lists dependencies even if some of them are generated files, such as `ghc_boot_platform.h`, and are still missing. No other output is produced in this mode, so it means we need to run `gcc` twice, which is a bit sad. (Curiously, if some generated files include other generated files, one needs to run `gcc -MG` + `need` until a fixed point is reached. Fortunately, in GHC we don't have such situations, but a friend is actually doing this in his project.)

So, we have two options:
* Do `orderOnly` on generated header files (an approximation, will break if new generated files are added), then call `gcc` once with `-MMD`, calling `needed` on the resulting list of dependencies.
* First call `gcc` with `-MG` to obtain the full list of dependencies, including generated files which may be still missing, call `need` on these files, and then compile the source by running `gcc` again.

@simonmar Shall we go for option two? We sacrifice a little in terms of accurate dependencies, but save one invocation of `gcc` per C file.

@ndmitchell I don't think you ever mentioned `-MG` -- are you aware of this flag?

**Comment by simonmar** [comment]
I'm fine with being conservative about dependencies on generated files.

**Comment by ndmitchell** [comment]
I've seen MG before, but don't generally recommend it - it's too annoying to run a fixed point. I generally recommended either `ordered` or manual scanning of include files (within any one project, scanning for headers is trivial - it's only across two projects it becomes a pain).

**Comment by snowleopard** [comment]
I believe the above commits fix the issue. 

Some key changes: 
* Object files built from C, Cmm and S sources now live in `c`, `cmm` and `S` subdirectories in the build tree. This allowed to decompose a single monolithic compilation rule into multiple separate ones (one per file type) and track dependencies more accurately.
* As discussed in #285 we now automatically detect generated dependencies (not in Haskell sources yet, unfortunately). Discovered dependencies for each `o` file are available for inspection in the corresponding `o.d` file.

@simonmar Let me know if it works for you and feel free to reopen this ticket if more work is needed.
