### ISSUE TITLE
New Cabal breaks hadrian build

### ISSUE THREAD

**Issue by KaiHa** [snowleopard/hadrian#269]
After updating _ghc_ to _master_ the build with _hadrian_ fails with
```
fatal error: _build/stage0/utils/hsc2hs/autogen/cabal_macros.h: No such file or directory
```
According to [this](https://phabricator.haskell.org/D2059#65435) this is an anticipated breakage due to the update of _Cabal_. But since I have not found any ticket that mentions it, I have created this one.

**Comment by snowleopard** [comment]
Many thanks for recording this @KaiHa.

P.S.: The last couple of weeks were extremely busy for me, so the progress with Hadrian has been slow, but I hope I'll be able to pick things up soon.

**Comment by KaiHa** [comment]
The reason the _AppVeyor_ and _Travis_ builds are broken seems also related to the new _Cabal_. ``condLibrary`` was replaced by ``condLibraries``:
```diff
diff --git a/Cabal/Distribution/PackageDescription.hs b/Cabal/Distribution/PackageDescription.hs
index 20cb29b..a792d5d 100644
--- a/Cabal/Distribution/PackageDescription.hs
+++ b/Cabal/Distribution/PackageDescription.hs

-        condLibrary        :: Maybe (CondTree ConfVar [Dependency] Library),
+        condLibraries      :: [(String, CondTree ConfVar [Dependency] Library)],
```

**Comment by snowleopard** [comment]
Hopefully the above two commits fix the issue.

**Comment by snowleopard** [comment]
Wow, Appveyor build finished in 14 mins. No idea why so fast, but I'm closing this issue.

**Comment by snowleopard** [comment]
Not sure what happened with AppVeyor, but we can now test the full build there in just 30 min!

**Comment by snowleopard** [comment]
Maybe this is the reason: https://www.appveyor.com/blog/2015/06/23/new-oss-build-environment-and-xamarin-support
