### ISSUE TITLE
Build failure `condLibraries`

### ISSUE THREAD

**Issue by Mistuke** [snowleopard/hadrian#280]
Commit 54a8e1579314b79890635323ff0e317834b720c9 switches `condLibrary` to `condLibraries`  but `condLibraries` isn't defined. At least not in `cabal-1.24` and `master`.

This causes build failures with `cabal-1.24` which is allowed by the cabal file.

```
[71 of 93] Compiling Rules.Cabal      ( src\Rules\Cabal.hs, dist\build\hadrian\hadrian-tmp\Rules\Cabal.o )

src\Rules\Cabal.hs:39:71:
    Not in scope: `condLibraries'
    Perhaps you meant `condLibrary' (imported from Distribution.PackageDescription)
```

**Comment by Mistuke** [comment]
Closing this since it seems a dup of #274

**Comment by snowleopard** [comment]
@Mistuke Is your issue resolved? Shall we drop `Cabal 1.24` from `hadrian.cabal` file to avoid problems?

**Comment by Mistuke** [comment]
Sort of, if I use the `build.cabal.sh` script it works since that seems to pick up the in-tree cabal file.
However `1.22.* || == 1.24.*` should indeed probably be dropped from the cabal file, or maybe `#ifdef` the `condLibrary` ?

Shake probably can't be used now to build `GHC 8.0.1` and `GHC 7.10.3` branches anymore. Should it?

In my case I am just working on an automated setup script, so in the end `cabal install --dependencies-only` solved my issue since it won't actually try to build shake. I would use the `sh` file but that also tries to build shake. 

I'm doing this on Windows btw, and Shake doesn't seem to work anymore due to the host detection. I'll open a ticket later once I read the instructions a bit more.

**Comment by snowleopard** [comment]
> However 1.22.* || == 1.24.* should indeed probably be dropped from the cabal file

@Mistuke Agreed. I'll look into this.

> Shake probably can't be used now to build GHC 8.0.1 and GHC 7.10.3 branches anymore. Should it?

I don't think it should: the Make build system can only (reliably) build GHC HEAD as far as I understand. One can always check-out an earlier version of the build system if an earlier version of GHC needs to be built.

> I'm doing this on Windows btw, and Shake doesn't seem to work anymore due to the host detection. I'll open a ticket later once I read the instructions a bit more.

Please do. I'm working exclusively on Windows, so hopefully we'll figure out a fix.

**Comment by snowleopard** [comment]
OK, I dropped `1.22.* || == 1.24.*`. 

Currently cannot build GHC HEAD though: #281.

**Comment by Mistuke** [comment]
It seems that the build error I was referring to before is an issue with Configure and not Hadrian related :)

**Comment by snowleopard** [comment]
@Mistuke Good to know, thanks :)
