### ISSUE TITLE
Build error: unknown function `condLibraries`

### ISSUE THREAD

**Issue by alogic0** [snowleopard/hadrian#282]
Here is what I got when ran `handrian/build.sh`
```
[137 of 159] Compiling Rules.Cabal 
...
hadrian/src/Rules/Cabal.hs:39:71:
    Not in scope: ‘condLibraries’
...    
```

Can't find where is function `condLibraries` from.

**Comment by snowleopard** [comment]
@alogic0 Strange, I thought this issue has been resolved (see #280, #274). 

Hadrian must be compiled with in-tree Cabal library, which should be handled by this command line argument in `handrian/build.sh`:
```
    -i"$root/../libraries/Cabal/Cabal"   \
```

Are you building GHC HEAD?

**Comment by snowleopard** [comment]
Ahh, it looks like the Cabal library API has been changed again.

@alogic0 Thanks for reporting this, I'll try to fix asap.

**Comment by snowleopard** [comment]
The above commit should fix this. Feel free to reopen the issue if need be.
