### ISSUE TITLE
Unnecessary rebuild and lint failure when changing the number of threads

### ISSUE THREAD

**Issue by cocreature** [snowleopard/hadrian#289]
I encountered this issue on a completely clean build (i.e., fresh clone of ghc & hadrian).

*Steps to reproduce*
```
./hadrian/build.cabal.sh --progress-info=Brief -j2 # build ghc once
./hadrian/build.cabal.sh --progress-info=Brief -j8 # build again with a different threading level
```

*Error*
```
Up to date
| Remove directory _build/stage1/libffi
| Create directory _build/stage0
| Remove directory _build/libffi-3.2.1
| Run Tar (stage = Stage1, package = libffi): libffi-tarballs/libffi-3.2.1.tar.gz => _build
| Move directory: _build/libffi-3.2.1 => _build/stage1/libffi
| Fix _build/stage1/libffi/Makefile.in
| Copy file: config.guess => _build/stage1/libffi/config.guess
| Copy file: config.sub => _build/stage1/libffi/config.sub
| Run Configure "_build/stage1/libffi" (stage = Stage1, package = libffi): _build/stage1/libffi/Makefile.in => _build/stage1/libffi/Makefile
| Remove directory _build/stage1/gmp
| No GMP library/framework detected; in tree GMP will be built
| Run Tar (stage = Stage1, package = integer-gmp): libraries/integer-gmp/gmp/tarball/gmp-5.0.3-nodoc-patched.tar.bz2 => /tmp/extra-dir-13494059728288
| Copy file: libraries/integer-gmp/gmp/gmpsrc.patch => /tmp/extra-dir-13494059728288/gmpsrc.patch
| Apply patch /tmp/extra-dir-13494059728288/gmpsrc.patch
| Copy file: libraries/integer-gmp/gmp/tarball/gmp-5.0.4.patch => /tmp/extra-dir-13494059728288/gmp-5.0.4.patch
| Apply patch /tmp/extra-dir-13494059728288/gmp-5.0.4.patch
| Move directory: /tmp/extra-dir-13494059728288/gmp-5.0.3 => _build/stage1/gmp
| Run Configure "_build/stage1/gmp" (stage = Stage1, package = integer-gmp): _build/stage1/gmp/Makefile.in => _build/stage1/gmp/Makefile
| Run Make "_build/stage1/libffi" (stage = Stage1, package = libffi): none => none
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
| Copy file: _build/stage1/libffi/inst/lib/libffi-3.2.1/include/ffi.h => _build/stage1/rts/ffi.h
| Copy file: _build/stage1/libffi/inst/lib/libffi-3.2.1/include/ffitarget.h => _build/stage1/rts/ffitarget.h
| Copy file: _build/stage1/libffi/inst/lib/libffi.a => _build/stage1/rts/libCffi.a
| Successfully built custom library 'libffi'
| Run Make "_build/stage1/gmp" (stage = Stage1, package = integer-gmp): none => none
repl-vsnprintf.c:389:0: warning: ISO C forbids an empty translation unit [-Wpedantic]
 #endif /* ! HAVE_VSNPRINTF */
 
| Create directory _build/stage1/gmp/include
| Copy file: _build/stage1/gmp/gmp.h => _build/stage1/gmp/include/ghc-gmp.h
| Copy file: _build/stage1/gmp/gmp.h => _build/stage1/gmp/include/gmp.h
| Move file: _build/stage1/gmp/.libs/libgmp.a => _build/stage1/gmp/libgmp.a
| Create directory _build/stage1/gmp/objs
| Run Ar (stage = Stage1, package = integer-gmp): _build/stage1/gmp/libgmp.a => _build/stage1/gmp/objs
| Run Ranlib (_build/stage1/gmp/libgmp.a)
| Successfully built custom library 'gmp'
shakeArgsWith                        0.000s    0%                           
Function shake                       0.212s    0%                           
Database read                        1.188s    3%  =                        
With database                        0.062s    0%                           
Running rules                       28.263s   94%  =========================
Pool finished (1094 threads, 8 max)  0.009s    0%                           
Lint checking                        0.147s    0%                           
Total                               29.882s  100%                           
Lint checking error - value has changed since being depended upon:
  Key:  _build/stage1/gmp/configure
  Old:  File {mod=0xDF76ED72,size=0xF3432,digest=0x7F0F05CD}
  New:  File {mod=0xE290CE2B,size=0xF3432,digest=0x7F0F05CD}
```
It is not rebuilding if I use the same number of threads. If I run the same command again after this lint error it exits cleanly. Switching back to `-j2` after that reproduces the error (and switching back and forth).

I am building on an up2date Archlinux 64bit installation with `cabal 1.24`. I’m happy to provide more information so just tell me what you need.

**Comment by cocreature** [comment]
Looking at the source I think https://github.com/snowleopard/hadrian/blob/master/src/Settings/Builders/Make.hs#L12 is the problem: The threading argument is simply passed on to make so gmp and libffi are rebuild. However as far as I know `make` itself does not rebuild if you change the threading argument so something else must be invalidated.

**Comment by snowleopard** [comment]
@cocreature Thanks! Interesting, I haven't seen this before, but I can reproduce this.

I believe the build should work despite the reported lint error, which simply says we've regenerated the GMP's `configure` script after we depended on it, but we didn't actually change it, resulting in the same digest `0x7F0F05CD`.

I'll look into this.

By the way, you are saying the rebuild is unnecessary, but I'm not convinved it is. Even though flags like `-jN` shouldn't affect build results, in practice it's hard to be absolutely sure of this for every builder we use... Hadrian reruns build rules whenever the build command line has changed -- are you suggesting that changes in some flags like `-jN` should be ignored?

**Comment by ndmitchell** [comment]
Some flags like -j are meant to have no effect, so should be ignored - otherwise once you stop trusting make its hard to do anything.

**Comment by snowleopard** [comment]
@ndmitchell We could, perhaps, have a list of such `(Builder, String -> Bool)` combinations that we trust have no effect on build results, filtering these out in `checkArgsHash`.

Do you have any other examples in mind?

**Comment by snowleopard** [comment]
On a second thought, this should probably be a function, e.g. `isEffectlessFlag :: Builder -> String -> Bool` in `Builder.hs`, rather than a list.

**Comment by snowleopard** [comment]
@cocreature @ndmitchell There is one other point to discuss: are we doing the right thing by simply passing `shakeThreads` to Make via `-j` flag? 

If a user runs Hadrian with `-j4` then we will end up running Make with `-j4` **plus potentially three other threads in Shake itself**, hence resulting in something like `-j7`.

Ideally, we should be running Make `withThreads 4 $ ...` when using `-j4`. @ndmitchell Can we do this in Shake? I don't think we can at the moment. Whether we should be that accurate is also unclear.

/cc @michalt

**Comment by snowleopard** [comment]
@cocreature The above should fix the lint error and significantly reduce the amount of unnecessary rebuilds for the GMP library (only zero Make build is rerun, which is fast). Could you please test?

A similar fix for Libffi is on the way.

**Comment by ndmitchell** [comment]
There is no way to say `withThreads 4`. Integrating two systems, both of which want "all" the threads, is quite a tricky thing to do. Arguably you should always be doing `-j1` for the Make, but it really depends how much difference that makes to the build times.

**Comment by snowleopard** [comment]
@ndmitchell IIRC, `-j4` gives around 2x speed up to GMP/Libffi Make, which is significant.

Users can modify this in `UserSettings` if need be, so maybe we can leave this as is.

**Comment by snowleopard** [comment]
@ndmitchell Just to clarify: by `withThreads 4` I meant a rather simple thing -- telling Shake that the action consumes 4 threads from the available pool. Similar to `unsafeExtraThread` which tells Shake that the action consumes 0 threads (intuitively, why should 0 be so special?).

Then it would be possible to do some simple manual load-balancing, i.e. decide how many threads we would like to dedicate to Make:
```haskell
-- Use parallel Make, but don't spend too many Shake's threads 
let makeThreads = max 4 $ (shakeThreads + 1) `div` 2
with makeThreads $ runMake ...
  where
    args = ... builder Make ? arg ("-j" ++ show makeThreads)
```
This gives a conservative guarantee that we never exceed `shakeThreads` and also gives us some ability to control parallelism in external builders.

**Comment by cocreature** [comment]
@snowleopard I can confirm that this solves the problem for me. I’ll leave this issue open until there is also a similar refactoring for `libffi`. Thanks for looking into this so quickly!

**Comment by snowleopard** [comment]
@cocreature Thanks! I've refactored `libffi` too, so now the rebuilds should be minimal.

I'll keep the issue open for some time, as I think we better ignore arguments like `-jN` altogether when tracking changes in the build system.

**Comment by ndmitchell** [comment]
@snowleopard Yep, I knew what you were after with `withThreads`. Unfortunately it has a few starvation issues - when I encounter one of those should I prioritise stopping other useful threads until the necessary total has been hit? The answer is probably yes, but the requirement to do so makes it a less useful function.

**Comment by snowleopard** [comment]
@ndmitchell I think the answer is yes too. And I agree, the result is suboptimal, but I don't see a better solution.

I'll do some benchmarking to see what is the effect of `-jN` on the full build. GMP and Libffi should never be rebuilt in normal GHC development, so if the full build is not affected significantly we could keep Make's sequential by default.

**Comment by ndmitchell** [comment]
If they are rarely built I'd be tempted to keep them at `max 4 (shakeThreads - 2)`, so you don't ever go too high, but you equally don't worry about going over for a bit.

**Comment by snowleopard** [comment]
@cocreature Now there should be no rebuilds whatsoever if you vary `-jN` setting when running Hadrian.

**Comment by cocreature** [comment]
@snowleopard Thanks, I can confirm that it works!

**Comment by snowleopard** [comment]
@cocreature Great, thanks!

@ndmitchell I've done some benchmarking -- the new setting of `max 4 (shakeThreads - 2)` doesn't affect the performance of full `-j4` and `-j8` builds.
