### ISSUE TITLE
Re-build failure

### ISSUE THREAD

**Issue by phadej** [snowleopard/hadrian#291]
On osx 10.10 I get only when _re-building_. Clean build succeeds always: Tried with todays ghc and hadrian masters

```
hadrian: _build/stage1/libraries/haskeline/System/Console/Haskeline/Command/History.o: openFile: does not exist (No such file or directory)
```

or

```
hadrian: _build/stage0/utils/mkUserGuidePart/Table.o: openFile: does not exist (No such file or directory)
```

or some other `.o` file is missing. Is there 

---

After that _hadrian_ thinks everything is built, but it doesn't seem to be true.

**Comment by snowleopard** [comment]
@phadej Thanks for reporting! I occasionally see this on Windows too. As far as I understand, the files are actually built. It's just the Shake's Linting procedure can't open them for some reason.

Could you confirm that the object files are actually there after Hadrian finishes?

Another similar issue #206 was eventually related to a Shake bug: https://github.com/ndmitchell/shake/issues/427.

@ndmitchell Could it be the case that the bug returned from the dead?

**Comment by snowleopard** [comment]
@phadej Could you also check if the issue disappears if you rollback to before this commit: https://github.com/snowleopard/hadrian/commit/b61423dfdb36c96a902f26b14c07e6bc39621a94?

I have a suspicion that this could be triggered by the new rule with multiple outputs (for `o` and `hi` files): https://github.com/snowleopard/hadrian/commit/b61423dfdb36c96a902f26b14c07e6bc39621a94#diff-fb1b7e33cead28ca570a892fd81b2f18R41.

**Comment by phadej** [comment]
I tried on linux machine, and it happened there as well. The file was there:
```
Total                            46.058s  100%                           
hadrian: _build/stage0/utils/mkUserGuidePart/Main.o: openFile: does not exist (No such file or directory)
phadej@system1:~/ghc/hadrian$ ll _build/stage0/utils/mkUserGuidePart/Main.o
ls: cannot access _build/stage0/utils/mkUserGuidePart/Main.o: No such file or directory
phadej@system1:~/ghc/hadrian$ ll ../_build/stage0/utils/mkUserGuidePart/Main.o
-rw-rw-r-- 1 phadej phadej 30768 Oct  24 00:20 ../_build/stage0/utils/mkUserGuidePart/Main.o
```

**Comment by phadej** [comment]
And after trying with older commit fbe22e6f83bb5e9f14960b63f1ad40dbbfdd7c86 hadrian successfully re-build ghc.

**Comment by snowleopard** [comment]
@phadej Many thanks for confirming! This indeed is related to introducing multiple-output build rules.

As a temporary workaround, you can remove the `--lint` argument from your build script.

**Comment by phadej** [comment]
@snowleopard thanks for the swift replies! I'm happy to try it again, when the issue is fixed

**Comment by ndmitchell** [comment]
This fix was added since the last release, so I suspect the bug is still there and will remain until after the release.

**Comment by snowleopard** [comment]
@ndmitchell Great! When do you plan the release?

**Comment by ndmitchell** [comment]
@snowleopard 2 weeks? I have some rebuild flags stuff to sort out, but then I'll push out a release in whatever state it is. I might even take a day and just release it at the end of that day as is - it's been too long!

**Comment by snowleopard** [comment]
The Shake bug has been fixed, so I'm closing this. Thanks @ndmitchell!

**Comment by ndmitchell** [comment]
The bug has been fixed in Shake HEAD, but not a released version...

**Comment by snowleopard** [comment]
Sure, we'll switch Hadrian to the new version as soon as it appears.
