### ISSUE TITLE
Util.customBuild breaks Shake invariant

### ISSUE THREAD

**Issue by bgamari** [snowleopard/hadrian#295]
The documentation for shake's `withResource` function states that "You cannot depend on a rule (e.g. `need`) while a resource is held." Hadrian's `Util.customBuild` does precisely this in its `Make` branch.

I suspect the `shake` documentation really means to say "you run the risk of deadlock if you depend on a rule while a resource is held" instead of the express prohibition, but it does seem best to avoid `need` while holding a resource if possible.

**Comment by snowleopard** [comment]
You are right, thanks for spotting that! I actually wanted to refactor `Util.customBuild` anyway, because it's slowly grown from a little furry thing into a 7-headed dragon.

**Comment by snowleopard** [comment]
@bgamari Should be fixed by the above commit.

**Comment by ndmitchell** [comment]
It's actually meant to be an error - see https://github.com/ndmitchell/shake/issues/504 - and I call `blockApply` which is meant to block need from working. I guess that doesn't work as expected though...

**Comment by snowleopard** [comment]
@ndmitchell Thanks! I'm fine with it being an error. I can always push `withResource` all the way to the `cmd`.

**Comment by snowleopard** [comment]
@ndmitchell I just realised that we actually never had a `need` inside a non-trivial `withResource`. The `need`s I deleted were for `Configure` and `Make` builders, but they don't (currently) use any resources, so `withResource` was called with the empty list. I guess `withResources [] $ need` is fine :-)

I'm closing this issue.
