### ISSUE TITLE
Allow build.sh to auto install dependencies

### ISSUE THREAD

**Issue by bollu** [snowleopard/hadrian#301]
It would be nice if `build.sh` automatically installed `shake`, `monad-extras`, etc.

Shall I add this step into `build.sh`?

**Comment by snowleopard** [comment]
@bollu Are you proposing to add `cabal install ansi-terminal extra mtl quickcheck shake` to `build.sh`?

I don't think we should do that. `build.sh` and `build.bat` rely on the global package database, and we do not want to mess with the user's globally installed packages.

If you would like more automation, I suggest you try `build.cabal.sh` or `build.stack.sh`, which install all Hadrian dependencies automatically without modifying the global package database.

**Comment by michalt** [comment]
@snowleopard I completely agree - modifying the global database doesn't sound like a good idea. But maybe we should make the `build.cabal.sh` (or `build.stack.sh`) more prominent? Currently `build.sh` has the shortest name and so it might appear to be the "default/recommended" option.

**Comment by snowleopard** [comment]
@michalt Yes, I think we'll have to do this at some point.

Most probably the shortest `build.*` command should be reserved for building with Cabal, because it's always available. We can keep `build.stack.*` as is, and rename `build.*` into e.g. `build.global.*`? Have you got any other suggestions?

**Comment by ndmitchell** [comment]
It seems like `build.cabal.*` and `build.stack.*` should exist so users can pick, but probably `build.*` should just forward on to `build.cabal.*`? And probably `build.cabal.*` should use sandboxes?

**Comment by snowleopard** [comment]
> And probably `build.cabal.*` should use sandboxes?

@ndmitchell It already uses sandboxes.

> probably `build.*` should just forward on to `build.cabal.*`?

Yep, good idea!

**Comment by snowleopard** [comment]
With #428 fixed, I think we can close this one too.
