### ISSUE TITLE
Document on debugging Hadrian

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#308]
I think it would be nice to have a document on how to debug Hadrian. For example, what tools you typically use to debug it, whether there is some magic switch in either Hadrian or GHC that provides useful information about the build etc.

While it would take quite some time to write a complete guide on this, we can always start with something trivial and do it incrementally. It should be not be a burden.

**Comment by snowleopard** [comment]
Very good point, we definitely need something like this.

Debugging is quite hard currently. I typically just use print-debugging, i.e. inserting noticeable `putSuccess` statements in key places in the build system and rebuilding. 

Perhaps, @ndmitchell can share some tricks how to debug Shake-based build systems?

**Comment by izgzhen** [comment]
Added a wiki page https://github.com/snowleopard/hadrian/wiki/Debugging with some initial contents.

I chose to put this on wiki because we can change wiki pages frequently and conveniently. We can put a link in README points to this place.

**Comment by bgamari** [comment]
What is the equivalent to passing `WERROR=` in the old build system?

**Comment by snowleopard** [comment]
@bgamari There is none at the moment. This could be implemented through `CmdLineFlag`:

https://github.com/snowleopard/hadrian/blob/master/src/CmdLineFlag.hs

The intended behaviour is not entirely clear to me. Could you open a new issue outlining what needs to be done?

**Comment by bgamari** [comment]
See #332.

**Comment by ndmitchell** [comment]
I wrote a doc at http://shakebuild.com/debugging - updates welcome.

**Comment by izgzhen** [comment]
I'll close this, since we already started doing that

**Comment by snowleopard** [comment]
@izgzhen Thanks! I've also added a section on troubleshooting, linking to the wiki.
