### ISSUE TITLE
When a program is rebuilt all dependent rules are rerun, even if the program's binary is unchanged

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/hadrian#31]
When a program, such as `ghc-pkg` is rebuilt, we have to rerun all rules that depend on it, even if the program's resulting binary is not changed.

We need to implement something like Shake's `writeFileChanged` in order to suppress unnecessary rebuilds. Pragmatically, we can rely on a simple heuristic to check binaries for equality, e.g. comparing file sizes. Incidentally, is this the purpose of `utils/compareSizes`?

**Comment by quchen** [comment]
We have to re-check all dependencies once a binary's dependencies change. Why is this a problem? I think we should very much stay away from pragmatic solutions (which just means "wrong and broken" to me) like comparing file sizes.

**Comment by snowleopard** [comment]
@quchen I agree that comparing file sizes is fragile. 

What if we do an honest comparison of the old binary with the new one? Would you still want to re-run an identical binary? If yes, why?

I think the fewer unnecessary rebuilds we do, the better.

**Comment by quchen** [comment]
How do we know the new binary will be the same as the old if we don't rebuild it? :-s

**Comment by snowleopard** [comment]
We do have to rebuild it, of course! If the new binary is different we dump the old one and rebuild all dependencies.

However, if the new binary is the same, I propose not to rerun all dependent rules. This can sometimes save significant time.

Shake has a similar primitive, called `writeFileChanged`, which we use in the build system for text files. We might be able to use it for binary files too but I have to check this.

**Comment by quchen** [comment]
Oh, you mean we build a new executable in a temporary location, and then overwrite the old executable conditionally, so that it won't be touched if nothing needs to be done? Sounds hacky, I'm not convinced. Shake compares files by modification time by default, I think - could we switch it to `ChangeModtimeAndDigest` to check modification time, and then if necessary digest ("contents"), to trigger a rebuild. For more info, see the [Change type](http://hackage.haskell.org/package/shake-0.15.5/docs/Development-Shake.html#t:Change).

**Comment by snowleopard** [comment]
> Sounds hacky, I'm not convinced.

Yes, I agree. I'm not convinced either.

> Shake compares files by modification time by default, I think - could we switch it to `ChangeModtimeAndDigest(Input)` to check modification time, and then if necessary digest ("contents"), to trigger a rebuild? 

Sounds promising! I'll have a look at this approach once more critical issues are out of the way.

**Comment by snowleopard** [comment]
@quchen Unfortunately `ChangeModtimeAndDigest` doesn't help. The binary of `ghc-pkg` does change slightly (14 bytes are different) even if the source files are unchanged.

The file size remains the same, however.

That may be a `ghc` bug, but even if it's fixed older bootstrapping versions of `ghc` will keep breaking things for us.

**Comment by bgamari** [comment]
Note that currently GHC isn't terribly good in the determinism department; what you are observing may be a result of this. That being said, things are rapidly improving thanks to Simon Marlow's group. It's not out of the question that we could have completely deterministic output in the 8.0 release.

**Comment by snowleopard** [comment]
@bgamari Good to hear!

What's interesting is that even the binary of `hp2ps` changes, where we use `ghc` only for linking. I'd imagine this step to be relatively straightforward determinism-wise.

**Comment by bgamari** [comment]
Hmm, that is indeed curious. Could you describe how you are testing this?

**Comment by snowleopard** [comment]
Assuming you can build `hp2ps` on your system, you can test this as follows:
```bash
mv hp2ps hp2ps-old
./build.sh
diff hp2ps hp2ps-old
```

**Comment by ndmitchell** [comment]
If you want to avoid rebuilding when changing `ghc-pkg` in non-interesting ways I suggest linking `ghc-pkg` to `ghc-pkg2`, and copying it over the top if it has changed (or changed in interesting ways, if you can automatically skip 14 irrelevant bytes).

**Comment by snowleopard** [comment]
I think we can close this. The `ChangeModtimeAndDigest` setting works fine, and GHC's determinism has improved.
