### ISSUE TITLE
Missing dist-derivedconstants

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#310]
In standard build, we will have multiple targets in `includes/dist-derivedconstants`, like `includes_GHCCONSTANTS_HASKELL_VALUE` (equals to `includes/dist-derivedconstants/header/platformConstants`).

They will be installed to `/usr/local/lib/ghc-<version>/includes`.

Related issue: https://github.com/snowleopard/hadrian/issues/219

Related make script: https://github.com/ghc/ghc/blob/master/includes/ghc.mk#L170

**Comment by snowleopard** [comment]
These files are built in `_build/generated` and can be copied from there to appropriate destination during installation. Note, we have the following `installTargets` in `Rules/Generate.hs`:
```haskell
installTargets :: [FilePath]
installTargets = [ "inplace/lib/ghc-usage.txt"
                 , "inplace/lib/ghci-usage.txt"
                 , "inplace/lib/platformConstants"
                 , "inplace/lib/settings"
                 , "inplace/lib/template-hsc.h" ]
```

Also see `copyRules` which already copies `inplace/lib/platformConstants`:
```haskell
copyRules = do
    "inplace/lib/ghc-usage.txt"      <~ "driver"
    "inplace/lib/ghci-usage.txt"     <~ "driver"
    "inplace/lib/platformConstants"  <~ generatedPath
    "inplace/lib/settings"           <~ "."
    "inplace/lib/template-hsc.h"     <~ pkgPath hsc2hs
    rtsBuildPath -/- "c/sm/Evac_thr.c" %> copyFile (pkgPath rts -/- "sm/Evac.c")
    rtsBuildPath -/- "c/sm/Scav_thr.c" %> copyFile (pkgPath rts -/- "sm/Scav.c")
  where
    file <~ dir = file %> copyFile (dir -/- takeFileName file)
```

**Comment by izgzhen** [comment]
Oh right, thanks a lot!

BTW, I guess I might need to modify `inplace/lib` part. I've written something equivalent to `$(ghclibdir)`.

I will close the issue now.
