### ISSUE TITLE
macOS clang complains -Wno-unknown-pragmas

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#311]
I saw this during building latest Hadrian (4952e80):

```
on the commandline: warning:
    unrecognised warning flag: -Wno-unknown-pragmas
```

Related code: 

- https://github.com/snowleopard/hadrian/blob/1774b40d0be398953bc0ad03bc364a951d971a7b/src/Settings/Builders/Common.hs#L52
- https://github.com/snowleopard/hadrian/blob/4952e8022f805d31035c3ecfd354518c72d07557/src/Settings/Default.hs#L77

clang version:

```
> clang --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I don't know if that is related to Clang's version. I made the change at https://github.com/snowleopard/hadrian/pull/309/files#diff-767d02e64fe5701ad5a0f02510f2c1dcR77 according to https://github.com/ghc/ghc/blob/master/mk/warnings.mk#L37

**Comment by snowleopard** [comment]
@izgzhen Thanks for reporting! Not sure what's going on. Your PR seems to match the Make behaviour.

Do you get the warning on your MacOS machine?

**Comment by izgzhen** [comment]
Yes, there were several Xcode updates rolled out recently, but I am not sure if this is related.

But anyway this is a low-priority issue.

**Comment by izgzhen** [comment]
Looks like this is not actually true, my `clang` understands this now.
