### ISSUE TITLE
Switch to python-based boot

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/hadrian#314]
The `boot` script has been rewritten from Perl to Python: https://phabricator.haskell.org/D3567

There are a few trivial fixes we need to do in Hadrian and on CI bots to support this, but at the moment we put this on hold until the Windows build is fixed in GHC, see this comment:

https://phabricator.haskell.org/D3567#102663

/cc #312

**Comment by snowleopard** [comment]
The `boot` script is back to Perl for now: https://github.com/ghc/ghc/commit/7fce4cbc0e0d00352826c5ef1d7f6bf8dbb826b9

**Comment by bgamari** [comment]
As of ghc/ghc@4671009efc450479c02e3ecf847c63a7483778fa we are back to the Python `boot` script. Yay!

**Comment by snowleopard** [comment]
@bgamari Your link appears to be broken.

Anyway, we'll need to adapt Hadrian to Python-based `boot`, so I think this issue should be reopened.

**Comment by bgamari** [comment]
Fixed.

**Comment by snowleopard** [comment]
After switching to the python based script, I get the following error on Windows:

```
Error when running Shake build system:
* OracleQ (KeyValue ("hadrian/cfg/system.config","host-os"))
* hadrian/cfg/system.config
* hadrian/cfg/system.config settings mk/config.h
* mk/config.h.in
* configure mk/config.h.in
user error (Development.Shake.cmd, system command failed
Command: python3 boot
Exit code: 1
Stderr:
Traceback (most recent call last):
  File "boot", line 184, in <module>
    autoreconf()
  File "boot", line 143, in autoreconf
    ac_local = os.environ['ACLOCAL_PATH']
  File "C:/msys/mingw64/lib/python3.5\os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'ACLOCAL_PATH'
)
```

I think this environment-fixing code needs a fix:

https://github.com/snowleopard/hadrian/blob/master/src/Environment.hs#L20-L28

**Comment by snowleopard** [comment]
Apparently, the old `ACLOCAL_PATH` workaround we had in `Environment.hs` is no longer needed, so I dropped it. Looks like there is nothing else to be done for this issue, so I'm closing it.
