### ISSUE TITLE
OS X CI timeout

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#322]
This is not a new issue: we had frequent OS X CI timeout on Travis, because the build took too long. Very sparsely, it can finish within the time limit.

It can be annoying since we might never know if the build will actually succeed or not (lucky that my dev machine is OS X), not to say spending more time running tests.

[Circle CI](http://circleci.com) provides better OS X support, but it is not free. Travis also supports a beta-version [cache mechanism](https://docs.travis-ci.com/user/caching/), which seems useful (as in https://github.com/travis-ci/travis-ci/issues/6410), but I am not sure about this.

**Comment by snowleopard** [comment]
One possible solution is to use a different (faster) bootstrapping compiler. I hear GHC 8.2 is fast -- perhaps it could bring build times down?

**Comment by izgzhen** [comment]
> I hear GHC 8.2 is fast -- perhaps it could bring build times down?

I can try this one later on.

**Comment by izgzhen** [comment]
> > I hear GHC 8.2 is fast -- perhaps it could bring build times down?
> 
> I can try this one later on.

Well, `brew` only supports the stable release, i.e. `8.0.2` (which is supposed to be used currently).

**Comment by izgzhen** [comment]
As mentioned in #325, this time even Linux build timeouts.

Another thought on infrastructure is to see if the larger community can help on this, like providing a self-hosted Linux build bot.

@jaspervdj Do you have any suggestion on this?

**Comment by izgzhen** [comment]
Building with `dyn` way on my MacBook Pro needs 112 minutes

**Comment by jaspervdj** [comment]
The caching mechanism for Travis works fairly well.

I'm not sure about a build bot, but since this is for a GHC-related project, @hvr might know more.

**Comment by izgzhen** [comment]
https://circleci.com/gh/izgzhen/hadrian/43 (not sure it is publicly viewable...)

I've successfully built hadrian with CircleCI OS X. I applied for their OSS seed plan two weeks ago, and it looks like their service is less likely to time out than Travis's.

@snowleopard What's your idea?

**Comment by snowleopard** [comment]
@izgzhen Nice! Looks like it's pretty fast. But as far as I see it's not free (beyond the two-week trial).

**Comment by izgzhen** [comment]
I applied a special program for Open Source project, we can use the Seed
Plan for free.

**Comment by snowleopard** [comment]
If we can use it for free then sure, let's add another CI integration to Hadrian!

**Comment by izgzhen** [comment]
It looks like new CI works pretty well, may we close this issue now?

**Comment by izgzhen** [comment]
Also, what do you think about switching off Travis's OS X build? It might be misleading if there is an error on the badge, although leaving it there can let us know when OS X is well supported again on Travis ASAP.

**Comment by snowleopard** [comment]
Yes, it looks like CircleCI is working well.

I'm thinking that perhaps we could repurpose the Travis OS X build for building, say, only `ghc-stage1` with a different bootstrapping compiler? Or, if GHC 8.0 is faster, perhaps we could even afford the full build?

**Comment by izgzhen** [comment]
> I'm thinking that perhaps we could repurpose the Travis OS X build for building, say, only ghc-stage1 with a different bootstrapping compiler? Or, if GHC 8.0 is faster, perhaps we could even afford the full build?

Good point, I'll try it later;

**Comment by izgzhen** [comment]
Let's close it for now?

**Comment by snowleopard** [comment]
@izgzhen Yes, I think our current CI support is quite good. Thanks!
