### ISSUE TITLE
Should pre-defined build flavors be consistent with the old system?

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#326]
For example, the `quickest` in old system will include the `dynamic` way, but in Hadrian, we might want to be *literally* the "quickest" way by not including the dynamic way at all.

The pros for being consistent with legacy definition of some way is:

1. Less confusing for developers migrating from the old system
2. Easier to port more logic from Makefiles directly without worrying about breaking some hard-coded implicit dependency on what "quickest" or alike mean

The cons for it, or the pros for having our own interpretation of "quickest", are:

1. More sane for newcomers
2. Show the potential problem hidden by the second "pro" above

A middle ground, might be

- Use new names for different dependencies
- Document the new name and the old name

So when people gets confused about names they can still lookup and pick whatever they want.

Like `quickest`, we can build dynamic libs for `quickest`, but not for a similar one called `quickest_static` or `fast_n_furious` (kidding).

**Comment by snowleopard** [comment]
> Easier to port more logic from Makefiles directly without worrying about breaking some hard-coded implicit dependency on what "quickest" or alike mean

@izgzhen As far as I understand, all flavour-related logic is quite straightforward in the Make build system and lives in `mk/flavours`. There is nothing else to port.

> `fast_n_furious` (kidding)

I actually like this one :) 

@bgamari what is your opinion? Is it important for GHC devs that the `quickest` flavour builds dynamic libs?

**Comment by izgzhen** [comment]
Ping back: https://github.com/snowleopard/hadrian/blob/master/doc/flavours.md

**Comment by snowleopard** [comment]
@izgzhen By the way, I think all flavours except for `quickest` now build `dynamic` ways, so we should update the above link.

**Comment by izgzhen** [comment]
Something suddenly hit my mind -- maybe we can provide a `blazing` or whatever that compiles _as least packages as possible_ in the stage1. For example, do we need to build `haskeline` to development the build system itself? etc.

**Comment by snowleopard** [comment]
I think `quickest` already does that. Note: `ghc-bin` depends on `haskeline` (see the `ghc/ghc-bin.cabal` file).

**Comment by bgamari** [comment]
Somehow I previously missed this; I don't think that dynamic libraries are critical for `quickest`. In general I think the set of flavours that we currently have in the tree are more a product of a gradual, largely accidental evolution than any grand plan. They all scratched an itch for someone at some point, but I think we should feel free to tweak them if there is good reason.

**Comment by snowleopard** [comment]
@bgamari Thanks! I think at some point after we merge, we should reengineer flavours. Preferable according to some plan :)

**Comment by snowleopard** [comment]
By the way, judging from @bgamari's response, we can close this issue with the answer "No, flavours do not need to be consistent with the old system".
