### ISSUE TITLE
A means to disable WERROR is needed

### ISSUE THREAD

**Issue by bgamari** [snowleopard/hadrian#332]
Some configurations of the current build system (e.g. the validation flavour) pass `-Werror` to various toolchain components. Hadrian seems to go farther, always enabling `-Werror`. This isn't necessarily a bad thing, but it does mean that it is essential that we have a means of disabling it. For instance, I recently attempted a series of builds with Hadrian on our Tier 2 platforms and found in several cases that I was forced to fix warnings. Fixing warnings isn't bad, but being forced to fix warnings when you really just want to see whether something builds can be quite annoying. In the previous build system I would generally just invoke `make` with `WERROR=""`, disabling `-Werror`.

**Comment by snowleopard** [comment]
You can currently remove `-Werror` in the user settings file, see some docs here:

https://github.com/snowleopard/hadrian/blob/master/doc/user-settings.md#command-line-arguments

Specifically, you can do: `userArgs = remove ["-Werror"]`.

Is this sufficient, or do we really need to do this via the command line?

**Comment by bgamari** [comment]
I think doing this in the user settings file is perfectly sufficient. Thanks!

**Comment by bgamari** [comment]
One thing that might help, however, is to add a placeholder `userArgs` value in the template `UserSettings.hs`, although with a docstring.
