### ISSUE TITLE
Hadrian appears not to respect configure options

### ISSUE THREAD

**Issue by bgamari** [snowleopard/hadrian#333]
For instance, when you pass `--with-curses-libraries` to `configure`, the appropriate flag is not propagated to `terminfo`'s `configure` script.

**Comment by bgamari** [comment]
Actually, it looks like the issue is just the `curses` logic missing. I've added it to #331.

**Comment by snowleopard** [comment]
With #331 merged this can now be closed, I think. Please reopen if need be.
