### ISSUE TITLE
Implement Stage1Only

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#337]
I think we probably don't have this feature and we need it to support #177.

Except for the control switch, we also need to know what can be built at stage0 and what can't (will `latestBuildStage` cover this? @snowleopard ?)

**Comment by izgzhen** [comment]
How will this feature interact with https://github.com/snowleopard/hadrian/issues/250?

**Comment by izgzhen** [comment]
Some notes:

```
Stage1Only=YES means:
   - don't build ghc-stage2 (the executable)
   - don't build utils that rely on ghc-stage2
     See Note [No stage2 packages when CrossCompiling or Stage1Only] in
     ./ghc.mk.
   - install ghc-stage1 instead of ghc-stage2
   - install the ghc-pkg that was built with the stage0 compiler
   - (*do* still build compiler/stage2 (i.e. the ghc library))
   - (*do* still build all other libraries)
```

**Comment by snowleopard** [comment]
@izgzhen When I was looking into this feature, I thought that we could simply build Stage1 GHC in a phony `stage1only` build rule, i.e. `"stage1only" ~> needBuilder $ Ghc CompileHs Stage1`.

Do you think this is sufficient?

> How will this feature interact with #250?

I think if the user requests both to build only stage 1 GHC and to skip all stage 1 build rules, then nothing should be rebuilt.

**Comment by izgzhen** [comment]
> "stage1only" ~> needBuilder $ Ghc CompileHs Stage1.
> Do you think this is sufficient?

Maybe not. What about other binary utils built in stage0? I think I can conduct a comparative experiment to show what is needed.

**Comment by snowleopard** [comment]
> What about other binary utils built in stage0?

All utils that are required for building stage1 GHC (such as `ghc-pkg`) will be built transitively.

> I think I can conduct a comparative experiment to show what is needed.

👍
