### ISSUE TITLE
Missing binaries: count_lines, mkdirhier

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#339]
I found `count_lines`, `mkdirhier` in my latest building of GHC using the old build system.

**Comment by snowleopard** [comment]
These seem to be not needed in Hadrian, where we can easily implement the functionality in Haskell. So I never bothered to build these builders. Do you think we might actually need them?

**Comment by izgzhen** [comment]
> Do you think we might actually need them?

I don't think we need them if so. Let's close this issue.
