### ISSUE TITLE
Fix install rule on Windows platform

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#345]
When #312 is merged, OS X and Linux tests are good, but we are yet not sure whether it will work on Windows.

**Comment by snowleopard** [comment]
Thanks, I'll take care of this.

**Comment by snowleopard** [comment]
I've tried installing on Windows and got the following error:
```
Error when running Shake build system:
* install
user error (Development.Shake.cmd, system command failed
Command: /usr/bin/install -c -m 755 -d /home/nam83/test-install/usr/local/lib/include
/usr/bin/install: createProcess: does not exist (No such file or directory))
```

Executing the command locally works fine, but for some reason it doesn't work from Shake.

**Comment by snowleopard** [comment]
This could be because the `install-dir` setting on my machine is `/usr/bin/install -c -m 755 -d` and the spaces screw up things.

@izgzhen What is this setting equal to on your machine?

**Comment by izgzhen** [comment]
on my Mac:

```
install-dir     = /usr/local/bin/ginstall -c -m 755 -d
```

**Comment by izgzhen** [comment]
> The following command works fine: cmd ["install", "-c", "-m", "755", "-d"] dir, so I can run install but not /usr/bin/install.

Shouldn't autoconf figure out a correct `@INSTALL` automatically?

**Comment by snowleopard** [comment]
@izgzhen I fixed the issue in the above commit -- paths on Windows require special attention.

I now hit the following:

```
| Install program inplace/lib/bin/ghc-stage2.exe to /home/nam83/test-install/usr/local/lib/bin
/-----------------------------------------------------------------------\
| Move file                                                             |
|      input: /home/nam83/test-install/usr/local/lib/bin/ghc-stage2.exe |
|  => output: /home/nam83/test-install/usr/local/lib/bin/ghc.exe        |
\-----------------------------------------------------------------------/
shakeArgsWith   0.000s    0%
Function shake  0.315s    7%  ==
Database read   0.485s   11%  ===
With database   0.031s    0%
Running rules   3.256s   79%  =========================
Total           4.087s  100%
Error when running Shake build system:
* install
renameFile: does not exist (The system cannot find the path specified.)
```

Will try to figure it out tomorrow.

**Comment by izgzhen** [comment]
I guess `renameFile` is something Windows specific, similar to `mv`...

**Comment by snowleopard** [comment]
Actually, the above fixes it -- we use the same trick in `moveDirectory`.

Now the install stops here:

```
| Install directory /home/nam83/test-install/usr/local/lib/bin
| Successfully generated inplace/lib/bin/ghc-split.
| Make 'inplace/lib/bin/ghc-split' executable.
| Install script inplace/lib/bin/ghc-split to /home/nam83/test-install/usr/local/lib/bin
| Install directory /home/nam83/test-install/usr/local/bin
shakeArgsWith   0.000s    0%
Function shake  0.331s    2%
Database read   0.721s    4%  =
With database   0.029s    0%
Running rules  13.743s   92%  =========================
Total          14.823s  100%
Error when running Shake build system:
* install
/home/nam83/test-install/usr/local/bin/ghc-8.3.20170713.exe: openFile: does not exist (No such file or directory)
```

**Comment by izgzhen** [comment]
https://github.com/snowleopard/hadrian/blob/master/src/Rules/Install.hs#L76

that might be relevant. What is in `inplaceLibBinPath` in the Windows case?

**Comment by snowleopard** [comment]
> What is in `inplaceLibBinPath` in the Windows case?

It's not platform-dependent:

https://github.com/snowleopard/hadrian/blob/master/src/Settings/Path.hs#L53

By the way, the file in question (`ghc-8.3.20170713.exe`) is nowhere to be found on my machine.

**Comment by izgzhen** [comment]
I mean, the binaries inside that directory can be named differently. I have
the impression that windows version doesn't append a version number, so
this ghc.exe is directly copied to the lib/bin and a wrapper in bin, no
symlink needed.

**Comment by snowleopard** [comment]
Ah, sorry, I misread your comment. Here is the contents of `inplace/lib/bin` on my machine after a successful build:
```
ghc-pkg.exe  ghc-stage2.exe  hpc.exe     runhaskell.exe  unlit.exe
ghc-split    hp2ps.exe       hsc2hs.exe  touchy.exe
```

**Comment by izgzhen** [comment]
Oh ... maybe I am asking a non-relavent question.

```
$ cd usr/local/
$ ls
bin   lib   share
$ cd bin 
$ ls
ghc                     hpc                     runhaskell
ghc-8.3.20170713        hpc-8.3.20170713        runhaskell-8.3.20170713
ghc-pkg                 hsc2hs
ghc-pkg-8.3.20170713    hsc2hs-8.3.20170713
$ cd ../lib
$ ls
ghc-8.3.20170713
$ cd ghc-8.3.20170713/bin
$ ls
ghc        ghc-split  hpc        runhaskell
ghc-pkg    hp2ps      hsc2hs     unlit
```

Also, the most possible source of `/home/nam83/test-install/usr/local/bin/ghc-8.3.20170713.exe: openFile: does not exist (No such file or directory)` should be https://github.com/snowleopard/hadrian/blob/master/src/Rules/Install.hs#L113-L114, I guess. Although I don't know that `writeFileChanged` could even fail.

**Comment by snowleopard** [comment]
We are not using wrappers on Windows, but the above code seems to be unconditional -- I guess, this is the reason?

**Comment by izgzhen** [comment]
> I guess, this is the reason?

Okay, the fix should be simple: just need to add another condition on `windowsHost` and copy stuff directly from `lib/bin` to `bin`

**Comment by snowleopard** [comment]
Sorry, I don't think I follow. How will the code look?

**Comment by izgzhen** [comment]
Like:

```diff
diff --git a/src/Rules/Install.hs b/src/Rules/Install.hs
index 57cf008..7e934fd 100644
--- a/src/Rules/Install.hs
+++ b/src/Rules/Install.hs
@@ -89,8 +89,12 @@ installBinPkgs =
 installBins :: Action ()
 installBins = do
     binDir <- setting InstallBinDir
+    libDir <- installGhcLibDir
     installDirectory (destDir ++ binDir)
-    forM_ installBinPkgs $ \pkg ->
+    win <- windowsHost
+    if win then do
+      copyDirectoryContents (destDir ++ libDir -/- "bin") (destDir ++ binDir)
+    else forM_ installBinPkgs $ \pkg ->
         withLatestBuildStage pkg $ \stg -> do
             let context = programContext stg pkg
             version <- setting ProjectVersion
```

**Comment by snowleopard** [comment]
Thanks, will give it a try tonight!

**Comment by snowleopard** [comment]
@izgzhen After digging a bit more, the `install` rule now finishes successfully on my Windows machine 🎉 



However, the built GHC does not work. If I run `ghc -e 1+2` from `lib/bin` I get this:
```
ghc.exe: panic! (the 'impossible' happened)
  (GHC version 8.3.20170713 for x86_64-unknown-mingw32):
        can't decompose ghc.exe path: "C:\\msys\\home\\nam83\\test-install\\usr\\local\\lib\\bin\\ghc.exe"

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```

And if I run it from `bin` I get this:
```
<interactive>:1:19: error:
    Not in scope: `System.IO.hSetBuffering'
    No module named `System.IO' is imported.

<interactive>:1:43: error:
    Not in scope: `System.IO.stdin'
    No module named `System.IO' is imported.

<interactive>:1:60: error:
    Not in scope: data constructor `System.IO.NoBuffering'
    No module named `System.IO' is imported.

<interactive>:1:81: error:
    Not in scope: `GHC.Base.thenIO'
    No module named `GHC.Base' is imported.

<interactive>:1:99: error:
    Not in scope: `System.IO.hSetBuffering'
    No module named `System.IO' is imported.

<interactive>:1:123: error:
    Not in scope: `System.IO.stdout'
    No module named `System.IO' is imported.

<interactive>:1:140: error:
    Not in scope: data constructor `System.IO.NoBuffering'
    No module named `System.IO' is imported.

<interactive>:1:161: error:
    Not in scope: `GHC.Base.thenIO'
    No module named `GHC.Base' is imported.

<interactive>:1:179: error:
    Not in scope: `System.IO.hSetBuffering'
    No module named `System.IO' is imported.

<interactive>:1:203: error:
    Not in scope: `System.IO.stderr'
    No module named `System.IO' is imported.

<interactive>:1:220: error:
    Not in scope: data constructor `System.IO.NoBuffering'
    No module named `System.IO' is imported.
```

Do you have any ideas on how to fix this? Does installed GHC work correctly on your machine?

**Comment by snowleopard** [comment]
Oh, I think the Windows build is broken on my machine. Same errors occur if I run GHC from `inplace/lib`.

**Comment by snowleopard** [comment]
False alarm: after a clean rebuild by GHC binary works. Not sure what's going on with the installed version...

**Comment by izgzhen** [comment]
> can't decompose ghc.exe path: "C:\\msys\\home\\nam83\\test-install\\usr\\local\\lib\\bin\\ghc.exe"

I don't actually know about this error...but shouldn't it be `ghc-stage2.exe`?

> ```
> <interactive>:1:19: error:
> Not in scope: `System.IO.hSetBuffering'
> No module named `System.IO' is imported.
> ```

Normally this is caused by packages not registered properly. I sometimes will walk through the steps in  `installPackages` manually to verify this.

I will check out the code again and hopefully can provide some advice. Also, I think the best way to debug this is to compare with what the old system would produce, since I try to imitate it in the best way.

**Comment by izgzhen** [comment]
One spot that might matter: https://github.com/ghc/ghc/blob/master/ghc.mk#L923-L933

**Comment by snowleopard** [comment]
Hmm, on my machine I get `ghc.exe` after install, not `ghc-stage2.exe`. Do you think it matters?

**Comment by izgzhen** [comment]
> Do you think it matters?

It matter only in the error msg as in the link above, but probably not relevant to the malfunctioning of installed bin,  I think.

**Comment by snowleopard** [comment]
So, I made an experiment:
* Build GHC
* Run `inplace/bin/ghc-stage2.exe -e 1+2` -- works fine.
* Copy the binary to `..` and run `inplace/ghc-stage2.exe -e 1+2` -- fails with "Can't decompose..." error.

Is this expected? My guess is that something similar is happening during the installation rule on Windows.

**Comment by izgzhen** [comment]
> Is this expected? My guess is that something similar is happening during the installation rule on Windows.

I can't reproduce that on my machine (actually it is the first time I heard of "Can't decompose..."). I found this https://ghc.haskell.org/trac/ghc/ticket/11759 though.

**Comment by snowleopard** [comment]
@izgzhen Thanks! I found the following in the ticket which seems important:

> Systools makes some pretty hard assumptions about where GHC is on Windows.
One of these is that ghc be in a folder named `bin` and that `../lib` exists.

So I shouldn't run GHC from `test-install\usr\local\lib\bin`, but only from `test-install\usr\local\bin`.

This leaves us with this error:
```
<interactive>:1:19: error:
Not in scope: `System.IO.hSetBuffering'
No module named `System.IO' is imported.

[...]
```

**Comment by snowleopard** [comment]
If I look at `base-4.10.0.0.conf` I see:
```
import-dirs: $topdir\base-4.10.0.0
library-dirs: $topdir\base-4.10.0.0
dynamic-library-dirs: $topdir\base-4.10.0.0
data-dir: $topdir\x86_64-windows-ghc-8.3.20170710\base-4.10.0.0
hs-libraries: HSbase-4.10.0.0
extra-libraries:
    wsock32 user32 shell32 msvcrt mingw32 mingwex
include-dirs: $topdir\base-4.10.0.0\include
includes:
    HsBase.h
depends:
    rts ghc-prim-0.5.0.0 integer-simple-0.1.1.1
abi-depends: rts= ghc-prim-0.5.0.0=432f6e69ccfd0baf6b44fc3fc1815a8f
             integer-simple-0.1.1.1=ebf815d3f1fb252a93ceb02d7ad9531e
haddock-interfaces: $topdir/../doc/html/libraries/base-4.10.0.0\base.haddock
haddock-html: $topdir/../doc/html/libraries/base-4.10.0.0
```
It looks like these unresolved `$topdir` variables could be the issue.

**Comment by izgzhen** [comment]
This is my [base-4.10.0.0.conf](https://gist.github.com/izgzhen/000a8a929af8ac287f54b20deae6ecbf).

$topdir should be passed in from https://github.com/snowleopard/hadrian/blob/master/src/Rules/Install.hs#L243.

**Comment by snowleopard** [comment]
I found that Windows installation is always relocatable:

https://ghc.haskell.org/trac/ghc/wiki/Building/Installing#HowGHCfindsitsfiles

This probably means that `$topdir` is supposed to be there, as otherwise the installation won't be relocatable. So I think the problem is somewhere else.

**Comment by snowleopard** [comment]
If I run `install` using the Make build system and I get exactly the same error. Not sure what to do now.

By the way, the installation result is quite different. I attached what I get with Make and Hadrian.

@izgzhen I think I'm stuck here, we need someone who better understands the installation process and requirements on Windows.

[make.txt](https://github.com/snowleopard/hadrian/files/1177881/make.txt)
[hadrian.txt](https://github.com/snowleopard/hadrian/files/1177882/hadrian.txt)

**Comment by izgzhen** [comment]
> By the way, the installation result is quite different. I attached what I get with Make and Hadrian.

Comparing the make system's output in Window and OS X, I found several major differences:

1. Window's one has a `msys` thing, which contains all documentation files and library object files. On OS X and Linux, it is in the same tree as *others* (bin etc.)
2. Windows's bin directory has `ghc` etc., no symbolic, both versioned and non-versioned, while in `lib/bin` there is no `ghc.exe` etc, but only `ghc-iserv.exe` etc. On Linux, real binaries are all put inside `lib/bin`, and most of them will have a symlinked version in `bin`.

[hadrian-linux.txt](https://github.com/snowleopard/hadrian/files/1178540/hadrian-linux.txt)

**Comment by snowleopard** [comment]
Aha, Make install worked after I dropped the `DEST_DIR` parameter, so I guess I'm not supposed to mess with this settings on Windows...

I rerun Hadrian install with `defaultDestDir = ""` and got a very strange error:
```
Error when running Shake build system:
* install
* OracleQ (DirectoryContents (And [],"/usr/local/lib/bin"))
/usr/local/lib/bin: getDirectoryContents: does not exist (The system cannot find the path specified.)
```

Note that the folder does exist and is non-empty:
```
$ ls /usr/local/lib/bin
ghc.exe  ghc-iserv.exe  ghc-pkg.exe  ghc-split  hp2ps.exe  hpc.exe  hsc2hs.exe  runhaskell.exe  touchy.exe  unlit.exe
```

**Comment by snowleopard** [comment]
We no longer have `install` rule, so I guess this issue can be closed.
