### ISSUE TITLE
Setup a status site

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#348]
While the per-commit CI is necessary to show that this project works, it is not sufficient to persuade people to switch over. I think we need a site that tracks the *status* of our project, aiming at

1. Showcase the capability of Hadrian
2. Help us better track of breaking changes
3. Attracting more people to use and contribute to this project

I think it should have the following features:

1. Comparison of implemented features between Hadrian and Make-build
2. Nightly build + test of implemented features (like `install`, `Stage1Only`, and different flavors ...), tracking the failure rate (of `validate` etc), and length of build
3. Roadmap

I can help set up the first version of it on my AWS Linux instance. Comments and ideas are welcomed.

**Comment by izgzhen** [comment]
I set up a t2-medium instance on AWS EC2, and the source is in https://github.com/izgzhen/hadrian-www (under development)

**Comment by snowleopard** [comment]
Great idea, we definitely need this. 

P.S.: I'm travelling all day today, so my responses will be slow. But I'm finally getting back home after a month-long trip, so should get some time for hacking!

**Comment by izgzhen** [comment]
@snowleopard Can you add a CRON job in the Travis CI config page (also maybe other CIs if there is such a thing)? So I can save up my own machine's time by focusing on building other (longer) flavors.

**Comment by snowleopard** [comment]
@izgzhen This has already been done as part of #306 for both Travis and AppVeyor. Couldn't find this on CircleCI though.

**Comment by izgzhen** [comment]
The site is stabilized. I'll close the issue for now.

**Comment by snowleopard** [comment]
@izgzhen Could you clarify what `default` and `validate` actually mean? I remember you planned to test the `install` rule too -- is it part of `default`? Can we also test profiled GHC? I think there are a few useful combinations to be tested, and perhaps we should arrange this in a matrix form, e.g. something like this:

https://matrix.hackage.haskell.org/package/shake

Maybe this should be raised as an issue in the `hadrians-wall` repo.

**Comment by izgzhen** [comment]
> I remember you planned to test the install rule too -- is it part of default? 

Yes, I've added `install` to `default` in the newest commit. It will be executed in the next run.

>  perhaps we should arrange this in a matrix form, e.g. something like this:

Since each run can take one hour or longer, I can't afford more than 3 to 4 times builds per day. So a large matrix like this is not very realistic for now. However, I'll open an issue about profiled GHC and add it in some way.

**Comment by snowleopard** [comment]
@izgzhen I see, thank you!
