### ISSUE TITLE
Why "Hadrian"?

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#354]
Out of pure curiosity, I wonder why it is called "Hadrian", and what is the motivation of changing from "Shaking-Up-GHC" to this one.

**Comment by snowleopard** [comment]
Hadrian (https://en.wikipedia.org/wiki/Hadrian) participated in a lot of large-scale construction projects, such as Pantheon in Rome and Hadrian's Wall in the UK. The latter starts in Newcastle, where I live, hence the name :-)

**Comment by snowleopard** [comment]
(And "Shaking-up-GHC" was a bit awkward as a project name, Hadrian is shorter and easier to use.)

**Comment by izgzhen** [comment]
Thanks for the explanation and it is fantastic :) So now it would be easier to answer when people ask me why that project is named that way. I'll close it for now.

**Comment by izgzhen** [comment]
Realizing that my comprehensive nightly CI might be a nontrivial endeavor, I am thinking about renaming it to Hadrian's Wall ;)

**Comment by snowleopard** [comment]
Sounds great :-) Let's build this wall out of shiny green bricks!
