### ISSUE TITLE
Should "build test" need depended binaries explicitly?

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#358]
This is a failed log of running `./build.sh test` directly without `./build.sh` beforehand: http://hadrian-status-dev.zhenzhang.me:3000/logs/2017-07-10T14%3A45%3A36.503688%25test%2595.1411631107%25failure.err.log.

My guess is that `test` target doesn't `need` things like `haddock` and alike. Is it true? Should we let `test` track them as well?

**Comment by snowleopard** [comment]
I'm confused by the log -- I don't see any build failure.

However, I agree that the `test` target should `need` all required executables. One shouldn't need to run `build` beforehand, so this is a bug.

**Comment by izgzhen** [comment]
> hadrian: Haddock is never built by Hadrian.

This last line is the indication of failure, as I find.

**Comment by snowleopard** [comment]
> hadrian: Haddock is never built by Hadrian.

Ah, I missed it. 

This actually looks like a bug in the `programPath` function. I think if we tried to use a builder which wasn't yet built, Hadrian would do the right thing -- build it first.

**Comment by snowleopard** [comment]
By the way, I fixed all compilation warnings in the above commit, so they don't confuse me again.

**Comment by izgzhen** [comment]
It looks like:

1. I can `need [ compiler, ghcPkg ]`
2. If I `need [ haddock ]`, then same error: "hadrian: Haddock is never built by Hadrian.". I searched a bit and it is because I didn't pass "--haddock" argument to `build`, so haddock is not part of stage2packages, so even `need` it directly will cause error:

```
./build.stack.sh --flavour=quickest --integer-simple -j inplace/bin/haddock
shakeArgsWith   0.002s    0%                           
Function shake  0.414s   38%  =====================    
Database read   0.472s   43%  =========================
With database   0.033s    3%  =                        
Running rules   0.161s   14%  ========                 
Total           1.082s  100%                           
Error when running Shake build system:
* inplace/bin/haddock
Maybe.fromJust: Nothing
```

Now I made a small workaround: deleting the line https://github.com/snowleopard/hadrian/blob/master/src/Rules/Test.hs#L62 directly (in future, we should use `--haddock` to switch on/off this argument to python driver). It works for some time, but error again:

```
| Make 'inplace/bin/ghc-stage2' executable.
| Successfully created wrapper for 'ghc-bin' (Stage1).
Traceback (most recent call last):
  File "testsuite/driver/runtests.py", line 63, in <module>
    exec(open(arg).read())
  File "<string>", line 56, in <module>
AttributeError: TestConfig instance has no attribute 'ghc_dynamic_by_default'
shakeArgsWith    0.003s    0%                           
Function shake   0.451s    0%                           
Database read    0.015s    0%                           
With database    0.001s    0%                           
Running rules  882.629s   99%  =========================
Total          883.097s  100%                           
Error when running Shake build system:
* test
user error (Development.Shake.cmd, system command failed
Command: python2 testsuite/driver/runtests.py --rootdir=libraries/binary/tests --rootdir=libraries/Cabal/Cabal/tests --rootdir=libraries/hpc/tests --rootdir=libraries/template-haskell/tests --rootdir=libraries/array/tests --rootdir=libraries/base/tests --rootdir=libraries/bytestring/tests --rootdir=libraries/containers/tests --rootdir=libraries/deepseq/tests --rootdir=libraries/directory/tests --rootdir=libraries/filepath/tests --rootdir=libraries/ghc-compact/tests --rootdir=libraries/ghc-prim/tests --rootdir=libraries/haskeline/tests --rootdir=libraries/pretty/tests --rootdir=libraries/process/tests --rootdir=libraries/unix/tests -e windows=False -e config.speed=2 -e 'ghc_compiler_always_flags="-fforce-recomp -dcore-lint -dcmm-lint -dno-debug-output -no-user-package-db -rtsopts"' -e ghc_with_native_codegen=1 -e 'ghc_debugged="NO"' -e ghc_with_vanilla=1 -e ghc_with_dynamic=0 -e ghc_with_profiling=0 -e ghc_with_interpreter=1 -e ghc_unregisterised=0 -e ghc_with_threaded_rts=0 -e ghc_with_dynamic_rts=0 -e ghc_dynamic_by_default=False -e ghc_dynamic=0 -e ghc_with_llvm=0 -e in_tree_compiler=True -e clean_only=False --configfile=testsuite/config/ghc --config 'compiler="/Users/zz/Repos/ghc2/inplace/bin/ghc-stage2"' --config 'ghc_pkg="/Users/zz/Repos/ghc2/inplace/bin/ghc-pkg"' --summary-file testsuite_summary.txt --threads=4
Exit code: 1
Stderr:
Traceback (most recent call last):
  File "testsuite/driver/runtests.py", line 63, in <module>
    exec(open(arg).read())
  File "<string>", line 56, in <module>
AttributeError: TestConfig instance has no attribute 'ghc_dynamic_by_default'
)
```

**Comment by izgzhen** [comment]
I think the upstream has updated the python driver code. I will take a look at it later

**Comment by izgzhen** [comment]
(Ugh, again it is proven that we do need a comprehensive CI!)

**Comment by bgamari** [comment]
Zhen Zhang <notifications@github.com> writes:

> (Ugh, again it is proven that we do need a comprehensive CI!)
>
For the record, I am currently working on moving GHC's CI to Jenkins. I
could start introducing Hadrian support while I am at it if this would
be helpful.

**Comment by ndmitchell** [comment]
For info, generally flags like `--haddock` should cause `want` statements to appear/disappear and nothing more - that way `need` always works.

**Comment by snowleopard** [comment]
I agree with @ndmitchell, and I think we're actually doing more than simply disabling the corresponding `want`. I think we also remove Haddock from the list of 'active' packages, which probably prevents it from being discovered as an existing builder.

**Comment by izgzhen** [comment]
> For the record, I am currently working on moving GHC's CI to Jenkins.

Oh right, I should probably use Jenkins instead of inventing my own wheels

**Comment by snowleopard** [comment]
We no longer have the `--haddock` flag, so Haddock can always be built. I think this can be closed.
