### ISSUE TITLE
build validate on Linux failed in lack of `test   spaces/hsc2hs`

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#366]
```
Cannot find hsc2hs: /tmp/tmpRClrGx/ghc/inplace/test   spaces/hsc2hs.  Stop.
```

stderr log: http://hadrian-status-dev.zhenzhang.me:3000/logs/2017-07-16T12%3A04%3A49.765572%25validate%252139.31077409%25failure.err.log

The weird thing is that the validation works fine on my Mac.

**Comment by snowleopard** [comment]
So, presumably this has something to do with paths containing spaces. One possible test is install GHC into a directory whose name contains spaces. I'll try to do on Windows, as part of #345.

**Comment by izgzhen** [comment]
this is fixed I think
