### ISSUE TITLE
Meta-issue on using GitHub's Project feature

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#368]
As you might notice, I created two "project"s, [GHC Merge](https://github.com/snowleopard/hadrian/projects/1) and [GHC Transcendence](https://github.com/snowleopard/hadrian/projects/2), and added something into it. I think it will be useful to help us track how far we might be from different milestones, since relevant issues & PRs & notes can be put together.

This issue will be used to discuss how we can utilize that well. BTW, to collaborators, you may add whatever that is in your mind to the proper place when available :)

**Comment by snowleopard** [comment]
Thanks, that's very useful, especially for people who'd like to contribute! It may be quite hard to keep these project pages up-to-date though.

**Comment by snowleopard** [comment]
Aha, I haven't realised that one can actually assign a particular issue to a project, just like adding a label. I'll try to remember doing that.

**Comment by izgzhen** [comment]
> Aha, I haven't realised that one can actually assign a particular issue to a project, just like adding a label

Yes, the thing quite cool is that the issue is put into "waiting for triage" state, and we can clean things up a bit sometime later in batch.

**Comment by snowleopard** [comment]
Great, I've added a link to the projects webpage to the README:

https://github.com/snowleopard/hadrian/commit/4bdc4a4747801dba02d755ce08d356d81ede18a3

**Comment by izgzhen** [comment]
I'll close this since that feature is already in use
