### ISSUE TITLE
install with --haddock on complains that _build/stage1/rts/libCffi_thr.a doesn't exist

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#374]
First `build --haddock`, then `build install`, it will result in the following error msg:

```
Error when running Shake build system:
* _build/stage1/rts/libCffi_thr.a
Error, file does not exist and no rule available:
  _build/stage1/rts/libCffi_thr.a
```

**Comment by izgzhen** [comment]
The `_build/stage1/rts` folder in Hadrian after `build --haddock`:

```
c                  ffitarget.h        libHSrts.a
cmm                inplace-pkg-config libHSrts_thr.a
ffi.h              libCffi.a          package-data.mk
```

In Make-based system after `make HADDOCK_DOCS=YES` (part of):

```
...
libCffi.a
libCffi_debug.a
libCffi_l.a
libCffi_thr.a
libCffi_thr_debug.a
libCffi_thr_l.a
libHSrts-ghc8.3.20170703.dylib
libHSrts.a
libHSrts_debug-ghc8.3.20170703.dylib
libHSrts_debug.a
libHSrts_l-ghc8.3.20170703.dylib
libHSrts_l.a
libHSrts_thr-ghc8.3.20170703.dylib
libHSrts_thr.a
libHSrts_thr_debug-ghc8.3.20170703.dylib
libHSrts_thr_debug.a
libHSrts_thr_l-ghc8.3.20170703.dylib
libHSrts_thr_l.a
libffi.dylib
linker
posix
sm
```

**Comment by snowleopard** [comment]
Yes, I've seen this failure. Thanks for documenting it!

**Comment by izgzhen** [comment]
My latest build suggests that it working fine. I will close it for now.

**Comment by izgzhen** [comment]
regression...

**Comment by izgzhen** [comment]
relavant: https://github.com/snowleopard/hadrian/blob/master/src/Rules/Install.hs#L166-L168

**Comment by izgzhen** [comment]
Latest test shown that the bug is missing again ... I've added `--haddock` to the test target in http://hadrian-status-dev.zhenzhang.me now to track the regression ...

**Comment by snowleopard** [comment]
@izgzhen Note that this may be non-deterministic if there is some missing dependency, i.e. it breaks only sometimes, depending on which build scheduling order.
