### ISSUE TITLE
Eliminate explicit filepaths in "need"

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#376]
For example,  `need ["inplace/bin/hp2ps"]` is not maintainable.

I am willing to mentor if anyone would like to contribute.

**Comment by joehillen** [comment]
I've been interested in hadrian for a while and I thought I'd start with some easy issues, but I just replaced the line with `needBuilder Hsc2Hs` like the TODO suggests and it seems to work fine. 

Do you remember what the problem was before?

**Comment by snowleopard** [comment]
@joehillen Thanks for helping!

This change was done in #378. I believe `needBuilder Hsc2Hs` worked for me and on all CI bots too, but for some reason it was failing on @izgzhen's machine.

@izgzhen Could you check if `needBuilder Hsc2Hs` still doesn't work for you?

**Comment by izgzhen** [comment]
Looks like `needBuilder Hsc2Hs` is fine with me (but filed another issue during that process #449 (O_o))

**Comment by snowleopard** [comment]
@izgzhen So, as I understand we should bring `needBuilder Hsc2Hs` back.

By the way, Hadrian is back to the all-green status.

@joehillen Let us know if you have any other questions.

**Comment by snowleopard** [comment]
@joehillen Yes, please do open a PR!

Let me clarify the purpose of this issue:
* Find all relevant `need`'s in the code. I'm not sure that the `grep` above catches all cases, as we might have something like `need [x, "y", z]` or `need [x -/- "y"]`. Ideally, all `need`s should be looked at.
* Analyse all suspicious `need`s. Each can be either fixed or left as is: there will be pros and cons in each case, so the process is not entirely mechanical. For example, `need ["configure.ac"]` is probably fine as is and introducing an extra abstraction (e.g. `configureAc = "configure.ac"`) may just make the code harder to read without any real win.
