### ISSUE TITLE
Use command line flags to control verbose commands and DESTDIR

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#377]
- https://github.com/snowleopard/hadrian/blob/master/doc/user-settings.md#verbose-command-lines
- https://github.com/snowleopard/hadrian/blob/master/src/Settings.hs#L129

We need to be able to:

```
DESTDIR=... ./build.sh # or
./build.sh --dest-dir=...
```

and

```
VERBOSITY=... ./build.sh # or
./build.sh --verbosity=...
```

**Comment by snowleopard** [comment]
Why environment variables and not command line flags? We have a good infrastructure for adding new flags, and adding `--dest-dir` or `--verbose` shouldn't be difficult.

By the way, regarding the verbosity setting: I think could just jump on Shake's `Verbosity`:

https://hackage.haskell.org/package/shake-0.15.11/docs/Development-Shake.html#t:Verbosity

**Comment by izgzhen** [comment]
> Why environment variables and not command line flags?

I was thinking about `make` system, where they are passed in as env. But cmd line args look handy enough to use as well.

> I think could just jump on Shake's Verbosity:

Do you mean that we can pass in this verbose level directly?

**Comment by snowleopard** [comment]
> Do you mean that we can pass in this verbose level directly?

I think the answer is Yes. Shake already has support for verbosity, for example, here is what `build --help` shows (among other things):
```
-V, --verbose, --trace      Print tracing information.
```
This setting, I believe, is available as `getVerbosity`.

By the way, the following two settings are also supported by Hadrian:
```
  --progress-colour[=MODE]    Use colours in progress info (Never, Auto or Always).
  --progress-info[=STYLE]     Progress info style (None, Brief, Normal or Unicorn).
```

**Comment by izgzhen** [comment]
Done now.
