### ISSUE TITLE
Rethink hadrian/cfg

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#381]

**Comment by snowleopard** [comment]
I think it was a mistake for me to commit it so prematurely, so we can drop it for now.

Here is a relevant TODO: https://github.com/snowleopard/hadrian/blob/master/src/Rules/Generators/GhcAutoconfH.hs#L9-L11

At the moment we are using the file from the Make build system `mk/config.h`, which is generated by Autoconf, but we should change this at some point and generate a file in `hadrian/cfg` instead.

We might also want to move generated files from `hadrian/cfg` to `_build/hadrian`.

**Comment by snowleopard** [comment]
A link to @izgzhen's attempt to generate `hadrian/cfg/config.h.in`: https://phabricator.haskell.org/D3869.
