### ISSUE TITLE
sdist-ghc builds more than necessary

### ISSUE THREAD

**Issue by bgamari** [snowleopard/hadrian#383]
In the `make`-based build system `make sdist` finishes in around two minutes on my machine, with most of the time being spent compressing the final source tarball. Afterall, all it does is copy the source files into `sdistprep`.

However, Hadrian seems to want to build a stage1 compiler as well.

**Comment by snowleopard** [comment]
I've just tried this on Windows.

The `sdist-ghc` rule runs the `boot` and `configure` scripts and than copies the file, painfully reporting about each one on the screen. Then it does the archiving.

I don't think it builds stage1 compiler or anything else, the only problem is excessive amount of output information. This should be easy to fix.

**Comment by snowleopard** [comment]
With `--progress-info=none` the rule runs slightly faster (5:08m compared to 6:41m), but it's still rather slow.

Could the reason be file-by-file copying?

https://github.com/snowleopard/hadrian/blob/master/src/Util.hs#L144-L150

**Comment by bgamari** [comment]
> I don't think it builds stage1 compiler or anything else, the only problem is excessive amount of output information. This should be easy to fix.

Hmm, that isn't what I observed but perhaps I'm doing something wrong. I definitely saw it build some compiler objects.

> With --progress-info=none the rule runs slightly faster (5:08m compared to 6:41m), but it's still rather slow.
Indeed I also had noticed that the copying itself was quite slow. At one point I eyeballed the copy rate at something like 30 files per second, which is significantly slower than I would expect. I'll try to look into why this may be.

**Comment by bgamari** [comment]
So one thing that I've noticed is that Hadrian is remarkably rough on the GC. Productivity with `-j4` typically hovers slightly lower than 50%. I suspect most of this time is spent trying to synchronize with threads in foreign calls.

**Comment by bgamari** [comment]
It sounds like this may be due to #384. Indeed I was unable to reproduce this with a clean tree.
