### ISSUE TITLE
build error: rts/libHSrts_thr.a matches multiple rules

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#391]
```
ar: creating archive _build/stage1/libraries/Cabal/Cabal/libHSCabal-2.0.0.2.a
/-------------------------------------------------------------------\
| Successfully built library 'Cabal' (Stage1, way v).               |
| Library: _build/stage1/libraries/Cabal/Cabal/libHSCabal-2.0.0.2.a |
| Library synopsis: A framework for packaging Haskell software.     |
\-------------------------------------------------------------------/
/----------------------------------------------------------------------------------------\
| Run Ld (stage = Stage1, package = Cabal)                                               |
|      input: _build/stage1/libraries/Cabal/Cabal/Distribution/Backpack.o (and 167 more) |
|  => output: _build/stage1/libraries/Cabal/Cabal/HSCabal-2.0.0.2.o                      |
\----------------------------------------------------------------------------------------/
shakeArgsWith     0.001s    0%                           
Function shake    0.231s    0%                           
Database read     0.001s    0%                           
With database     0.000s    0%                           
Running rules  2408.858s   99%  =========================
Total          2409.090s  100%                           
Error when running Shake build system:
* inplace/bin/ghc-cabal
* _build/stage1/rts/libHSrts_thr.a
Build system error - key matches multiple rules:
  Key type:       FileQ
  Key value:      _build/stage1/rts/libHSrts_thr.a
  Rules matched:  2
Modify your rules/defaultRules so only one can produce the above key
```

**Comment by snowleopard** [comment]
Oh, this is my fault. Strange this didn't show up in my testing, I'm pretty sure it's not `OSX` specific.

**Comment by snowleopard** [comment]
@izgzhen Can you check if adding the following priorty fixes this on your system?

```haskell
priority (fromIntegral . length $ waySuffix way) $
```
You need to add it to this build rule:

https://github.com/snowleopard/hadrian/blob/master/src/Rules/Library.hs#L56

If it works, I'll push a patch tonight, after trying to figure out something more clever.

**Comment by izgzhen** [comment]
```diff
--- a/src/Rules/Library.hs
+++ b/src/Rules/Library.hs
@@ -53,7 +53,7 @@ buildDynamicLib context@Context{..} = do
 buildPackageLibrary :: Context -> Rules ()
 buildPackageLibrary context@Context {..} = do
     let libPrefix = "//" ++ contextDir context -/- "libHS" ++ pkgNameString package
-    libPrefix ++ "*" ++ (waySuffix way <.> "a") %> \a -> do
+    priority (fromIntegral . length $ waySuffix way) $ libPrefix ++ "*" ++ (waySuffix way <.> "a") %> \a -> do
         objs <- libraryObjects context
         asuf <- libsuf way
         let isLib0 = ("//*-0" ++ asuf) ?== a
```

After this, I simply build and got:

```
Error when running Shake build system:
* _build/stage1/libraries/hpc/libHShpc-0.6.0.3.a
Build system error - key matches multiple rules:
  Key type:       FileQ
  Key value:      _build/stage1/libraries/hpc/libHShpc-0.6.0.3.a
  Rules matched:  1
Modify your rules/defaultRules so only one can produce the above key
```

**Comment by snowleopard** [comment]
Wat. `Build system error - key matches multiple rules:` and `Rules matched:  1` doesn't seem to make much sense :)

@ndmitchell Do you know what this error means?

**Comment by snowleopard** [comment]
Ah, I think I know what's going on. The priority will be 0 for the vanilla way, which messes up the Shake's error report :-) We need to add `+1` to all priorities to solve this.

Just another off-by-one error :-)

**Comment by izgzhen** [comment]
> Just another off-by-one error :-)

Looks like your are right on this point :)

**Comment by izgzhen** [comment]
But why does that happen? Different way appends a different suffix to the built object, so the rules should be exclusive. In what case will `libHSrts_thr.a` will be matched twice?

**Comment by snowleopard** [comment]
@izgzhen The problem is that `libHSrts_thr.a` matches both `//*.a` and `//*_thr.a` patterns. This is even worse for more complicated ways, e.g. `libHSrts_thr_p_dyn.a` which I believe has 4 matches.

We can use priorities to tell Shake to prefer longer matches.

**Comment by izgzhen** [comment]
Cool, thanks!

**Comment by snowleopard** [comment]
@izgzhen The above should fix this. Please let me know if it works for you.

**Comment by ndmitchell** [comment]
It seems like you've figured this one out. I've added a test to Shake that the number of rules reported is accurate, so in the next version you won't have a problem (I didn't find the old bug, as that code has changed totally).

**Comment by snowleopard** [comment]
@ndmitchell Yes, it seems to work now. Do you think this is an appropriate use case for priorities? 

By the way, will any attempt to use `priority 0.0` lead to the `key matches multiple rules` error like above? It may be worth to report a custom error in this case.

**Comment by ndmitchell** [comment]
In shake-0.15, yes, any use of priority 0 will raise a multiple match error, as implicitly there is a rule at priority 0 that say "it's just a source file". In shake-HEAD, it doesn't work that way at all, so the problem is gone. This doesn't seem a terrible use of priorities - you have two patterns, you know one is strictly more specific than the other, so you use priorities to switch between.

**Comment by snowleopard** [comment]
@ndmitchell I see, thanks!

**Comment by izgzhen** [comment]
looks like this has been resolved?

**Comment by snowleopard** [comment]
@izgzhen Yes, seems to work on my machine. If it works for you too, please close the issue.

**Comment by izgzhen** [comment]
It works for me now
