### ISSUE TITLE
Travis Linux CI with GHC 8.0.2 timeouts frequently

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#393]
All recent commits caused the GHC 8.0.2 version of Travis Linux CI to timeout.

Since we have GHC 8.2.1 and it has been around for a while, I am considering to either drop Travis Linux GHC 8.0.2 entirely or make it only build stage1 like OS X on Travis.

**Comment by snowleopard** [comment]
@izgzhen Yes, good idea to switch to stage1 only. I've pushed a fix -- let's see if it works.

**Comment by izgzhen** [comment]
The fix https://github.com/snowleopard/hadrian/commit/7231dd5a3d512bbafbd65aa4ad70ecdf6a924243 is not very successful, since it uses `ghc-stage1 -e`. However, at the same time the 8.2.1 version CI also started to time out ...

I believe that we might need to improve the efficiency of Hadrian first.

**Comment by izgzhen** [comment]
But I also noticed more packages being added to GHC recently, so will that be relevant as well?

**Comment by snowleopard** [comment]
@izgzhen I pushed a fix removing `ghc-stage2` test on GHC 8.0.2, and removing `selftest` on GHC 8.2.1.

> But I also noticed more packages being added to GHC recently, so will that be relevant as well?

You mean modules? Yes, that may be the reason.

Also, the Cabal library got bigger -- it now includes Backpack, and we build it 4 (!) times, three times by the bootstrapping compiler, as mentioned in this ticket: #233. I'll see if I can quickly do anything about it.

**Comment by snowleopard** [comment]
> But I also noticed more packages being added to GHC recently, so will that be relevant as well?

Oh, I've just realised that indeed, there is a new package `parsec` and a couple of new packages are now built in Stage0. That will be problematic to handle using our CI infrastructure...

See this commit, in particular:

https://github.com/ghc/ghc/commit/36fe21aa3fe5abe1cef0104b20c296ac9385658d

We still haven't implemented this in Hadrian. I'll set up a new issue.

**Comment by snowleopard** [comment]
It seems that the above commits gradually fixed the timeout, so I am closing this.

@izgzhen You mentioned recently that Hadrian was slower than Make on your machine. Could you try to benchmark again please?

**Comment by izgzhen** [comment]
> @izgzhen You mentioned recently that Hadrian was slower than Make on your machine. Could you try to benchmark again please?

It is 23 min 21 s vs 22 min 48 s now, in which Hadrian is still a bit slower, but it is okay I think.

**Comment by snowleopard** [comment]
@izgzhen Thanks! Does this include `boot` + `configure` in case of Make?

**Comment by izgzhen** [comment]
> @izgzhen Thanks! Does this include boot + configure in case of Make?

No, it includes all the time spent after Hadrian is built.

**Comment by izgzhen** [comment]
....I mean, Make doesn't include that, while Hadrian does.

**Comment by snowleopard** [comment]
I see, thanks. We need to do a proper benchmarking at some point, which I think should include `boot` and `configure` on both sides.
