### ISSUE TITLE
Depend on ansi-terminal in Shake

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/hadrian#399]
I am considering adding an ansi-terminal dependency in Shake so I can have prettier console messages. Given Hadrian already has such a dependency I guess that's not going to cause you problems - but I thought I'd check.

**Comment by snowleopard** [comment]
@ndmitchell Yes, we already depend on `ansi-terminal`, so I don't see any issues with this.

However, if `ansi-terminal` is problematic on a certain platform, Hadrian can easily live without it. But we can't live without Shake! :-)

**Comment by ndmitchell** [comment]
If ansi-terminal ever becomes problematic I'll just remove it - not a big deal and won't be integrated tightly.
