### ISSUE TITLE
Simplify package build and installation lists

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/hadrian#403]
When reviewing #401, I started to think that the current approach to specifying which packages are built in which stages is overly complex. Here is a snippet from `Settings/Default.hs`:

```haskell
defaultPackages :: Packages
defaultPackages = mconcat [ stage0 ? stage0Packages
                          , stage1 ? stage1Packages
                          , stage2 ? stage2Packages ]

stage0Packages :: Packages
stage0Packages = do
    win <- expr windowsHost
    ios <- expr iosHost
    pure $ [ binary
           , cabal
           , checkApiAnnotations
           , compareSizes
           , compiler
           , deriveConstants
           , dllSplit
           , genapply
           , genprimopcode
           , ghc
           , ghcBoot
           , ghcBootTh
           , ghcCabal
           , ghci
           , ghcPkg
           , ghcTags
           , hsc2hs
           , hp2ps
           , hpc
           , mtl
           , parsec
           , templateHaskell
           , text
           , transformers
           , unlit                       ] ++
           [ terminfo | not win, not ios ] ++
           [ touchy   | win              ]
```

I propose to simplify this by going from expressions `Expr [Package]` to something simpler, e.g. just a function `Stage -> Action [Package]`. For example:

```haskell
defaultPackages :: Stage -> Action [Package]
defaultPackages Stage0 = do
    win <- windowsHost
    ios <- iosHost
    return $ [ binary
             , ... 
             , unlit                       ] ++
             [ terminfo | not win, not ios ] ++
             [ touchy   | win              ]
defaultPackages Stage1 = ...
```

This will also allow to move to package lists to `GHC.hs`, which is a more sensible place for such lists.

@izgzhen Are you OK with this? I can implement this quickly enough, so you could benefit from the simplification in your PR #401.

**Comment by snowleopard** [comment]
This will also help me with #347.

**Comment by izgzhen** [comment]
Looks good to me, thanks!

**Comment by snowleopard** [comment]
@izgzhen Thanks, I've pushed a commit. I think this is mostly done, but I might later do a minor refactoring which shouldn't affect #401.

**Comment by snowleopard** [comment]
By the way, to conditionally remove `terminfo` from the list of packages, I think this should change the definition of `stagePackages` in `Settings`:

https://github.com/snowleopard/hadrian/blob/master/src/Settings.hs#L30-L33

**Comment by snowleopard** [comment]
For the sake if keeping Hadrian codebase sane, I propose to restrict user packages so that they cannot be Hadrian builders and they cannot be installed.

Hadrian will still build any user package, be it a C or Haskell library or program.

**Comment by snowleopard** [comment]
Done.

I think it will also be possible to get rid of `latestBuildStage` and simplify related code by using the newly introduced `GHC.isInstallContext`.

**Comment by izgzhen** [comment]
> I think it will also be possible to get rid of latestBuildStage and simplify related code by using the newly introduced GHC.isInstallContext.

Looks cool. Do you mean getting rid of `latestBuildStage` in `Install.hs`?

**Comment by snowleopard** [comment]
@izgzhen I pushed a revision. It's not a huge simplification, but I think the semantics is a bit clearer now.

There is still one confusion left in the code with regards to the GHC binary.

1. During a normal build we 'install' GHC binaries (`ghc-stage1`, `ghc-stage2`, etc) into `inplace/bin`, which is reflected in the function `installStages` above.

2. However, during the installation build, we only install GHC of the latest build stage, hence the function `withLatestInstallStage` above.

I'd prefer to remove this confusion from the codebase. Perhaps, we shouldn't refer to (1) as installation? 

My proposal is:

* Switch from `installStages` + `withLatestInstallStage` to `installStage` + `withInstallStage`.
* Add `buildInplace :: Context -> Action Bool` function, which handles the question of whether a binary should be built in `buildRoot` or in `inplace` directory.

**Comment by izgzhen** [comment]
I support the separation of "install" and "inplace", but sometimes they share very similar logics, like building script wrappers, so that might take a bit of patience to get right.

**Comment by snowleopard** [comment]
Thanks! Indeed, wrappers are also related to this. I'll see if I manage to unravel this.

**Comment by snowleopard** [comment]
I think we can close this now.
