### ISSUE TITLE
libffi configure needs libffi_EnableShared flag

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#405]
see `libffi/ghc.mk`

**Comment by izgzhen** [comment]
`enable_static` is also missing

**Comment by izgzhen** [comment]
Oops ... found that, https://github.com/snowleopard/hadrian/blob/29046aa3b29a26e69db1bf38015f9376bfad2ff0/src/Settings/Builders/Configure.hs#L18-L25

But there is also a TODO anyway

**Comment by snowleopard** [comment]
This code is quite well-hidden, I think it's probably not the best location for it. If we follow the convention of how we deal with package-specific settings, this should be moved to `Settings/Packages/Libffi.hs`.

**Comment by izgzhen** [comment]
> This code is quite well-hidden, I think it's probably not the best location for it. If we follow the convention of how we deal with package-specific settings, this should be moved to Settings/Packages/Libffi.hs.

Agreed

**Comment by izgzhen** [comment]
The above issue is filled in https://github.com/snowleopard/hadrian/issues/411

**Comment by bgamari** [comment]
@angerman, you may also be interested in this.

**Comment by snowleopard** [comment]
I believe this has been fixed.
