### ISSUE TITLE
Implement commented part in Rts

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#406]
See https://github.com/snowleopard/hadrian/blob/29046aa3b29a26e69db1bf38015f9376bfad2ff0/src/Settings/Packages/Rts.hs#L127-L258

**Comment by snowleopard** [comment]
It's probably medium-to-high priority. I expect that these missing flags account for a lot of errors we see when we run `validate`.

**Comment by izgzhen** [comment]
I'll close this now
