### ISSUE TITLE
is PORTING_HOST still useful?

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#407]
It appeared in https://github.com/ghc/ghc/blob/c0feee90118333dac817cfad6f2dedc0a886d1bd/includes/ghc.mk#L85-L91

For the change above I made in #401, I basically don't include that header at all when cross compiling some packages:

https://github.com/izgzhen/hadrian/blob/e9a66ed59f99d4cf61326491ce8ceb1c383526d0/src/Settings/Builders/Common.hs#L31-L32

I think they are related -- and if `PORTING_HOST` is indeed useless, then maybe my hack in cross compilation might be the sole solution I can come up now to fix the type size unmatched problem (e.g. described in #349)

**Comment by bgamari** [comment]
I can say that I've never used this option.

**Comment by izgzhen** [comment]
> I can say that I've never used this option.

Okay, then I will close it for now
