### ISSUE TITLE
DYNAMIC_BY_DEFAULT on different platforms

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#408]
https://github.com/ghc/ghc/blob/c0feee90118333dac817cfad6f2dedc0a886d1bd/mk/config.mk.in#L132-L142

**Comment by snowleopard** [comment]
Not sure, but this may be part of #248?

**Comment by izgzhen** [comment]
> Not sure, but this may be part of #248?

Probably ... but they've disabled it explicitly in `mk/config.mk` now anyway, so it is low-priority.

**Comment by snowleopard** [comment]
I think we better close this one as a duplicate of #248.
