### ISSUE TITLE
Use different INSTALLED_GHC_REAL when cross compiling

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#409]
See https://github.com/ghc/ghc/blob/b2c2e3e818b8aa69af711cefa7efeadedc3f2e4e/ghc.mk#L976-L991

**Comment by snowleopard** [comment]
@izgzhen Can you confirm if this is still relevant?

**Comment by izgzhen** [comment]
it seems related to `inplace`, so I will close it for now. I need to check if cross-compilation works well later sometime.
