### ISSUE TITLE
./configure on OS X dumps weird output

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#415]
```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
ld: unknown option: --version
configure: line 8179: --version: command not found
configure: line 8297: --version: command not found
configure: line 9708: cygpath: command not found
configure: line 9708: ArCmd: command not found
configure: WARNING: Sphinx version 1.0.0 or later is required to build documentation
```

**Comment by snowleopard** [comment]
Presumably, this is not a Hadrian issue, but a bug in the GHC's configure script?

**Comment by izgzhen** [comment]
> Presumably, this is not a Hadrian issue, but a bug in the GHC's configure script?

Not sure, will investigate into it later

**Comment by bgamari** [comment]
It sounds like the machine that you are building on doesn't have a full XCode installation but rather only the command line tools package. I believe GHC requires the full thing.

**Comment by izgzhen** [comment]
> It sounds like the machine that you are building on doesn't have a full XCode installation but rather only the command line tools package. I believe GHC requires the full thing.

You are right. But what about the "command not found" etc. below the first line?

**Comment by bgamari** [comment]
Hmm, good question. I had missed the other errors. Something is definitely going quite awry here. You have run `./boot` recently, yes?

**Comment by izgzhen** [comment]
>  You have run ./boot recently, yes?

I think I should the answer should be "yes" -- It is not exactly `./configure`, but `Configure` run by Hadrian indirectly, so a `boot` will be fired up first each time as I remember

**Comment by snowleopard** [comment]
@bgamari Just to let you know: I also get the following messages from `configure` on Windows:
```
configure: line 8179: --version: command not found
configure: line 8297: --version: command not found
```
However, the rest of the build succeeds.

**Comment by bgamari** [comment]
Hmm, unfortunately debugging `autoconf` scripts is quite tricky. What is on line 8179 and 8297 of `configure`?

**Comment by snowleopard** [comment]
@bgamari I think these are offending lines:
```
        if test `$LLC --version | grep -c "version $LlvmVersion"` -gt 0 ; then
...
        if test `$OPT --version | grep -c "version $LlvmVersion"` -gt 0 ; then
```

**Comment by bgamari** [comment]
Ahh, yes, that sounds like it.

**Comment by bgamari** [comment]
I think it's fair to call this a bug. See https://phabricator.haskell.org/D3992.

**Comment by snowleopard** [comment]
@bgamari Thanks for the fix! Now I have no warnings from `configure`.

@izgzhen Has your issue been fixed too?

**Comment by izgzhen** [comment]
Now it is:

```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
ld: unknown option: --version
```

**Comment by izgzhen** [comment]
It looks like only `ld` complains about `--version` now for me

**Comment by angerman** [comment]
`ld` on macOS doesn't have `--version`. Not sure why we would try to call `--version` on it.
`ld` on macOS is `ld64`, and supports `ld -v` though.

**Comment by snowleopard** [comment]
I believe this has been fixed.
