### ISSUE TITLE
Regenerate .cabal.in files when changed

### ISSUE THREAD

**Issue by bgamari** [snowleopard/hadrian#416]
One of the annoyances that I have felt with the current Make-based build system is the inability for it to rebuild `ghc.cabal` when `ghc.cabal.in` is changed. Instead one must re-run `configure`, which results in all sort of spurious changes, generally requiring a full rebuild. Doing this every time a module is added, removed, or renamed gets quite tiresome. For this reason I generally just resort to updating `ghc.cabal` by hand.

I suspect it wouldn't be that hard to teach Hadrian to do the same sort of substitution that `autoconf` performs, eliminating the need for a full re-`configure`.

**Comment by snowleopard** [comment]
I looked at `ghc.cabal.in` and I can see only two variables that are substituted by `configure`: 
* @ProjectVersionMunged@
* `@FFIIncludeDir@`
Both values are known to Hadrian, so we can indeed do the substitution ourselves.

**Comment by snowleopard** [comment]
This seems to be a duplicate of #655.
