### ISSUE TITLE
Widows build broken (configure fails)

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/hadrian#420]
AppVeyor CI and my local builds are broken with the following `configure` error:
```
checking for gfind... no
checking for find... /usr/bin/find
checking for sort... /usr/bin/sort
checking for GHC version date... inferred 8.3.20170923
checking for GHC Git commit id... inferred d55961262be1b6bbacea0cd6864346f8822ee99b
checking for ghc... /c/Users/nam83/AppData/Local/Programs/stack/x86_64-windows/ghc-8.0.2/bin/ghc
checking version of ghc... 8.0.2
GHC path canonicalised to: c:/Users/nam83/AppData/Local/Programs/stack/x86_64-windows/ghc-8.0.2/bin/ghc
checking build system type... x86_64-pc-mingw64
checking host system type... x86_64-pc-mingw64
checking target system type... x86_64-pc-mingw64
Build platform inferred as: x86_64-unknown-mingw32
Host platform inferred as: x86_64-unknown-mingw32
Target platform inferred as: x86_64-unknown-mingw32
Unknown OS mingw64
```

This looks like a GHC bug, but I'll open a ticket here to investigate.

@bgamari Any ideas?

**Comment by snowleopard** [comment]
Could [this commit](https://github.com/ghc/ghc/commit/c2373b7b09939027742626e4a7bbba05ea1f6850) be related?

**Comment by angerman** [comment]
Indeed, it looks like `mingw64` is not a valid OS according to `GHC_CONVERT_OS`. I believe it should be?

**Comment by snowleopard** [comment]
@angerman Not sure what `GHC_CONVERT_OS` does, but presumably right now all 64-bit Windows machines are broken.

**Comment by angerman** [comment]
https://phabricator.haskell.org/D4016

**Comment by snowleopard** [comment]
@angerman Thanks for the fix! The Windows build is fixed now.
