### ISSUE TITLE
TH annotations test failed due to failure of capturing the standard output

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#423]
I was debugging the failure validation test `annotations/should_compile/th`, the `annth_make` target. 

If you execute the command under your shell, using Hadrian-built artifacts, by `make -s annth_make`, you will **see** the content of `annth_make.stdout` in your **terminal**. However, I can't redirect the output to file, by either using `>` or `2>`. It should be related to stdout, since using `>` will silent the output from terminal, but still you get no output in the redirected file.

It doesn't occur in a Make-based system.

The essence is whether `ghc-stage2 [....] annth.hs`'s output can be properly captured as stdout.

By `strace -f`, I can spot the difference between Make-built ghc-stage2 and Hadrian-built one:

Hadrian's:

```
poll([{fd=1, events=POLLOUT}], 1, 0)    = 1 ([{fd=1, revents=POLLOUT}])
write(1, "[\"TH module annotation\",\"addTopD"..., 77) = 77
poll([{fd=1, events=POLLOUT}], 1, 0)    = 1 ([{fd=1, revents=POLLOUT}])
write(1, "[\"Value annotation\"]\n", 21) = 21
poll([{fd=1, events=POLLOUT}], 1, 0)    = 1 ([{fd=1, revents=POLLOUT}])
write(1, "[\"TH Value annotation\",\"addTopDe"..., 55) = 55
poll([{fd=1, events=POLLOUT}], 1, 0)    = 1 ([{fd=1, revents=POLLOUT}])
write(1, "[\"Type annotation X\"]\n", 22) = 22
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=0, ptr=0}} ---
rt_sigreturn({mask=[]})                 = 73451681
poll([{fd=1, events=POLLOUT}], 1, 0)    = 1 ([{fd=1, revents=POLLOUT}])
write(1, "[\"TH Type annotation\",\"addTopDec"..., 53) = 53
poll([{fd=1, events=POLLOUT}], 1, 0)    = 1 ([{fd=1, revents=POLLOUT}])
write(1, "[\"Constructor annotation\"]\n", 27) = 27
poll([{fd=1, events=POLLOUT}], 1, 0)    = 1 ([{fd=1, revents=POLLOUT}])
write(1, "[\"TH Constructor annotation\",\"ad"..., 67) = 67
```

Make's

```
[pid 75809] write(1, "[\"TH module annotation\",\"addTopD"..., 77 <unfinished ...>
[pid 75813] futex(0x1608d30, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 75809] <... write resumed> )       = 77
[pid 75813] <... futex resumed> )       = 0
[pid 75813] futex(0x1608d04, FUTEX_WAIT_PRIVATE, 87, NULL <unfinished ...>
[pid 75809] poll([{fd=1, events=POLLOUT}], 1, 0) = 1 ([{fd=1, revents=POLLOUT}])
[pid 75809] futex(0x1608d04, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x1608d00, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
[pid 75813] <... futex resumed> )       = 0
[pid 75809] write(1, "[\"Value annotation\"]\n", 21 <unfinished ...>
[pid 75813] futex(0x1608d30, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 75809] <... write resumed> )       = 21
[pid 75813] <... futex resumed> )       = 0
[pid 75813] futex(0x1608d04, FUTEX_WAIT_PRIVATE, 89, NULL <unfinished ...>
[pid 75809] poll([{fd=1, events=POLLOUT}], 1, 0) = 1 ([{fd=1, revents=POLLOUT}])
[pid 75809] futex(0x1608d04, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x1608d00, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
[pid 75813] <... futex resumed> )       = 0
[pid 75809] write(1, "[\"TH Value annotation\",\"addTopDe"..., 55 <unfinished ...>
[pid 75813] futex(0x1608d30, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 75809] <... write resumed> )       = 55
[pid 75813] <... futex resumed> )       = 0
[pid 75813] futex(0x1608d04, FUTEX_WAIT_PRIVATE, 91, NULL <unfinished ...>
[pid 75809] poll([{fd=1, events=POLLOUT}], 1, 0) = 1 ([{fd=1, revents=POLLOUT}])
[pid 75809] futex(0x1608d04, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x1608d00, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
[pid 75813] <... futex resumed> )       = 0
[pid 75809] write(1, "[\"Type annotation\"]\n", 20 <unfinished ...>
```

The make-based `ghc-stage2` runs the `write` in a subprocess, and will call `futex` in between. I am not yet a experience UNIX hacker, so not knowing why that would cause the uncapturable output problem.

BTW, I wonder if this is the same in non-UNIX platform, like Window?

**Comment by snowleopard** [comment]
> However, I can't redirect the output to file, by either using `>` or `2>`

I don't understand. Are you running GHC from within Hadrian? If yes, you can extract `stdout` as follows:

https://github.com/snowleopard/hadrian/blob/master/src/Builder.hs#L195-L196

@izgzhen Does this help?

**Comment by izgzhen** [comment]
> I don't understand. Are you running GHC from within Hadrian?

No exactly. Inside `build validate`, we are still running Python scripts right? And despite the driver program, I can't capture the output from the just invoking `ghc-stage2` by hand, even if I can clearly *see* it on screen

**Comment by snowleopard** [comment]
> Inside `build validate`, we are still running Python scripts right?

No. `build validate` simply does `make fast` in the GHC testsuite. The python script is run directly only in `build test` target. See https://github.com/snowleopard/hadrian#testing.

**Comment by snowleopard** [comment]
> `build validate` simply does `make fast` in the GHC testsuite.

Just to clarify: the GHC testsuite will call the python script itself, so it still being called, but not by Hadrian.
