### ISSUE TITLE
"Rules may not be recursive" error

### ISSUE THREAD

**Issue by bgamari** [snowleopard/hadrian#425]
While attempting to build GHC e515c7f37be97e1c2ccc497ddd0a730e63ddfa82 with Hadrian c6d7b2a33e6ff987e7112c57555425c285c380e9 I encountered the following error,
```
$ hadrian/build.cabal.sh -j
Up to date
/-------------------------------------------------------\
| Run Configure "." (stage = Stage0, package = ghc)     |
|      input: hadrian/cfg/system.config.in (and 2 more) |
|  => output: hadrian/cfg/system.config (and 2 more)    |
\-------------------------------------------------------/
shakeArgsWith   0.000s    0%                           
Function shake  0.319s   65%  =========================
Database read   0.001s    0%                           
With database   0.000s    0%                           
Running rules   0.168s   34%  =============            
Total           0.488s  100%                           
Error when running Shake build system:
* OracleQ (ConfigKey "host-os")
* hadrian/cfg/system.config
* hadrian/cfg/system.config settings mk/config.h
* OracleQ (ConfigKey "host-os")
Build system error - recursion detected:
  Key type:   OracleQ ConfigKey
  Key value:  OracleQ (ConfigKey "host-os")
Rules may not be recursive


```

**Comment by snowleopard** [comment]
@bgamari Oh. I'll try to reproduce and fix asap.

**Comment by snowleopard** [comment]
@bgamari I couldn't reproduce the "Rules may not be recursive" error. Can you try if Hadrian 88a7b4e31616f06ea9c0f75d3565ae11936009e0 has the same problem?

By the way, it looks like the build is broken by recent `libffi` changes. I'll raise another issue.

**Comment by snowleopard** [comment]
@bgamari After fixing the `libffi` issue I still can't reproduce this. Is the build still broken for you?

**Comment by bgamari** [comment]
Indeed I still encounter this with ghc/ghc@429fafb5b2b1ac02fd04d9a98e30b5991125692c and Hadrian ca6ab27204bedc59716040da849a47ef64fcafa9.

**Comment by snowleopard** [comment]
@bgamari That's puzzling.

Do you happen to have a custom `UserSettings.hs` file?

I know what can cause this: trying to compute a setting like `windowsHost` before the `configure` script had a chance to run and collect the information about the system. But as far as I can see, in such situations (when `configure` output is not yet available), we are using `System.Info.os` to determine the OS.

**Comment by bgamari** [comment]
Andrey Mokhov <notifications@github.com> writes:

> @bgamari That's puzzling.
>
> Do you happen to have a custom `UserSettings.hs` file?
>
Unfortunately I do not.

> I know what can cause this: trying to compute a setting like
> `windowsHost` before the `configure` script had a chance to run and
> collect the information about the system. But as far as I can see, in
> such situations (when `configure` output is not yet available), we are
> using `System.Info.os` to determine the OS.
>
Hmm. Is there any way to get shake to print where the rules that it's
complaining about are defined?

**Comment by snowleopard** [comment]
Debugging oracles is a bit tricky.

Could you ask Hadrian to build `hadrian/cfg/system.config` with `--verbose`?

**Comment by bgamari** [comment]
Sadly the error doesn't really shed any more light,
```
$ hadrian/build.cabal.sh  hadrian/cfg/system.config --verbose
Up to date
/-------------------------------------------------------\
| Run Configure "." (stage = Stage0, package = ghc)     |
|      input: hadrian/cfg/system.config.in (and 2 more) |
|  => output: hadrian/cfg/system.config (and 2 more)    |
\-------------------------------------------------------/
Executable found: bash => /bin/bash
shakeArgsWith   0.000s    0%                           
Function shake  0.307s   69%  =========================
Database read   0.001s    0%                           
With database   0.000s    0%                           
Running rules   0.134s   30%  ==========               
Total           0.442s  100%                           
Error when running Shake build system:
* hadrian/cfg/system.config
* hadrian/cfg/system.config settings mk/config.h
* OracleQ (ConfigKey "host-os")
* hadrian/cfg/system.config
Build system error - recursion detected:
  Key type:   FileQ
  Key value:  hadrian/cfg/system.config
Rules may not be recursive
```

**Comment by snowleopard** [comment]
@bgamari Thanks! My feeling is that [this commit](https://github.com/snowleopard/hadrian/commit/c6d7b2a33e6ff987e7112c57555425c285c380e9) is the problem, but I can't quite figure out where I managed to introduce a cyclic dependency which is so difficult to trigger.

**Comment by bgamari** [comment]
Andrey Mokhov <notifications@github.com> writes:

> @bgamari Thanks! My feeling is that [this commit](https://github.com/snowleopard/hadrian/commit/c6d7b2a33e6ff987e7112c57555425c285c380e9) is the problem, but I can't quite figure out where I managed to introduce a cyclic dependency which is so difficult to trigger.
>
Hmm, strangely enough reverting that commit doesn't seem to help.

**Comment by snowleopard** [comment]
@bgamari Ah, that's interesting. Could you perhaps `git-bisect`?

**Comment by bgamari** [comment]
Andrey Mokhov <notifications@github.com> writes:

> @bgamari Ah, that's interesting. Could you perhaps `git-bisect`?
>
Unfortunately it fails as early as
907cad60863a4ea2b940fa7aa6c73b0da82eab7c. I'm afraid I'm unable to build
any earlier commits due to naming shadowing of RuleResult.

**Comment by bgamari** [comment]
Hmm, well this is a bit unfortunate; it ended up being that I was using a stale executable. See #427.

**Comment by snowleopard** [comment]
Uh-h, mystery solved!
