### ISSUE TITLE
Treatment of absolute paths in (-/-) is questionable

### ISSUE THREAD

**Issue by bgamari** [snowleopard/hadrian#434]
Consider the expression,
```
"/build" -/- "/usr/lib/hello"
```
What should this evaluate to? Currently it evaluates to `/build/usr/lib/hello`, interpreting the second argument as a relative path. This seems a bit surprising. Is this intentional?

**Comment by bgamari** [comment]
To be clear, by "surprising" I mean "differs from `System.FilePath.(</>)`" ([haddocks](https://hackage.haskell.org/package/filepath-1.4.1.2/docs/System-FilePath-Posix.html#v:-60--47--62-))

**Comment by snowleopard** [comment]
Here is a relevant issue: https://github.com/snowleopard/hadrian/issues/218

@bgamari We don't want to call `</>` because it messes up slash direction on Windows, but we can make the behaviour less surprising.

**Comment by snowleopard** [comment]
I believe this has been fixed.
