### ISSUE TITLE
Enable branch protections

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/hadrian#437]
You have a policy of never pushing to master, other than through PR's - which makes a lot of sense. Have you considered enforcing it via https://help.github.com/articles/configuring-protected-branches/?

**Comment by snowleopard** [comment]
@ndmitchell `master` is already a protected branch, however the following option is unchecked: `Require pull request reviews before merging`. Do you mean to enable it?

I'm fine as long as it doesn't force me to go via PRs myself: I do most reviews myself anyway, so it would be a bit counter-productive.

**Comment by ndmitchell** [comment]
Going via PR's yourself would mean that you went via the CI test suites as well, which for a project with as many people grabbing it, might be handy. You might have protected it since I last accidentally merged, which might well be enough - I'm just trying to stop me screwing up.

**Comment by snowleopard** [comment]
Indeed! I've ticked this extra box. Hopefully, that's enough protection, so I'm closing this.
