### ISSUE TITLE
build failed because of cabal new-run unrecognised arguments

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#438]
https://travis-ci.org/snowleopard/hadrian/jobs/288055338

As I found, only cabal 2.1.0.0 from the cabal HEAD can accept argument after `--` successfully. Is there a bug in cabal?

@bgamari

**Comment by snowleopard** [comment]
@izgzhen Yes, thanks for registering this as an issue. This comes from merging #435. I guess we might want to revert unless there is another way to pass extra arguments to the executable when using `new-run`?

**Comment by izgzhen** [comment]
@snowleopard I think reverting a bit plus checking cabal's version number > 2100 before using `new-run` would be good

**Comment by snowleopard** [comment]
@izgzhen If we revert then we are back to the problem mentioned by @bgamari:

> The previous approach was terribly unreliable, potentially picking up stale executables which lead me to waste an hour debugging

I'm not familiar enough with Cabal to offer any fixes. Any suggestions about what can be done to improve the reliability for Cabal < 2100?

**Comment by duog** [comment]
Perhaps we could forgo new-build, and always use sandboxes?

**Comment by snowleopard** [comment]
Are there any downsides to using sandboxes?

**Comment by duog** [comment]
I don't think so; I would refine my suggestion to use sandboxes for cabal-install < 2.1.

**Comment by snowleopard** [comment]
@duog OK, let's go for it. If you can send a PR that would be great, otherwise I'll try to do this tonight.

**Comment by snowleopard** [comment]
The above commit seems to have done the trick.

**Comment by bgamari** [comment]
Indeed I think sounds like the right approach to me.
