### ISSUE TITLE
Feature request: An easy way to add compiler flags on the command line

### ISSUE THREAD

**Issue by bgamari** [snowleopard/hadrian#439]
While working on a ticket I realized that there is something that I do fairly often that I'm not sure Hadrian supports: adding compiler flags on the command line. For instance,
```
make -j4 EXTRA_HC_OPTS=-dno-debug-output
```
I will often do this to suppress added trace output until the build gets to the file I am interested in looking at more closely. Then I will run just plain `make` to get the trace output for that file. If I need further output I then will either just copy and paste the command line produced by `make` or add additional flags using `EXTRA_HC_OPTS`.

**Comment by snowleopard** [comment]
@bgamari Hadrian can't change flags via command line that at the moment. However, it's possible via the `UserSettings` file:

https://github.com/snowleopard/hadrian/blob/master/doc/user-settings.md#command-line-arguments

Note that with the above it's easy to add file-specific arguments, e.g. `file "//Prelude.hs" ? arg "foo"`. You can also enable verbose output on per-file basis: 

https://github.com/snowleopard/hadrian/blob/master/doc/user-settings.md#verbose-command-lines

Do you think this is sufficient?

There is nothing fundamentally difficult in making it possible to pass some flags from the command line, but the design space here is quite big. We can certainly discuss this in this issue.

**Comment by bgamari** [comment]
Well, I think using `UserSettings` is fine but I'm concerned that it might rebuild too much. The `make` build system doesn't include compiler flags in its recompilation check whereas I believe Hadrian does. Doesn't this mean that, for instance, adding `-dno-debug-output` will cause recompilation of the entire project?

**Comment by snowleopard** [comment]
@bgamari Aha, indeed. There is a notion of 'tracked arguments' in Hadrian, and most arguments are indeed tracked. However, one can declare some arguments as non-tracked, for example, `-jN` is not tracked when passed to Make:

https://github.com/snowleopard/hadrian/blob/0781e16f1184adc1b35921924326df410ded3e31/src/Target.hs#L17-L26

We can add `-dno-debug-output` as a non-tracked argument.

**Comment by snowleopard** [comment]
I believe this has been fixed.
