### ISSUE TITLE
`setting` is an Oracle

### ISSUE THREAD

**Issue by angerman** [snowleopard/hadrian#444]
The `setting` from `Oracles.Setting.hs` is an Oracle (doh!).
It contains as far as I can see all kinds of autoconf generated
information, which would be good to have at Rule Building
time.

As far as I understand Oracles, they can only be used with
Actions. I however do not see why it needs to be an oracle.

Shouldn't the `cfg/system.config` be generated by the
autoconf configure script, and such be present prior the
actual invocation of the build system, and as such be
static during compilation?

**Comment by ndmitchell** [comment]
You can use action to run an oracle at rule building time - but it is slightly restricted. Can you give an example in pseudo code of the kind of thing you'd like to write?

**Comment by snowleopard** [comment]
The `configure` script takes a bunch of files (such as `system.config.in`) and generates a bunch of files (such as `system.config`), so we treat it just as another `Builder`. The benefits are: 
* Uniform tracking of its dependencies, e.g. if `system.config.in` is changed, we need to rerun `configure`.
* Uniform treatment of command line arguments passed to it, including their tracking.
* Tracking individual settings, such as `ConfCcArgs`, by means of oracles allows us to rebuild only affected rules if any of these settings change.

@angerman Can you be more specific about the disadvantages of the current approach?

**Comment by angerman** [comment]
Right now, I'm wondering how to get the proper set of stage0 packages at the time of building rules.
And this seems to be impossible right now, as stage0packages depend on e.g. the host, and other properties the configure script computes.

**Comment by ndmitchell** [comment]
Why do you want that set of packages when building the rules?

**Comment by angerman** [comment]
> Uniform tracking of its dependencies, e.g. if system.config.in is changed, configure should be rerun.

I see the attractiveness of this. I would however argue that the build system should not take over configure. If I change the autoconf part, and fail to run configure, that's kind of acceptable to me.

However I'd prefer the configure and building step to be separate and not interlinked. The files generated by the configure script should be fixed across the build.

**Comment by angerman** [comment]
> Why do you want that set of packages when building the rules?

I want to ensure that I for example, will *never* be able to build the `rts` package in stage0. I could of course hardcode these as a filter, but that seems quite hacky.

**Comment by ndmitchell** [comment]
Why not move the check - write a rule that can build any package in stage0, and then have that rule check it's valid at the start.

**Comment by angerman** [comment]
Can you point me to an example? Can I have a second matching rule as a fallback?

Assume I want to *not* build rts in stage0, but would want to copy in the rts package from somewhere else for stage0?

**Comment by angerman** [comment]
Ok. After writing that and giving it another though. Yes I might just use a catch all rule and dispatch in the body.

Thanks for the pointer!

**Comment by snowleopard** [comment]
> However I'd prefer the configure and building step to be separate and not interlinked. The files generated by the configure script should be fixed across the build.

@angerman Note that it is possible to run Hadrian with `--skip-configure` in which case the configure step is fully managed by the user.

I think for the majority of people who would like to build GHC the current default if more convenient: no need to know what `configure` is at all.

I do agree however that sometimes not knowing settings statically makes the code more complicated, and there are a few workarounds for this in Hadrian, so if you get stuck, I'm happy to help!

**Comment by hvr** [comment]
> I think for the majority of people who would like to build GHC the current default if more convenient: no need to know what configure is at all.

I strongly disagree. Hiding the well-understood `./configure`-then-`make install` paradigm everyone in the OSS world is used to is  only going to cause all sorts of trouble. Please stop trying to fight GNU Autoconf just because you don't like it, it's not something that needs to hidden from end-users, and certainly not from GHC developers. After all, Hadrian is supposed to make life easier for GHC devs, and if I have to keep passing `--skip-configure` to Hadrian to make it do the right thing, this is only going to cause me frustration everytime I work on GHC and wishing we stayed with the old system.

**Comment by snowleopard** [comment]
> everyone in the OSS world is used to
> you don't like it

@hvr Looks like you banished me from the OSS world :)

> After all, Hadrian is supposed to make life easier for GHC devs

Yes, that's my primary optimisation point. I'm not a GHC dev myself, so what I like doesn't matter at all.

The current default was chosen after a _brief_ discussion with several active GHC devs, and I do not plan to change it right now. When we fix all outstanding issues and are ready to make Hadrian default, please raise this question with GHC devs (not me!).

> I have to keep passing `--skip-configure` to Hadrian to make it do the right thing, this is only going to cause me frustration 

I'm sorry it's frustrating for you. As an intermediate solution just create an alias.

**Comment by hvr** [comment]
> brief discussion with several active GHC devs

I want names

**Comment by snowleopard** [comment]
> I want names

Well, you can start by talking to SPJ. But I don't see why you need specific names -- just talk to all GHC devs.

I'm happy to accept a PR that makes it possible for Hadrian users to pick the default in `UserSettings`.

**Comment by angerman** [comment]
@snowleopard 
> I think for the majority of people who would like to build GHC the current default if more convenient: no need to know what configure is at all.

This puts me in the minority. And I am also not convinced that not needing to know about configure is a good thing when building GHC. So I disagree that I consider the current default convenient. My shell history is now full of hadrian invocations with `--skip-configure`.

Anyhow. The original issue was resolved, and as such I'm going to close this issue.

**Comment by snowleopard** [comment]
@angerman Thanks! So we have at least you and @hvr against the current default. When we are close to making Hadrian the main build system, we'll need to set up a discussion in the GHC developers mailing list to see the general preference.

**Comment by bgamari** [comment]
For what it's worth I also generally agree that `configure` should be left to the user. It's not an infrequent occurrence that I need to pass flags to `configure`. I worry that some day I may do so, only to have Hadrian override my flags during its run may lead to quite some confusion.
