### ISSUE TITLE
Put cWarnings in a different file

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#451]
https://github.com/snowleopard/hadrian/blob/1ade88547a2c3256c6b6e6de8c546a04dc1ae1d3/src/Settings/Builders/Common.hs#L43-L50

Filed in case we forgot :) It should easy to pick up for anyone and not so urgent.

Tip: maybe we should put it along with other warnings args.

**Comment by chitrak7** [comment]
@izgzhen  @snowleopard 
Can we move this warning to the existing file "Settings/Warnings.hs"? We can shift rtsWarnings from file Settings/Packages/Rts here as well.

**Comment by snowleopard** [comment]
Yes, sounds good.
