### ISSUE TITLE
Automatic run of configure silently overrides previous configure options

### ISSUE THREAD

**Issue by bgamari** [snowleopard/hadrian#457]
Earlier today I started a GHC build with some flags passed to `configure`. Essentially, something like this,
```
$ ./configure $flags
$ hadrian/build.sh
```
Only when the build finished did I notice that Hadrian had taken the liberty to run `configure` again on its own, in the process silently overriding my flags. This is rather insidious behavior can drive you crazy if you don't expect it while debugging.

Ultimately, I think it would be best if `hadrian` just left `configure` to the user. Trying to do it automatically is simply too magical, too fragile, and too unpredictable.

However, even if we decide to retain the automatic run, Hadrian should at very least make painstaking effort to preserve any existing configuration. Command line flags passed to `configure` in principle should be too hard, although I don't know what to do about configuration passed via environment variable.

**Comment by snowleopard** [comment]
@bgamari OK, I think with you, @hvr and @angerman all saying the current default is wrong, and noone supporting it (at least here on GitHub), I have no other choice but to change it :)

What about the following plan?
- [ ] Don't run `boot` or `configure` scripts by default.
- [ ] Remove the `--skip-configure` flag.
- [ ] Add  `--configure` flag (`-c` for short) which activates the current behaviour.
- [ ] Update README.

**Comment by bgamari** [comment]
Sounds perfect.

**Comment by snowleopard** [comment]
Done.

**Comment by snowleopard** [comment]
@bgamari What's the protocol regarding pushing changes to GHC? Are you going to do this periodically or shall I do this? 

I'd like the above commit to reach GHC as soon as possible, as I'm planning to send an update about Hadrian to GHC devs mailing list.

**Comment by bgamari** [comment]
Andrey Mokhov <notifications@github.com> writes:

> @bgamari What's the protocol regarding pushing changes to GHC? Are you
> going to do this periodically or shall I do this?
>
> I'd like the above commit to reach GHC as soon as possible, as I'm
> planning to send an update about Hadrian to GHC devs mailing list.
>
I don't mind doing it periodically but if there is a change you would
like to see in ASAP feel free to push an update yourself.

**Comment by snowleopard** [comment]
@bgamari Thanks, will do today, squashing the commits as usual.
