### ISSUE TITLE
"//" rules seem to match even outside of the build root.

### ISSUE THREAD

**Issue by angerman** [snowleopard/hadrian#460]
So I have a `ghc-pkg` (my bootstrap one) in `/path/to/ghc-bootstrap/stage1/bin/ghc-pkg`. Now hadrian calls `need` on any builder, which is totally fine. But the rule for `Program`s, which looks like
```
"//" ++ stageString stage -/- "bin" -/- programName context <.> exe %> \bin -> do
```
still fires, even though my build root is `/path/to/_build`.

**Comment by angerman** [comment]
I believe this is to be expected behavior:
- https://hackage.haskell.org/package/shake-0.16/docs/Development-Shake.html#v:-63--61--61-
- http://shakebuild.com/manual#toplevel-variables

**Comment by snowleopard** [comment]
@angerman I like your solution and I might factor it out into a separate PR soon (time permitting), becuase it might help simplify a couple of other things too. Hope you don't mind me stealing your trick :)

By the way, this may also be relevant: https://github.com/ndmitchell/shake/issues/376

**Comment by snowleopard** [comment]
I think this has now been fixed. If not, please reopen.
