### ISSUE TITLE
build.cabal.sh breaks badly if hadrian's dependencies do not successfully install.

### ISSUE THREAD

**Issue by duog** [snowleopard/hadrian#463]
running build.cabal.sh with Cabal <2.1 triggers this code path:
```bash
    if ! ( "$CABAL" sandbox hc-pkg list > /dev/null 2>&1); then
        "$CABAL" sandbox init
        "$CABAL" sandbox add-source ../libraries/Cabal/Cabal
        "$CABAL" install                \
            --dependencies-only         \
            --disable-library-profiling \
            --disable-shared
    fi
```

If dependencies do not cleanly install one must manually delete the sandbox to proceed.

**Comment by snowleopard** [comment]
Thanks @duog! I suppose the right solution is to detect the failure and delete the sandbox?

I'm not familiar with Cabal sandboxes so it will take me some time to dig out the right commands to run. Presumably this is an easy fix, so a PR is very welcome.

**Comment by chitrak7** [comment]
@snowleopard @izgzhen deleting .sandbox file and then rerunning build works whenever I get this error. I believe this should be a good fix here.

**Comment by izgzhen** [comment]
related to #524
