### ISSUE TITLE
Reduce cost of rebuilding hadrian on change to UserSettings

### ISSUE THREAD

**Issue by bgamari** [snowleopard/hadrian#471]
I suspect that we should do one of the following to reduce the cost of rebuilding Hadrian when `UserSettings` is changed,

 * Compile all of `hadrian` with `-O0` by default
 * Add a `OPTIONS_GHC -O0` pragma to `src/UserSettings.hs`
 * Add `NOINLINE` pragmas to the bindings in `src/UserSettings.hs`

In all cases the goal is to prevent GHC from giving unfoldings to the bindings in `UserSettings`, meaning that changes will only require a single-module rebuild and relink.

**Comment by angerman** [comment]
I think th usersettings should be a file read in by ghc.

I’ve suggested YAML to @hvr ;-)

**Comment by angerman** [comment]
I should have thought of dhall, not sure why I keep forgetting it’s name.

**Comment by angerman** [comment]
Maybe @Gabriel439 has something to say in support or against using dhall for this?

**Comment by bgamari** [comment]
On November 16, 2017 9:50:37 PM EST, Moritz Angermann <notifications@github.com> wrote:
>Maybe @Gabriel439 has something to say in support or against using
>dhall for this?

I think there would need to be a very good reason for us to accept a dependency for this.

**Comment by Gabriel439** [comment]
I have no context here, but since I was cc:ed I'll derail the discussion by recommending Nix instead =P

See: https://github.com/Gabriel439/slides/blob/master/nix-derivation/slides.md

**Comment by hvr** [comment]
> I’ve suggested YAML to @hvr ;-)

 :angry: :rage: :anger: :boom: :skull_and_crossbones:  ;-)

**Comment by snowleopard** [comment]
I believe this has been fixed.
