### ISSUE TITLE
Add support for fast rebuild of a single package (ignoring all other dependencies)

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/hadrian#472]
As discussed in #464, we need a way to tell Hadrian to rebuild a single GHC package ignoring any external dependencies, just like we did when implementing the `--freeze1` feature #250.

See this comment: https://github.com/snowleopard/hadrian/issues/464#issuecomment-345016179.

**Comment by snowleopard** [comment]
@hvr [comments](https://github.com/snowleopard/hadrian/issues/464#issuecomment-346975881):

> > Would you like Hadrian to detect the current directory and make decisions based on it, just like Make? This sounds a bit fragile to me.

> Why do you consider this fragile? As you point out, CWD-sensitivity is a commonly used paradigm for make, and fwiw, cabal new-build also supports this paradigm (currently w/ package granularity; but it's planned to make it more fine-grained re CWD). Another example of a CWD-sensitive UI is Git. In general, tooling designed for Unix shells quite often is CWD sensitive.

I'd like to respond here, because this is a more relevant issue:

By fragile I mean the following: you run the build system but it sometimes produces incorrect results, i.e. when run in a package directory (possibly accidentally) it will not rebuild some files.  

You give an example of `git`, but if I run `git status` from a subdirectory, it still gives me accurate information about **all edited files** outside that subdirectory, so it's output is still correct, it just uses a different reference point. Now imagine that `git status` instead listed **only files within the current directory**? That would be quite fragile! You could accidentally lose an edit.

I think it would be more robust if users had to use a flag to tell Hadrian that they are OK with incorrect build results -- they take the risk for the sake of a very fast rebuild. 

I view build systems as safety-critical components of a software project. It shouldn't be easy to circumvent the guarantees that they provide.

**Comment by snowleopard** [comment]
@ndmitchell Could you comment on the above from your experience of working with build systems?

**Comment by hvr** [comment]
@snowleopard I see, I misunderstood your comment to be more general. I agree that CWD-sensitivity shouldn't sacrifice correctness. To take an example from `cabal new-build`, if you're in a multi-package project, the folder from which you invoke `cabal new-build` determines the implicit build-target/goal.

So e.g. the cabal project is set up as a multi-package project, with 4 folders via its `cabal.project` file:

```
packages: Cabal/ cabal-testsuite/ cabal-install/ solver-benchmarks/
```

If you say `cabal new-build all` it doesn't matter in which folder you are; the explicit build-target `all` refers to building everything in the current *project*. Similarly, you can say `cabal new-build exe:cabal`, and it will always build the executable `cabal` (from the `cabal-install` *package*), regardless of the CWD.

However, if you say `cabal new-build`, it depends in which folder you are. If you happen to be in the `Cabal/` folder, only all active components from the  `Cabal` package will be built. If, on the other hand, you happen to be inside the `cabal-install/` folder, `cabal new-build` will build all components from the `cabal-install` package (which includes the `cabal` executable) -- *and* if necessary rebuild any dependencies (e.g. `lib:Cabal` from the package in the `../Cabal/` folder). 

`cabal new-build` does not support a "fast rebuild (ignoring all dependencies)" mode: if a dependency becomes dirty, it must be rebuilt; always ensuring this invariant makes things easier. In Cabal.s case, the cases where you'd want to break this invariant are too seldom for anybody to have requested such a feature (and I'm not sure the added complexity would be justified).

Otoh, for GHC/Hadrian having such opt-in *unsafe* shortcutting/freezing features  saves a lot of GHC developer time... :-)

**Comment by ndmitchell** [comment]
I've used some build system where it did a magic cd to the root before processing your commands. I've used other build systems where if you were in a specific project directory, it adjusted the implicit want's to be specific to that directory. I would suggest that only the `want`'s change at most, not the rules or anything else, then you remain consistent.

**Comment by chitrak7** [comment]
@snowleopard Do we currently have any method to rebuild a single package and its dependencies?

**Comment by angerman** [comment]
With #531, you should be able to build single package by asking for the relevant `.conf` file.
E.g. `_build/stage1/lib/package.conf.d/base-...conf` I guess we could create shortcuts for those?

**Comment by snowleopard** [comment]
@angerman Yep, I think we will want a shortcut, and perhaps also freeze unrelated parts of the tree?

**Comment by angerman** [comment]
You'd want to generate those on the fly though. You'd not really want to hardcode them, otherwise this will be suprising to people adding addtional dependencies to ghc.

Iterating over the set of packages, filtering out for lirbary (and here it becomes tricky: in principle we can have multiple components per library, while this is something that's not used in ghc TODAY, we should strive to understand packages as sets of components. Lirbaries & Executables).

Freezing with #531 basically becomes: don't rebuild anything in `$buildRoot/stage0`.

**Comment by snowleopard** [comment]
> Freezing with #531 basically becomes: don't rebuild anything in `$buildRoot/stage0`.

@angerman I think one could go even further: don't rebuild anything outside `$buildRoot/stage1/package`.

**Comment by snowleopard** [comment]
I believe this has been fixed.
