### ISSUE TITLE
Hadrian commits mess up GHC Trac

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/hadrian#480]
Just spotted: https://ghc.haskell.org/trac/ghc/ticket/454#comment:7

@bgamari Can we do anything about this?

**Comment by angerman** [comment]
May I propose a submodule until we fully merge Hadrian as subtree into ghc and at that point delete the upstream repository?

**Comment by bgamari** [comment]
> @bgamari Can we do anything about this?

Of course. There are at least three options,

a. Be careful to delete the commit messages in the squashed commit
b. Do as @angerman suggests and move hadrian to a submodule until we are closer to merging
c. Ignore the problem in hopes that we can merge soon

**Comment by snowleopard** [comment]
@bgamari @angerman Thanks! I think option (a) is my current preference.
