### ISSUE TITLE
Remove text from local package list?

### ISSUE THREAD

**Issue by bgamari** [snowleopard/hadrian#481]
Why is `text` in the local packages list in `cabal.project`? This means that Cabal will be unable to share the `text` build with the user's store which increases CI build times.

**Comment by snowleopard** [comment]
Hmm, I'm puzzled. I thought the `cabal` library required the in-tree version of `text`, but it doesn't look like it's the case now. If we can drop `text` from `cabal.project` and `stack.yaml` let's do this, of course!

**Comment by snowleopard** [comment]
Done in #491
