### ISSUE TITLE
Rethink the `-Werror` decision.

### ISSUE THREAD

**Issue by angerman** [snowleopard/hadrian#485]
Currently Hadrian fails in spectacular ways to build ghc for anything but the CI targets. This is mostly due to `-Werror`, yes I can go in and add the `-Wno-xxx` flags to `Warnings.hs`, but that puts the burden on **me**, and doesn't guarantee that a bump of a library won't break a specific build again.

While I do see the value in no-warnings, it means builds that run over night to produce a multitude of cross compilers just fail after some time, even though they could have (and did with the make base build system) built just fine.

**Comment by Mistuke** [comment]
I agree, the few times I tried to use Hadrian it always failed due to a `-Werror`. But the make based one worked fine, I didn't expect `-Werror` to even be on for `--flavour=devel2` unless I'm doing something wrong.

In general I think it should just do what the make based system did to ease transition and then we can talk later about changing the defaults.

**Comment by snowleopard** [comment]
@angerman @Mistuke Sure, I'm fine with removing `-Werror` from defaults. It's something that can be easily added back later. Also, it may be the reason behind this recent issue #483.

> In general I think it should just do what the make based system did to ease transition and then we can talk later about changing the defaults.

I've already forgotten what the Make's default is. When does it add `-Werror`? If you can create a PR to do The Right Thing I'd be happy to review and merge!

**Comment by Mistuke** [comment]
@snowleopard Unless I'm mistaken, the make version only enables `-Werror` for validate builds. https://github.com/ghc/ghc/blob/master/mk/flavours/validate.mk#L29

Anything else doesn't have it.

**Comment by snowleopard** [comment]
@Mistuke Aha, I see. I think we can simply drop `-Werror` for now, and bring it back when resolving the issue with validation #299. I can take care of this.

**Comment by ggreif** [comment]
IIRC I've seen errors coming from warnings in plain `make` for stage2. I
almost never use `validate`.

**Comment by Mistuke** [comment]
@snowleopard Yeah, I think that's the right thing to do. I think #483 should be "solved" too then. I suspect #483 is an issue with GHC, as the buildbots have been broken for ages so people have committed code that don't pass validation. Also a normal development build often has warnings as you haven't cleaned up the code yet :)

@ggreif well, ideally you should be running validate before you push a patch. We consider anything that doesn't pass a validate build as broken. That's how issues like #483 happen. And sometimes the warnings do point to a real issue.

**Comment by snowleopard** [comment]
Done in #487.

**Comment by Mistuke** [comment]
Thanks @snowleopard !

**Comment by snowleopard** [comment]
@Mistuke Thanks for your help :)
