### ISSUE TITLE
Haskell Symposium paper is not publically available

### ISSUE THREAD

**Issue by bergey** [snowleopard/hadrian#488]
I get a 403 when I try to view the paper hosted at [Newcastle](https://www.staff.ncl.ac.uk/andrey.mokhov/Hadrian.pdf).  I can get it through [the ACM](https://dl.acm.org/citation.cfm?id=2976011&CFID=798369340&CFTOKEN=81568958), but I don't think that is public either.  (Rather, the ACM citation page is public, but I need to be logged in to get the full-text PDF.)

**Comment by snowleopard** [comment]
@bergey Thanks for spotting the broken link! I've now replaced that link by the ACM Author-izer link, so one can download the published version for free from ACM.

**Comment by snowleopard** [comment]
The link at Newcastle got slightly changed to https://www.staff.ncl.ac.uk/andrey.mokhov/hadrian.pdf -- note the lower-case `h`.

**Comment by ndmitchell** [comment]
FWIW, I also have a copy at https://ndmitchell.com/downloads/paper-non_recursive_make_considered_harmful-22_sep_2016.pdf - the URL's for all my papers have been stable for many years.
