### ISSUE TITLE
Run ghc's test can't work

### ISSUE THREAD

**Issue by sighingnow** [snowleopard/hadrian#494]
When I run `build.stack.sh test`, I get the following error:

```
runtests.py: error: unrecognized arguments: --configfile=testsuite/config/ghc
```

The ghc's `--configfile` flag has already been renamed to `--config-file` [six months ago](https://github.com/ghc/ghc/commit/5e940bd3d554729ce650008a72b4f82a78578a7b).

**Comment by sighingnow** [comment]
I would like to push a patch to improve the test support of hadrian. Should I submit the patch to [GHC phabricator](https://phabricator.haskell.org/) or open a pull request here ?

**Comment by snowleopard** [comment]
@sighingnow Many thanks for the report and for offering your help! Please open a PR here.

Note that there is also the `validate` build rule, which runs GHC's validation script, which you might want to try as well. However, in any case we should try to fix the `test` rule as well.

**Comment by bgamari** [comment]
@angerman, @alpmestan, I believe this is relevant to your work.

**Comment by alpmestan** [comment]
@bgamari It is, but as you can see in https://github.com/snowleopard/hadrian/pull/495, @sighingnow and I discussed all the problems that we respectively had identified, both there and by email a little bit. @sighingnow seemed well on the way to getting a good chunk of the tests working. We'll mostly be able to reuse his work directly (even though it might require a tweak or two) with the relocatable approach, nothing scary really. :)

**Comment by izgzhen** [comment]
Running `./build.sh test` now led to an error:

```
/home/zhen/repos/ghc/_build/stage1/rts/build/libCffi_p.a: copyFile: does not exist (No such file or directory)
shakeArgsWith    0.000s    0%                           
Function shake   0.219s    0%                           
Database read    0.232s    0%                           
With database    0.098s    0%                           
Running rules  604.736s   99%  =========================
Total          605.286s  100%                           
Error when running Shake build system:
* test
* _build/stage1/bin/ghc
* OracleQ (PackageDataFile (Context {stage = Stage1, package = Package {pkgLanguage = Haskell, pkgType = Program, pkgName = "ghc-bin", pkgPath = "ghc"}, way = v}))
* _build/stage1/ghc/setup-config
* _build/stage1/lib/package.conf.d/containers-0.5.11.0.conf
* OracleQ (PackageDataFile (Context {stage = Stage1, package = Package {pkgLanguage = Haskell, pkgType = Library, pkgName = "containers", pkgPath = "libraries/containers"}, way = v}))
* _build/stage1/libraries/containers/setup-config
* _build/stage1/lib/package.conf.d/ghc-prim-0.5.2.0.conf
* OracleQ (PackageDataFile (Context {stage = Stage1, package = Package {pkgLanguage = Haskell, pkgType = Library, pkgName = "ghc-prim", pkgPath = "libraries/ghc-prim"}, way = v}))
* _build/stage1/libraries/ghc-prim/setup-config
* _build/stage1/lib/package.conf.d/rts-1.0.conf
ExitFailure 1
```

**Comment by snowleopard** [comment]
This seems to be superseded by #669.
