### ISSUE TITLE
Incomplete extensions of files encountered during build

### ISSUE THREAD

**Issue by chitrak7** [snowleopard/hadrian#508]
On running build on windows 10, Errors were produced as these files were not found:
hadrian/cfg/system.config 
settings 
mk/config.h

There are files named the following in the directory.
*settings.in
* hadrian/cfg/system.config.in
* hadrian/cfg/system.config settings mk/config.mk.in

I believe the extensions of the files are not properly written in the build system @snowleopard

**Comment by snowleopard** [comment]
@chitrak7 Can you copy the error that was reported, including the exact command line you run?

**Comment by chitrak7** [comment]
shakeArgsWith   0.001s    0%
Function shake  0.278s   61%  =========================
Database read   0.001s    0%
With database   0.000s    0%
Running rules   0.169s   37%  ===============
Total           0.449s  100%
Error when running Shake build system:
* OracleQ (KeyValue ("hadrian/cfg/system.config","host-os"))
* hadrian/cfg/system.config
* hadrian/cfg/system.config settings mk/config.h
Configuration file hadrian/cfg/system.config is missing.
Run the configure script manually or let Hadrian run it automatically by passing the flag --configure.
CallStack (from HasCallStack):
  error, called at src\Rules\Configure.hs:19:13 in main:Rules.Configure
@snowleopard

**Comment by alpmestan** [comment]
You need to pass the `-c` or `--configure` option the first time you run hadrian, if I remember correctly.

**Comment by snowleopard** [comment]
@chitrak7 Aha, I see. If you read the error message carefully, it tells you exactly what to do:

```
Configuration file hadrian/cfg/system.config is missing.
Run the configure script manually or let Hadrian run it automatically by passing the flag --configure.
```

The `hadrian/cfg/system.config` file is generated by running the `boot` and `configure` scripts, as explained in the [preparation guide](https://ghc.haskell.org/trac/ghc/wiki/Building/QuickStart).

As @alpmestan points out, Hadrian can run these scripts for you if you pass the `--configure` flag to it.

**Comment by snowleopard** [comment]
@chitrak7 I closed this issue, but if you think the README can be improved to help beginners, please feel free to send a pull request.

**Comment by ndmitchell** [comment]
I think the user experience could be improved by automatically doing the right thing rather than spitting out an error message saying what to do...

**Comment by snowleopard** [comment]
@ndmitchell I agree and the automated `configure` used to be the default, but @bgamari, @angerman and @hvr rebelled against it. With no one backing me up I had to concede in #457 :(

**Comment by ndmitchell** [comment]
😞

**Comment by chitrak7** [comment]
@snowleopard  I think this should be mentioned in the file doc\windows.md . This could help a lot of beginners as me.

**Comment by snowleopard** [comment]
@chitrak7 Good point!

I've added `--configure` to the Windows build script and a note that it's only needed during the first build.
