### ISSUE TITLE
Discrepancy in syntax in lookupValue and system.config

### ISSUE THREAD

**Issue by chitrak7** [snowleopard/hadrian#509]
The function lookupValue in Hadrian.Oracles.TextFile expects file in this syntax:
-- | Lookup a value in a text file, tracking the result. Each line of the file
-- is expected to have @key = value@ format.

This function is called with file system.config as an argument, but the lines in this files are of the format:
key = @value@ e.g. 
cross-compiling       = @CrossCompiling@
Thus creating a discrepancy and possible errors

**Comment by snowleopard** [comment]
@chitrak7 I think this is just a misunderstanding:

* The comment uses Haddock markup syntax where `@text@` renders `text` using a fixed-width font.
* The settings in `system.config.in` use the Autoconf syntax `@value@` as a placeholder -- it is replaced by the `configure` script with concrete values -- see `system.config`.

I can see how it can be a bit confusing. I suggest you build Haddock documentation by `stack haddock` and then you'll be able to read the documentation in HTML, where you'll see no `@`.
