### ISSUE TITLE
Hadrian failed to build stage1 ghc-prim

### ISSUE THREAD

**Issue by sighingnow** [snowleopard/hadrian#514]
When building ghc using hadrain with the following command

~~~
stack exec hadrian -- \
    --lint                         \
    --directory "$absoluteRoot/.." \
    -j8                            \
    --flavour=devel2               \
    "$@"
~~~

I got the error:

~~~
Error when running Shake build system:
* _build/stage1/libraries/ghc-prim/libHSghc-prim-0.5.2.0_p.a
* OracleQ (KeyValue ("_build/stage1/libraries/ghc-prim/package-data.mk","MODULES"))
* _build/stage1/libraries/ghc-prim/package-data.mk
* _build/stage1/libraries/ghc-prim/package-data.mk _build/stage1/libraries/ghc-prim/setup-config
* libraries/ghc-prim/configure
Error, file does not exist and no rule available:
  libraries/ghc-prim/configure
~~~

Seems due to the change of ghc-prim in https://phabricator.haskell.org/D4378

**Comment by angerman** [comment]
Which GHC are you trying to build? HEAD?

**Comment by sighingnow** [comment]
Yes, I'm trying to build the ghc HEAD.

+ GHC version: [commit f57c3059d7c8b8e00bd3a9f9153c3520f6db14d4](https://github.com/ghc/ghc/tree/f57c3059d7c8b8e00bd3a9f9153c3520f6db14d4) (testsuite: Bump allocations for T9630)
+ Hadrian version: commit da397291a9052387862c27c87ec29b6fce2c7d77 (Make shell.nix less broken)

**Comment by angerman** [comment]
Strange. `libraries/ghc-prim/configure` should exists. It does for me.

**Comment by sighingnow** [comment]
I finally manage to make it work after deleting the `_build`, `inplace` and `hadrian/cfg/system.config` manually (and restart the shell).

Maybe something went wrong with my local msys2 environment. Many thanks for your attention to this! @angerman
