### ISSUE TITLE
Consider moving ghc_boot_platform.h

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/hadrian#516]
I see a `ghc_boot_platform.h` in `_build/stage0/compiler`, and another in `_build/stage0/compiler`. I wonder if this should really live in `_build/generated` (where other generated headers go), which might let you simplify the header directory story?

Just a thought, please close if it doesn't seem useful.

**Comment by snowleopard** [comment]
Yes, we could keep all generated headers in `generated`, but there are two issues here:

* These files are different in different stages, so this will force us to introduce subdirectories in `generated`.

* These files are used only by `compiler` as far as I can tell. Perhaps, `compiler/generated` would be best?

**Comment by ndmitchell** [comment]
Is `ghc_boot_platform.h` really different per stage? Looking at it, it seemed invariant on the stage.

**Comment by snowleopard** [comment]
Here is where these files are generated:

https://github.com/snowleopard/hadrian/blob/master/src/Rules/Generate.hs#L385-L438

Perhaps the difference occurs only when cross compiling.

**Comment by bgamari** [comment]
Indeed, these will only differ while cross-compiling.

**Comment by ndmitchell** [comment]
Ok, then my idea seems a bad one.
