### ISSUE TITLE
build.cabal.sh permission bits changed by running build

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#517]
```
diff --git a/build.cabal.sh b/build.cabal.sh
old mode 100644
new mode 100755
```

**Comment by snowleopard** [comment]
I'm confused. Are you saying Hadrian changed permissions of this file? I don't see how it could do that!

**Comment by snowleopard** [comment]
Oops, it does do that actually:
```
# By default on Linux/MacOS we build Hadrian using Cabal
chmod a+x "$root/build.cabal.sh"
(. "$root/build.cabal.sh" "$@")
```

I remember now: without this it was failing on CI. Perhaps, we can move this to CI scripts?

**Comment by izgzhen** [comment]
> Perhaps, we should move this to CI scripts?

It sounds reasonable to me. Or we could change the permission bit once and for all.

**Comment by snowleopard** [comment]
@izgzhen Ah, so git can actually store permission bits? In this case yes, that would be a better solution. Could you send a PR?

**Comment by snowleopard** [comment]
I've reopen the issue to also fix `build.sh` -- see the PR above.
