### ISSUE TITLE
Error in validation

### ISSUE THREAD

**Issue by chitrak7** [snowleopard/hadrian#518]
On running "./build.sh validation", this is the error message I get.

make[1]: *** [test] Error 1
make: *** [fast] Error 2
shakeArgsWith     0.000s    0%                           
Function shake    0.245s    0%                           
Database read     0.840s    0%                           
With database     0.046s    0%                           
Running rules  1167.656s   99%  =========================
Total          1168.787s  100%                           
Error when running Shake build system:
* validate
user error (Development.Shake.cmd, system command failed
Command: /usr/bin/make -C testsuite/tests THREADS=4 fast
Exit code: 2
Stderr:
make[1]: *** [test] Error 1
make: *** [fast] Error 2
)

I think the command is working fine, but it is not returning the complete results but only the final Error values.

**Comment by chitrak7** [comment]
This is the result when I run Makefile directly from /testsuite/tests.

[test1.txt](https://github.com/snowleopard/hadrian/files/1773975/test1.txt)
Clearly, the error codes are the same, but the rest of validation result is not.

**Comment by izgzhen** [comment]
> ./build.sh validation

Do you mean `./build.sh validate`?

> I think the command is working fine, but it is not returning the complete results but only the final Error values.

The complete results in test1.txt is in verbose output. You can run it with `-VV`.

**Comment by chitrak7** [comment]
Yeah, that does it. Thanks @izgzhen.
