### ISSUE TITLE
Consider adding additional flag to make command while running validate

### ISSUE THREAD

**Issue by chitrak7** [snowleopard/hadrian#519]
Currently, when we run ./build.sh validate, the make command takes two arguments which are: "fast" and "THREADS=t". We can add a third argument "VERBOSE=1" in make command of Settings.Builders.Make.  Here is the list of values supported by verbose: 
     n=0: No per-test output
     n=1: Only failing test results
     n=2: As above, plus progress information (names of all tests)
     n=3: As above, plus commands called.
     n=4: As above, plus performance numbers even for succeeding test cases
The default is n=3. But I don't think this is a good Idea as it generates a lot of logs and it is painstaking to go through it all to find something valuable. 
@snowleopard

**Comment by snowleopard** [comment]
@chitrak7 It's easy for you to add this flag locally by editing this line:

https://github.com/snowleopard/hadrian/blob/master/src/Settings/Builders/Make.hs#L16

Even better, you can add it to your `hadrian/UserSettings.hs` file, as describe here:

https://github.com/snowleopard/hadrian/blob/master/doc/user-settings.md

This will then be ignored by `git`.

**Comment by snowleopard** [comment]
But I don't mind to also provide this as a general functionality.

**Comment by chitrak7** [comment]
@snowleopard I have implemented it in my system. I just believe it will be a good addition as in my view, there is no use of the complete log

**Comment by snowleopard** [comment]
@chitrak7 It's fine if you implement the ability to pass a different verbosity setting to the `validate` rule, but I don't think we should make Hadrian defaults different from the defaults used in the GHC build system. This may unnecessarily confuse GHC developers trying out Hadrian.

**Comment by chitrak7** [comment]
@snowleopard I think then we can add this to the documentation.

**Comment by snowleopard** [comment]
@chitrak7 Sure! Try to document everything that helps you be more productive when hacking on Hadrian. 

Perhaps, the wiki started by @izgzhen could be a good place for this: 

https://github.com/snowleopard/hadrian/wiki.

**Comment by snowleopard** [comment]
I believe this has been fixed.
