### ISSUE TITLE
Cabal: Could not resolve dependencies.

### ISSUE THREAD

**Issue by chitrak7** [snowleopard/hadrian#527]
On running the build on a fresh system, I am encountering this problem:
trying: hadrian-0.1.0.0 (user goal)
next goal: Cabal (dependency of hadrian-0.1.0.0)
rejecting: Cabal-2.3.0.0, Cabal-2.0.1.1/installed-Ain...,
Cabal-1.24.2.0/installed-1.2..., Cabal-2.0.1.1, Cabal-2.0.1.0, Cabal-2.0.0.2,
Cabal-1.24.2.0, Cabal-1.24.0.0, Cabal-1.22.8.0, Cabal-1.22.7.0,
Cabal-1.22.6.0, Cabal-1.22.5.0, Cabal-1.22.4.0, Cabal-1.22.3.0,
Cabal-1.22.2.0, Cabal-1.22.1.1, Cabal-1.22.1.0, Cabal-1.22.0.0,
Cabal-1.20.0.4, Cabal-1.20.0.3, Cabal-1.20.0.2, Cabal-1.20.0.1,
Cabal-1.20.0.0, Cabal-1.18.1.7, Cabal-1.18.1.6, Cabal-1.18.1.5,
Cabal-1.18.1.4, Cabal-1.18.1.3, Cabal-1.18.1.2, Cabal-1.18.1.1, Cabal-1.18.1,
Cabal-1.18.0, Cabal-1.16.0.3, Cabal-1.16.0.2, Cabal-1.16.0.1, Cabal-1.16.0,
Cabal-1.14.0, Cabal-1.12.0, Cabal-1.10.2.0, Cabal-1.10.1.0, Cabal-1.10.0.0,
Cabal-1.8.0.6, Cabal-1.8.0.4, Cabal-1.8.0.2, Cabal-1.6.0.3, Cabal-1.6.0.2,
Cabal-1.6.0.1, Cabal-1.4.0.2, Cabal-1.4.0.1, Cabal-1.4.0.0, Cabal-1.2.4.0,
Cabal-1.2.3.0, Cabal-1.2.2.0, Cabal-1.2.1, Cabal-1.1.6, Cabal-1.24.1.0
(conflict: hadrian => Cabal>=2.1.0.0 && <2.3)
fail (backjumping, conflict set: Cabal, hadrian)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: hadrian, Cabal
Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.

Steps taken were:
Clone git and submodules 
Clone hadrian
copy build.mk
run ./boot and ./configure
run ./build.sh

Before running build, the version of Cabal, as per cabal info is
Versions installed: 1.24.2.0, 2.1.0.0, 2.2.0.0, 2.3.0.0 (and 1 other)
After running build, the versions were
Versions installed: 1.24.2.0, 2.0.1.1
After removing cabal.sandbox.config the versions was restored
Versions installed: 1.24.2.0, 2.1.0.0, 2.2.0.0, 2.3.0.0 (and 1 other)

**Comment by snowleopard** [comment]
@chitrak7 Thanks! Looks like this might be the same issue as on AppVeyor:

https://ci.appveyor.com/project/snowleopard/hadrian/build/1.0.951

**Comment by snowleopard** [comment]
@chitrak7 Looks like an easy fix: #528.

**Comment by snowleopard** [comment]
The above fix seems to have solved this particular issue.
