### ISSUE TITLE
Drop Support for ghc-8.0

### ISSUE THREAD

**Issue by chitrak7** [snowleopard/hadrian#529]
Yesterday, GHC has dropped support for GHC-8.0. I think we should do it also.
I believe only affected dependency will be base.
Refer to commit: 
152055a19cf368439c8450040b68142f8e7d0346

**Comment by snowleopard** [comment]
@chitrak7 Thanks! Yes, we'll need to switch to a later GHC and update our CI infrastructure.

However, let's postpone this until we have a working build, as #523 is still not fully resolved.

**Comment by izgzhen** [comment]
we updated the CI script to 8.2+ now, is there anything left to be done?

**Comment by alpmestan** [comment]
I personally don't think so. The `configure` script errors out with a proper error message if one's trying to use a incompatible boot ghc.

**Comment by snowleopard** [comment]
OK, let me close this.
