### ISSUE TITLE
Add more targets to Hadrian

### ISSUE THREAD

**Issue by chitrak7** [snowleopard/hadrian#536]
Make currently supports a few targets which I couldn't find in Hadrian. Implementation of a few are pretty simple I think they are "help", "distclean", "maintainer-clean", "fasttest", "slowtest" @snowleopard

**Comment by izgzhen** [comment]
ping https://github.com/snowleopard/hadrian/issues/360

**Comment by snowleopard** [comment]
I agree, this seems like a duplicate of #360, so closing this. Let's revise/add more details to #360.
