### ISSUE TITLE
Follow-up to #531

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/hadrian#540]
Here is a list of things that I'd like to look at after #531 has been merged:
- [x] Try to break import loops by adding more `.Type` modules.
- [x] Work on #538 to fix `-c`.
- [x] Figure out where we can replace `buildDir` with `contextDir`. 
- [x] Finish the `Settings/Packages.hs` story.
- [x] Move `ghctags` and `haddock`back to Stage2.
- [x] Clean up remaining `ghc-cabal` bits.
- [x] Clean up remaining installation infrastructure.

**Comment by alpmestan** [comment]
`-c` is fixed (#571).

**Comment by snowleopard** [comment]
@alpmestan Yep, checked the box.

**Comment by snowleopard** [comment]
I finished merging all package-specific arguments into `Settings/Packages.hs` in #622.

**Comment by snowleopard** [comment]
I'm moving Haddock and `ghctags` to Stage2, since this is what Make build system does. I haven't found a justification for moving Haddock to Stage2 in #531. 

@alpmestan If this is wrong, please shout.

**Comment by alpmestan** [comment]
There probably isn't a justification. I don't think this should be a problem. As long as you make sure everything still happily builds, we should be fine :-)

**Comment by snowleopard** [comment]
@alpmestan Thanks, done :)

**Comment by snowleopard** [comment]
I think I'm done with this issue. 

> Figure out where we can replace `buildDir` with `contextDir`.

The answer to this appears to be "No, we need to keep `buildDir`", since the Cabal library insists on keeping build artefacts in the `build` subdirectory.
