### ISSUE TITLE
cmd failed but stdin is missing from debugging info 

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#545]
For example, the #543 probably failed between the following line 

https://github.com/snowleopard/hadrian/blob/9a46249e974c99a2015d7bba514b252c31ff8575/src/Builder.hs#L259-L266

You would see a `-` at the end of `Command: /usr/local/bin/ghc-pkg --global-package-db _build/stage0/lib/package.conf.d register -v0 -`, but this isn't complete since some stdin need be fed into the command line in order to run.

If a command failed, we might need to throw this out explicitly

**Comment by angerman** [comment]
@izgzhen so you want to *dump* `Stdin` to the console if the command failed? Am I understanding this right? If so, what would probably be something that needs to be addressed in Shake's `cmd`?

**Comment by izgzhen** [comment]
> so you want to dump Stdin to the console if the command failed? Am I understanding this right? If so, what would probably be something that needs to be addressed in Shake's cmd?

I think we can address it either in Shake or in this repo (by getting `Exit` out).

**Comment by ndmitchell** [comment]
I created a Shake issue https://github.com/ndmitchell/shake/issues/577

**Comment by snowleopard** [comment]
I believe this has been fixed.
