### ISSUE TITLE
Rename GhcPkgMode::Clone to GhcPkgMode::Register?

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#546]
@alpmestan I am curious why it is called `Clone`, since the sub-command it uses is `register`.

thanks!

**Comment by alpmestan** [comment]
@izgzhen IIRC this particular builder is used for "cloning" the package database of the stage 0 compiler (copying it somewhere under our build root). @angerman Do I remember correctly?

**Comment by angerman** [comment]
@alpmestan that is correct. Clone is `dump` + `register`.

**Comment by angerman** [comment]
I should note: I mean `describe` if I say `dump` :(

**Comment by izgzhen** [comment]
It makes sense, thanks!
