### ISSUE TITLE
Improve haddock coverage of the project

### ISSUE THREAD

**Issue by angerman** [snowleopard/hadrian#55]
I'm lost from time to time in the source, trying to figure out how the parts belong together.  I guess adding more extensive documentation to the functions would help with this in a big way.

**Comment by snowleopard** [comment]
More documentation would be great. However, bear in mind that the codebase is still unstable and large refactorings, such as #18, are coming.

**Comment by snowleopard** [comment]
I've been continuously improving Haddock coverage in Hadrian, and now I think we are in a good shape. Let me therefore close this issue, but if there are any specific places that require better documentation, please feel free to reopen, or better raise a new specific issue.
