### ISSUE TITLE
Does hadrian support the equivalent of: make STAGE=1 TEST="A B C" ?

### ISSUE THREAD

**Issue by alpmestan** [snowleopard/hadrian#556]
i.e running some tests against the stage1 compiler (`<build root>/stage0/bin/ghc`). Simon PJ expressed interest in having hadrian support this, and I'm not sure the current validate/test rules support it. Does it? If not, I'll add this issue to my TODO :-)

**Comment by snowleopard** [comment]
@alpmestan Yes, sure, we will need to support existing flags for testsuite. I think this is the existing issue

https://github.com/snowleopard/hadrian/issues/187

If it's incomplete, please add a comment there.

**Comment by Mistuke** [comment]
There are  quite a few other make variables though https://github.com/ghc/ghc/blob/master/testsuite/mk/test.mk#L10 are a few.

**Comment by chitrak7** [comment]
With #621 We can close this now @snowleopard ?

**Comment by snowleopard** [comment]
@chitrak7 Let me give this a try. I'll close the issue if everything works as expected.

**Comment by snowleopard** [comment]
@alpmestan By the way, what do you think -- does #621 provide enough functionality?

**Comment by alpmestan** [comment]
Yes, AFAICT. #621 gives us `--test-compiler`, which when set to `stage1` and in conjuction with `--only` gives us what the title of this issue is about. Closing this issue.

**Comment by snowleopard** [comment]
@alpmestan Awesome, thanks!

**Comment by snowleopard** [comment]
And also thanks to @chitrak7, of course!
