### ISSUE TITLE
Add high level overview on how the system works / is supposed to work

### ISSUE THREAD

**Issue by angerman** [snowleopard/hadrian#56]
Similar to #55.  Getting an idea how all the parts fit together would help with new people getting into the project.  I don't yet see myself qualified to document the system but, I think we should try to produce some high quality documentation. Maybe this can be done as part of #55 and have it live in the haddocks?

**Comment by snowleopard** [comment]
Yes, this is certainly for me to write. I will get on to it as soon as I can.

**Comment by angerman** [comment]
@snowleopard If you haven't started with this, I'd take this over with the high level documentation overview I'm working on right now. If we need more documentation you could either add ontop of that or write something more detailed? I'll try to document what I learned so far.

**Comment by snowleopard** [comment]
@angerman Yes, please take over. This week is going to be difficult for me in terms of spare coding time.

I will do a revision once you finish; feel free to leave some spots undocumented leaving as many TODO's for me as you like.

**Comment by angerman** [comment]
For the `/doc` part, should we try to use [read the docs](https://readthedocs.org)? [stack](http://haskellstack.org) uses that as well, and I find it quite good to read.

In anywise, if anything specific should be covered, let's try to keep track of that in this ticket.

**Comment by snowleopard** [comment]
@angerman I am not sure why, but I find the `stack` documentation confusing. It always felt complicated and daunting to me, although it's hard to point out the exact reason. Not sure if `readthedocs` contributed to this perception.

Personally, I'd prefer a simple Markdown document for the `/doc` part in the first instance. Once it starts to outgrow this simple format we may consider other options.

**Comment by ndmitchell** [comment]
I dislike the stack stuff too. Markdown is simple and clean on GitHub. I suggest once we outgrow a couple of pages, we simplify the build system - this stuff isn't meant to be rocket science!

**Comment by snowleopard** [comment]
@ndmitchell :+1:

**Comment by angerman** [comment]
Ohh, readthedocs is just a presentation layer using markdown or reStructuredText, stack's documentation is in their doc folder in markdown as well see https://github.com/commercialhaskell/stack/tree/stable/doc

So it must be either the presentation or the writing :-)

Let's stick with bare `/doc` for now then.

**Comment by snowleopard** [comment]
A high-level overview of Hadrian can now be found in the Haskell Symposium 2016 paper, which is available here: https://www.staff.ncl.ac.uk/andrey.mokhov/Hadrian.pdf. There is a also a Haskell eXchange 2016 talk: https://skillsmatter.com/skillscasts/8722-meet-hadrian-a-new-build-system-for-ghc.

I've linked the talk and the paper in the project README, so I think we can now close this.
