### ISSUE TITLE
Missing (or bad) header file: fs.h: in unlit

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#579]
```
hadrian: Missing dependency on a foreign library:
* Missing (or bad) header file: fs.h
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.If the
library file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
If the header file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.

shakeArgsWith   0.000s    0%                           
Function shake  0.218s    2%                           
Database read   0.000s    0%                           
With database   0.000s    0%                           
Running rules   7.386s   97%  =========================
Total           7.604s  100%                           
Error when running Shake build system:
* _build/stage1/bin/unlit
* OracleQ (PackageDataFile (Context {stage = Stage1, package = Package {pkgLanguage = Haskell, pkgType = Program, pkgName = "unlit", pkgPath = "utils/unlit"}, way = v}))
* _build/stage1/utils/unlit/setup-config
* _build/stage0/bin/unlit
* OracleQ (PackageDataFile (Context {stage = Stage0, package = Package {pkgLanguage = Haskell, pkgType = Program, pkgName = "unlit", pkgPath = "utils/unlit"}, way = v}))
* _build/stage0/utils/unlit/setup-config
ExitFailure 1
```

-----

{'ghc-git-hash': '5c9bc0771f426de2b99d6bb3a0f1d2eeaa91c710', 'hadrian-git-hash': '64da39cc9f955d7c1492ab39927a8e0849b23f00', 'gcc-version': '5.4.0', 'clean': True, 'duration': 13.175835371017456, 'exit-code': 1, 'stage0-ghc-version': '8.2.2', 'timestamp': 'Tue Apr 24 15:23:21 2018', 'platform': 'Linux-4.13.0-38-generic-x86_64-with-Ubuntu-16.04-xenial', 'flavour': 'quickest'}

**Comment by izgzhen** [comment]
```
$ cat ../utils/unlit/unlit.cabal
cabal-version: 2.1
Name: unlit
Version: 0.1
Copyright: XXX
License: BSD-3-Clause
Author: XXX
Maintainer: XXX
Synopsis: Literate program filter
Description: XXX
Category: Development
build-type: Simple

Executable unlit
    Default-Language: Haskell2010
    Main-Is: unlit.c
    C-Sources: unlit.c, fs.c
    Includes: fs.h
```

**Comment by izgzhen** [comment]
@Mistuke similar to https://github.com/snowleopard/hadrian/issues/554

**Comment by Mistuke** [comment]
If they can't be found then something went wrong with your configure step.
The Hadrian CI is finding them and building fine so I think it's a local
issue.

Check the output of configure

**Comment by izgzhen** [comment]
Thanks! I removed everything outside the tree and trying to rebuild now

**Comment by izgzhen** [comment]
> Check the output of configure

https://gist.github.com/izgzhen/1bb69b0aa67bc1e367b82da3d6f6dade

Still the same after cleaning up.

**Comment by snowleopard** [comment]
@izgzhen I've just restarted Travis to check if it might fail with GHC HEAD.

**Comment by Mistuke** [comment]
The make based version doesn't use the cabal file it looks like. But the
cabal file looks correct to me and the files are in the right place. Not
sure what the problem here is. Especially if it also can't find the C file.

**Comment by snowleopard** [comment]
Looks like no CI bots hit this issue.

**Comment by izgzhen** [comment]
I found what is going on! if I used `-c` of `build.sh`, instead of manually `./configure` and then run `build.sh` without `-c`, it will error.

I used to `./configure`, so I wonder if this is an expected behaviour?

**Comment by snowleopard** [comment]
> I used to `./configure`, so I wonder if this is an expected behaviour?

@izgzhen Definitely not expected. Running `boot` + `configure` at the GHC root should be equivalent to running Hadrian with `-c`.

**Comment by Mistuke** [comment]
My guess is that the ln destination for the copies need to be prepend with
$srcdir/ i think that would fix it. But i can't test till later.

**Comment by Mistuke** [comment]
@izgzhen can you try in your GHC source tree changing these lines
https://github.com/ghc/ghc/blob/master/configure.ac#L676

so they look like

```
ln -f -v $srcdir/utils/fs/fs.* $srcdir/utils/lndir/
```

so appending `$srcdir/` to each. If this doesn't work could you attach the `config.status` file for the working and not working builds? Thanks. All my source trees are currently dirty so I can't easily try myself.

**Comment by izgzhen** [comment]
@Mistuke appending `$srcdir` does work:

```diff
diff --git a/configure.ac b/configure.ac
index a8b8681a36..cf614e64eb 100644
--- a/configure.ac
+++ b/configure.ac
@@ -673,8 +673,8 @@ dnl --------------------------------------------------------------
 dnl ** Copy the files from the "fs" utility into the right folders.
 dnl --------------------------------------------------------------
 AC_MSG_NOTICE([Creating links for in-tree file handling routines.])
-ln -f -v utils/fs/fs.* utils/lndir/
-ln -f -v utils/fs/fs.* utils/unlit/
+ln -f -v $srcdir/utils/fs/fs.* $srcdir/utils/lndir/
+ln -f -v $srcdir/utils/fs/fs.* $srcdir/utils/unlit/
 ln -f -v utils/fs/fs.* rts/
 ln -f -v utils/fs/fs.h libraries/base/include/
 ln -f -v utils/fs/fs.c libraries/base/cbits/
```

**Comment by Mistuke** [comment]
Ah great, I'll submit a patch later today

**Comment by izgzhen** [comment]
@Mistuke wait a bit .. it might be a false positive. I was toying with cross compilation, and it failed in a similar way.

**Comment by Mistuke** [comment]
@izgzhen Can you tell me what I need to do to reproduce this? I'm not entirely sure how Hadrian does the out of tree build.

**Comment by izgzhen** [comment]
@Mistuke how is this going on now?

**Comment by Mistuke** [comment]
I've tried to reproduce it a couple of times and couldn't. I also don't understand why there would be any difference at all between running `./configure` manually and `hadrian -c`. Also cabal is able to build the `unlit` package after a configure just fine. So I don't think this is a problem with these files.

**Comment by izgzhen** [comment]
I can't reproduce this now either :( Thanks for the information! I will close this issue.

**Comment by jfischoff** [comment]
FWIW I'm running into this as well. It happens with the old make build too.

**Comment by snowleopard** [comment]
@jfischoff As you can see from the above discussion, this appears to be a hard-to-reproduce issue. If it persists, I suggest you report it on https://gitlab.haskell.org/ghc/ghc/issues, since Hadrian development moved to the GHC tree.

**Comment by ggreif** [comment]
Try to re-`configure`, I have seen header files disappearing when
cleaning, but they got recreated on `configure`. It always struck me
as odd.

**Comment by jfischoff** [comment]
I think I figured out what the issue is. I am using a shared folder with vagrant and virtualbox. I changed the configuration to bidirectional syncing based on the "virtualbox" type. This disables hard links which caused an issue in setup I didn't see initially.

**Comment by snowleopard** [comment]
@jfischoff Good to hear you found a fix! 

@ggreif Thanks for the hint :)
