### ISSUE TITLE
nix.shell: can't build happy

### ISSUE THREAD

**Issue by sgillespie** [snowleopard/hadrian#609]
I'm running NixOS, and I'm running `nix-shell` from `ghc/hadrian`:

```
Linking dist/build/happy/happy ...
haddockPhase
installing
: getDirectoryContents:openDirStream: does not exist (No such file or directory)
builder for '/nix/store/mqfjgf36rpzxmc7142nsh8h0lrfxpglj-happy-1.19.8.drv' failed with exit code 1
cannot build derivation '/nix/store/lllrigz3fby0pbf01lakmzgz5y057xxf-hadrian-0.1.0.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/lllrigz3fby0pbf01lakmzgz5y057xxf-hadrian-0.1.0.0.drv' failed
```

Any idea what to do here or how to get more information?

**Comment by snowleopard** [comment]
@sgillespie Thanks for reporting! I'm not a nix user myself, but let's ping @mpickering and @angerman who regularly commit to `shell.nix`.

**Comment by mpickering** [comment]
It's not clear what is happening here but @bgamari also ran into this same issue. I ran into it trying to build a different haskell project with HEAD.

**Comment by sgillespie** [comment]
I also run into the same problem running `build.nix.sh` and `build.stack.nix.sh`

**Comment by mpickering** [comment]
See https://github.com/haskell/cabal/issues/5318

**Comment by sgillespie** [comment]
This resolved it for me:

https://git.haskell.org/ghc.git/commitdiff/14f4347c28a2d8d45e795fd01bc0e547fe8738e6
