### ISSUE TITLE
Build fails with integer simple

### ISSUE THREAD

**Issue by chitrak7** [snowleopard/hadrian#629]
I think it has something to do with this commit
[https://github.com/ghc/ghc/commit/fe770c211631e7b4c9b0b1e88ef9b6046c6585ef](url)

**Comment by alpmestan** [comment]
Indeed, here's the code introducing the error message that we're seeing: https://github.com/ghc/ghc/commit/fe770c211631e7b4c9b0b1e88ef9b6046c6585ef#diff-6e194c689dd071b72b0bf8b07f301fb3R1572

**Comment by sighingnow** [comment]
I have tested with ghc-8.4.2, both the `default` flavor and the `quickest` flavor`. The only difference to build the stage1 library `base` is the optimization level.

+ For `default`, we pass `-O2` to `stage0/bin/ghc`
+ For `quickest`, we pass `-O0` to `stage0/bin/ghc`

The panic only occurs when building with `quickest` flavor.

**If we build the `GHC/Natural.o` with `-O` (or `-O2`), then rebuild the `GHC/Num.o`, the panic disappears.**

**Comment by sighingnow** [comment]
I have reported this issue to GHC: https://phabricator.haskell.org/rGHCfe770c211631e7b4c9b0b1e88ef9b6046c6585ef#80828

**Comment by snowleopard** [comment]
@sighingnow Many thanks for reporting and finding a workaround. If there is no quick fix in GHC, we can add `-O` just when building `Natural.o`.

**Comment by sighingnow** [comment]
If we build the `GHC.Natural` with `-O0 -fno-omit-interface-pragmas` and build `GHC.Num` with `-O0 -fno-ignore-interface-pragmas`, the panic disappears.

**Comment by alpmestan** [comment]
Reported on Trac: https://ghc.haskell.org/trac/ghc/ticket/15286#ticket

Ben has started looking into this a little earlier today.

**Comment by sighingnow** [comment]
I have left some comments under the ticket, may be helpful.

**Comment by alpmestan** [comment]
Yes they are, thanks a lot @sighingnow!

**Comment by snowleopard** [comment]
I believe this has been fixed.
