### ISSUE TITLE
Build fails with Error: Data.Binary.Get.runGet at position 362: not enough bytes

### ISSUE THREAD

**Issue by chitrak7** [snowleopard/hadrian#631]
@snowleopard 
As I was trying to rebase, I ran across this error.
Error when running Shake build system:
* _build/stage1/lib/bin/unlit
* OracleQ (PackageDataFile (Context {stage = Stage1, package = Package {pkgLanguage = Haskell, pkgType = Program, pkgName = "unlit", pkgPath = "utils/unlit"}, way = v}))
* _build/stage1/utils/unlit/setup-config
* _build/stage0/lib/bin/unlit
* OracleQ (PackageDataFile (Context {stage = Stage0, package = Package {pkgLanguage = Haskell, pkgType = Program, pkgName = "unlit", pkgPath = "utils/unlit"}, way = v}))
Data.Binary.Get.runGet at position 362: not enough bytes
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:351:5 in binary-0.8.5.1:Data.Binary.Get

I then pulled hadrians master but the error still persists.

**Comment by sighingnow** [comment]
PR #627 added a new filed `mainIs` to `PackageData`. You need do `hadrian clean`, then rebuild hadrian and  build ghc with hadrian from scratch.

**Comment by snowleopard** [comment]
@sighingnow Thanks! Looks like this is indeed the reason.

@chitrak7 Can you confirm if this worked?

**Comment by chitrak7** [comment]
yes, running clean removed the errors.
