### ISSUE TITLE
Support GHCi debugger with -fexternal-interpreter

### ISSUE THREAD

**Issue by alpmestan** [snowleopard/hadrian#642]
See https://phabricator.haskell.org/D4955#inline-38448.

**Comment by alpmestan** [comment]
Should we pass that flag to the `CabalFlags` builder or to the `GhcCabal Conf` one?

**Comment by snowleopard** [comment]
@alpmestan I'd like to get rid of `CabalFlags` at some point (hope to find time for this soon!), so I'd prefer to start switching over to `GhcCabal Conf` which is more consistent with the rest of the infrastructure. But if doing it using `CabalFlags` is much easier, go for it :)

**Comment by alpmestan** [comment]
Done in #648.
