### ISSUE TITLE
Build more variants of profiled runtime systems (normal, threaded, debug, threaded debug, ...) ?

### ISSUE THREAD

**Issue by alpmestan** [snowleopard/hadrian#681]
I just saw https://phabricator.haskell.org/D5140 by @osa1 and I suspect we might have to do a similar thing in hadrian. Unless we're already doing this, @snowleopard @angerman ?

**Comment by snowleopard** [comment]
@alpmestan I don't think we do this. Here are the ways we currently build RTS by default:

https://github.com/snowleopard/hadrian/blob/master/src/Settings/Default.hs#L154-L164

**Comment by alpmestan** [comment]
Hmm, shouldn't we include the `profiling` way in that `[threadedProfiling]` list?

Now, for the issue at hand, we'll also want to add `debugProfiling` and `threadedDebugProfiling` I suppose?

**Comment by snowleopard** [comment]
@alpmestan Yes, I think so. Bear in mind that this list was initially shrunk to "whatever Hadrian can compile now", so it could easily mismatch the one from Make.

Perhaps, we should rename this issue to bringing Hadrian in sync with Make w.r.t. RTS ways.

**Comment by alpmestan** [comment]
Yes. Do you see any other change we should make besides the one I suggested in my previous comment?

**Comment by snowleopard** [comment]
No, I don't see any other change. I'm surprised we don't have `profiling` included into RTS ways now.

**Comment by alpmestan** [comment]
#682 was about the hadrian side of things. Here is the GHC patch that goes with it, necessary to actually produce the new ways (_debug_p, _thr_debug_p): https://phabricator.haskell.org/D5142

**Comment by snowleopard** [comment]
@alpmestan Thank you! Please close this once your patch makes its way to GHC HEAD.

**Comment by alpmestan** [comment]
[Merged](https://phabricator.haskell.org/rGHC5d67d069608f04b4c5eeee73b44bf27562adc5a3).
