### ISSUE TITLE
testsuite: support figuring out the list of tests from $PWD

### ISSUE THREAD

**Issue by alpmestan** [snowleopard/hadrian#685]
@simonmar requested this in https://github.com/snowleopard/hadrian/issues/669#issuecomment-420329845

> Hi @alpmestan, this might not be the right place but I wanted to ask about workflows for the testsuite. Very often I do something like
>
> ```
> cd testsuite/tests/codeGen/should_run
> make TEST=cgrun001 WAY=optasm CLEANUP=0 EXTRA_HC_OPTS=-debug
> ```
> 
> to run a single test with some custom options. This is really convenient (and fast). Will we have something equally convenient with Hadrian, and will it be just as fast?

**Comment by snowleopard** [comment]
I believe this has been fixed.
