### ISSUE TITLE
testsuite: add CLI flag for specifying extra options to pass to ghc

### ISSUE THREAD

**Issue by alpmestan** [snowleopard/hadrian#686]
So that these would apply to whatever tests we will be running. Requested by @simonmar in https://github.com/snowleopard/hadrian/issues/669#issuecomment-420329845

In the make build system, all one has to do is to use `EXTRA_HC_OPTS`, as can be seen in Simon's comment.

**Comment by snowleopard** [comment]
I believe this has been fixed.
