### ISSUE TITLE
Issue on Trac: 15908

### ISSUE THREAD

**Issue by ggreif** [snowleopard/hadrian#707]
This is just a pointer to a [trac ticket](https://ghc.haskell.org/trac/ghc/ticket/15908). My first one and not sure how the process works.

I have experienced another problem too, on Linux: -o does not work. I did `hadrian/build.sh -c --build-root=/some/other/place/_build`. Directory got created but the build failed.

**Comment by snowleopard** [comment]
@ggreif Thank you! We have decided to create all new tickets on GHC Trac, so I'm going to close this issue if you don't mind.

I suggest you create a separate Trac ticket for the `-o` problem, so we can track it there, too. It would be great if you also add me to `Cc`, so I get notified (my Trac username is `snowleopard`).
